import { adminApi, AdminApiError } from './admin-client';
const root=document.querySelector('[data-problems]');
if(root){
 const el=(id:string)=>document.getElementById(id)!;let generation=0,current:string|null=null,version=0,cursor:string|null=null,ready=false;const pending=new Map<string,string>();
 const status=el('problem-status'),detail=el('problem-detail'),list=el('problem-list');
 const clear=()=>{generation++;pending.clear();ready=false;current=null;version=0;cursor=null;list.replaceChildren();detail.replaceChildren();(el('problem-create') as HTMLFormElement).reset();status.textContent='';el('problem-next').hidden=true;};
 const failure=(e:unknown)=>{if(e instanceof AdminApiError&&[401,403].includes(e.status)){clear();return;}status.textContent=e instanceof Error?e.message:'操作失败';};
 const node=(tag:string,text:string)=>{const n=document.createElement(tag);n.textContent=text;return n;};
 function form(title:string,operation:string,fields:{name:string;label:string;options?:string[];type?:string;value?:string;required?:boolean}[]){const f=document.createElement('form');f.dataset.operation=operation;f.append(node('h3',title));for(const field of fields){const label=node('label',field.label);let input:HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement;
 if(field.options){input=document.createElement('select');for(const value of field.options){const o=document.createElement('option');o.value=value;o.textContent=value;input.append(o);}}
 else if(field.type==='textarea')input=document.createElement('textarea');else {input=document.createElement('input');input.type=field.type??'text';}input.name=field.name;input.required=field.required!==false;if(field.value)input.value=field.value;label.append(input);f.append(label);}const button=node('button','保存');f.append(button);f.addEventListener('submit',event=>{event.preventDefault();void write(operation,f);});return f;}
 async function load(next:string|null=null){const g=++generation;try{const p=await adminApi<any>('problems'+(next?'?cursor='+encodeURIComponent(next):''));if(g!==generation||!ready)return;list.replaceChildren();for(const item of p.items){const b=node('button',`${item.title} · ${item.repairStage}`);b.addEventListener('click',()=>void show(item.id));list.append(b);}cursor=p.nextCursor;el('problem-next').hidden=!cursor;status.textContent='问题列表已加载';}catch(e){if(g===generation)failure(e);}}
 async function show(id:string){const g=++generation;status.textContent='正在加载问题…';try{const d=await adminApi<any>('problems/'+encodeURIComponent(id));if(g!==generation||!ready)return;current=id;version=d.problem.version;detail.replaceChildren();detail.append(node('h2',d.problem.title),node('p',`${id} · ${d.problem.repairStage} · 版本 ${version}`));
 detail.append(form('问题材料','update',[{name:'description',label:'描述',type:'textarea',value:d.problem.description},{name:'reproduction',label:'复现步骤',type:'textarea',value:d.problem.reproduction,required:false},{name:'versionInfo',label:'版本信息',value:d.problem.versionInfo,required:false},{name:'reason',label:'修改原因'}]));
 detail.append(node('h3','关联证据与用户'));for(const link of d.links){const row=node('p',`${link.kind}: ${link.relatedId} `);if(link.kind==='feedback'){const a=node('a','在 T02 逐条核验');a.setAttribute('href','/admin/feedback/detail/?id='+encodeURIComponent(link.relatedId));row.append(a);}const b=node('button','解除关联');b.addEventListener('click',()=>{if(confirm('确认解除此关联？原反馈会保留。'))void action('unlink',{kind:link.kind,relatedId:link.relatedId,confirmed:true,reason:'管理员确认解除关联'});});row.append(b);detail.append(row);}detail.append(node('p','相关用户 ID：'+d.relatedUsers.map((u:any)=>u.userId).join('、')));
 detail.append(form('关联 / 归并','link',[{name:'kind',label:'类型',options:['feedback','user','content','anomaly','run','problem']},{name:'relatedId',label:'对象 ID（内容格式 ID@VERSION）'},{name:'reason',label:'关联依据'}]));
 detail.append(node('h3','修复引用（最多100条；人工查询结果由操作者负责）'));for(const ref of d.references){detail.append(node('p',`${ref.id} · ${ref.kind} · ${ref.value} · ${ref.trust} · ${ref.source} · ${ref.active?'有效':'已解除'}`));if(ref.active){const b=node('button','解除修复引用');b.addEventListener('click',()=>{if(confirm('解除此引用并重置修复进度？'))void action('remove-reference',{refId:ref.id,reason:'管理员确认错误修复关联'});});detail.append(b);}}
 detail.append(form('新增仓库 / 修复 / 发布引用','references',[{name:'kind',label:'类型',options:['repository','issue','pr','commit','release']},{name:'value',label:'链接或版本标识'},{name:'trust',label:'来源状态',options:['manual','verified','query_failed']},{name:'source',label:'实际查询方式、对象及结果；手工填写说明'},{name:'checkedAt',label:'实际查询时间（带时区ISO，人工填写可空）',required:false},{name:'reason',label:'记录原因'}]));
 detail.append(form('修复进度','progress',[{name:'repairStage',label:'待修复 / 候选 / 已合并 / 已发布 / 待验证 / 验证通过',options:['pending','candidate','merged','released','verify_pending','verified']},{name:'refId',label:'已查询核验的 PR 或提交引用 ID',required:false},{name:'releaseRefId',label:'已核验发布引用 ID',required:false},{name:'reason',label:'当前进度的实际证据'}]));
 detail.append(form('线上验证（不会自动关闭关联反馈）','verify',[{name:'refId',label:'修复引用 ID'},{name:'releaseRefId',label:'发布引用 ID'},{name:'result',label:'验证结果',options:['passed','failed']},{name:'note',label:'验证步骤、影响范围和结果',type:'textarea'},{name:'reason',label:'记录原因'}]));for(const check of d.checks)detail.append(node('p',`${check.result} · 修复 ${check.refId} · 发布 ${check.releaseRefId} · ${check.note}`));
 detail.append(node('h3','AI 辅助诊断'));detail.append(node('p','只发送你在下方选择并确认脱敏的材料。默认不自动复制邮箱、凭证、截图、内部备注或日志。截图为独立可选输入，需要确认已遮盖私有内容。'));
 detail.append(form('选择诊断材料','diagnose',[{name:'description',label:'已脱敏问题描述',type:'textarea'},{name:'reproduction',label:'复现步骤（可空）',type:'textarea',required:false},{name:'versions',label:'版本信息（可空）',required:false},{name:'errorSummary',label:'脱敏错误摘要（禁止完整日志）',type:'textarea',required:false},{name:'screenshots',label:'明确选择截图：每行反馈ID:索引；默认留空',type:'textarea',required:false},{name:'budget',label:'问题累计预算上限 USD（模拟器不收费）',type:'number',value:'0'},{name:'reason',label:'诊断原因'}]));
 for(const run of d.runs){const section=document.createElement('section');section.dataset.diagnosticRun=run.id;section.append(node('h3',`${run.id} · ${run.state}`),node('p',`诊断建议 · ${run.promptVersion} · 错误 ${run.errorCode??'无'} · 尝试 ${run.attempt}`),node('p',`模型 ${run.config.analyst.model} · 输入上限 ${run.config.maxInputTokens} · 预算 ${run.budget} USD · 预留 ${run.reserved} · 费用 ${run.actualCost??'未知（模拟器未计费）'}`),node('pre',JSON.stringify({selectedMaterial:run.material,usage:run.usage},null,2)),node('pre',JSON.stringify(run.result??{message:'未获得可用建议'},null,2)));if(['queued','running'].includes(run.state)){const b=node('button','取消诊断');b.addEventListener('click',()=>void action('cancel-run',{runId:run.id,reason:'管理员取消诊断'}));section.append(b);}if(['needs_review','cancelled'].includes(run.state))section.append(form('供应商执行结果核查','reconcile-run',[{name:'runId',label:'任务 ID',value:run.id},{name:'outcome',label:'实际执行结果',options:['executed','not_executed']},{name:'note',label:'供应商核查证据'},{name:'actualCost',label:'已知费用 USD，未知留空',type:'number',required:false},{name:'reason',label:'核查原因'}]));detail.append(section);}
 detail.append(node('h3','供开发者复制的任务描述'),node('pre',d.developerTask));status.textContent='问题详情已加载';}catch(e){if(g===generation)failure(e);}}
 async function action(op:string,input:Record<string,unknown>){if(!current||!ready)return;const id=current,g=generation;status.textContent='正在提交…';const body={...input,expectedVersion:version},binding=id+':'+op+':'+JSON.stringify(body),key=pending.get(binding)??crypto.randomUUID();pending.set(binding,key);try{await adminApi('problems/'+encodeURIComponent(id)+'/'+op,body,key);pending.delete(binding);if(g!==generation||!ready)return;await show(id);}catch(e){if(g===generation)failure(e);}}
 async function write(op:string,f:HTMLFormElement){const values=Object.fromEntries([...new FormData(f)].map(([k,v])=>[k,String(v).trim()]));let input:Record<string,unknown>={...values};if(op==='link'){if(!confirm('确认归并 / 关联？不会修改原反馈状态。'))return;input.confirmed=true;}
 if(op==='progress'){if(!confirm('确认该进度有独立证据？合并不证明上线，上线不证明已解决。'))return;input.confirmed=true;}
 if(op==='verify')input.environment='online';if(op==='reconcile-run')input.actualCost=values.actualCost?Number(values.actualCost):null;
 if(op==='update'){for(const k of ['reproduction','versionInfo'])if(!values[k])delete input[k];}
 if(op==='diagnose'){if(!confirm('确认文本已脱敏，并明确允许发送所选截图（如有）给模型？'))return;const screenshots=values.screenshots?values.screenshots.split('\n').map(line=>{const split=line.lastIndexOf(':');return {feedbackId:line.slice(0,split),index:Number(line.slice(split+1))};}):[];input={reason:values.reason,budget:Number(values.budget),material:{description:values.description,reproduction:values.reproduction,versions:values.versions,errorSummary:values.errorSummary,redactionConfirmed:true,screenshots}};}
 await action(op,input);}
 el('problem-create').addEventListener('submit',async event=>{event.preventDefault();if(!ready)return;const g=generation;try{const v=Object.fromEntries(new FormData(event.target as HTMLFormElement)),body={...v,reason:'管理员创建问题'},binding='create:'+JSON.stringify(body),key=pending.get(binding)??crypto.randomUUID();pending.set(binding,key);const r=await adminApi<any>('problems',body,key);pending.delete(binding);if(g!==generation||!ready)return;await show(r.id);}catch(e){if(g===generation)failure(e);}});
 el('problem-refresh').addEventListener('click',()=>void (current?show(current):load()));el('problem-next').addEventListener('click',()=>void load(cursor));document.addEventListener('maas:admin-ready',()=>{ready=true;const id=new URLSearchParams(location.search).get('id');void (id?show(id):load());});document.addEventListener('maas:admin-cleared',clear);window.addEventListener('pagehide',clear);
}
