import {adminApi,AdminApiError,type AdminPage} from './admin-client';
type Row=Record<string,any>;
const el=(id:string)=>document.getElementById(id),label:Record<string,string>={success:'成功',partial:'部分失败',failed:'失败',unchanged:'无变化',not_run:'未执行',unknown:'未知',fetch_failed:'抓取失败',parse_failed:'解析失败',normal:'正常',degraded:'异常',stale:'记录过期',fresh:'新鲜',full:'完整',missing:'缺失',passed:'通过',completed:'完成',succeeded:'执行成功',queued:'排队',running:'运行中',needs_review:'需核查',cancelled:'取消',open:'待处理',acknowledged:'已确认',in_progress:'处理中',ignored:'已忽略',resolved:'已解决',schedule:'定时',manual:'手动',workflow:'工作流',worker:'周报worker'};
const word=(v:unknown)=>label[String(v)]??String(v??'未知');
const time=(v:unknown)=>typeof v==='number'?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+' 北京时间':'未知';
const node=(tag:string,value:string)=>{const n=document.createElement(tag);n.textContent=value;return n;};
let generation=0,cursor:string|null=null,anomalyCursor:string|null=null;
function clear(){generation++;el('monitor-sources')?.replaceChildren();el('monitor-runs')?.replaceChildren();el('monitor-anomalies')?.replaceChildren();el('monitor-status')!.textContent='';cursor=anomalyCursor=null;for(const id of ['monitor-next','monitor-anomaly-next'])if(el(id))el(id)!.hidden=true;}
function filters(){const p=new URLSearchParams();const form=el('monitor-filter') as HTMLFormElement;for(const [k,v]of new FormData(form))if(String(v).trim())p.set(k,String(v).trim());return p;}
function failure(e:unknown){el('monitor-status')!.textContent=e instanceof AdminApiError?e.message+' · '+e.requestId:'加载失败，请重试';if(e instanceof AdminApiError&&[401,403].includes(e.status)){clear();document.dispatchEvent(new CustomEvent('maas:admin-cleared'));(el('admin-private') as HTMLElement).hidden=true;el('admin-status')!.textContent=e.status===401?'请使用页面顶部的登录入口登录。':'无后台访问权限';}}
function auditLink(id:string){const a=node('a','查看处理审计') as HTMLAnchorElement;a.href='/admin/audit/?targetType=monitor_anomaly&targetId='+encodeURIComponent(id);return a;}
function runLink(r:Row){if(typeof r.runLink==='string'&&/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/actions\/runs\/\d+$/.test(r.runLink)){const a=node('a','受控运行诊断') as HTMLAnchorElement;a.href=r.runLink;a.target='_blank';a.rel='noopener noreferrer';return a;}return node('p','无运行链接；在受控终端按运维说明核查原任务。');}
async function load(more=false){const current=++generation;el('monitor-status')!.textContent='正在加载…';try{const p=filters();if(more&&cursor)p.set('cursor',cursor);if(el('monitor-sources')){const data=await adminApi<{items:Row[],asOf:number,truncated:boolean}>('monitor/sources?'+p);if(current!==generation)return;el('monitor-sources')!.replaceChildren(...data.items.map(s=>{const tr=document.createElement('tr');for(const v of [s.name+' / '+s.platform,word(s.health)+' / '+word(s.outcome),time(s.latestAttemptAt),time(s.latestSuccessAt),time(s.dataThrough),s.consecutiveFailures===null?'未知':String(s.consecutiveFailures)+(s.failureCountTruncated?'（有截断）':''),word(s.coverage)+' / '+(s.errorSummary??'无已知异常')])tr.append(node('td',v));return tr;}));el('monitor-status')!.textContent=`检查于 ${time(data.asOf)} · ${data.items.length}个信源${data.truncated?'（最多500个）':''}`;if(!data.items.length)el('monitor-status')!.textContent+=' · 无已接入信源';await anomalies(false,current);}else{const data=await adminApi<AdminPage<Row>>('monitor/runs?'+p);if(current!==generation)return;if(!more)el('monitor-runs')!.replaceChildren();for(const r of data.items){const box=node('article','');box.className='admin-card';box.append(node('h2',r.kind+' / '+r.stage),node('p',`运行 ${r.id} · ${word(r.trigger)} · ${word(r.state)} · 结果 ${word(r.result)}`),node('p',`开始 ${time(r.startedAt)} · 结束 ${time(r.finishedAt)}`),node('p',`输入 ${r.inputVersion??'未知'} → 输出 ${r.outputVersion??'未知'}`),node('p',`校验 ${word(r.validation)} · 发布 ${word(r.publication)} · ${r.errorSummary??'无已知错误'}`),node('p','信源：'+(r.sources.map((s:Row)=>s.sourceId+' '+word(s.outcome)).join('；')||'无关联记录')),node('p',r.operation),runLink(r));if(r.kind==='editorial'){const a=node('a','进入周报工作台') as HTMLAnchorElement;a.href='/admin/weekly/';box.append(a);}el('monitor-runs')!.append(box);}cursor=data.nextCursor;el('monitor-next')!.hidden=!cursor;el('monitor-status')!.textContent=data.items.length?'任务已加载 · 北京时间':'无任务记录，状态未知';}}catch(e){if(current===generation)failure(e);}}
async function anomalies(more=false,current=generation){try{const p=new URLSearchParams();if(more&&anomalyCursor)p.set('cursor',anomalyCursor);const data=await adminApi<AdminPage<Row>>('monitor/anomalies?'+p);if(current!==generation)return;if(!more)el('monitor-anomalies')!.replaceChildren();for(const a of data.items){const box=node('article','');box.className='admin-card';box.append(node('h3',a.summary+' · '+word(a.state)),node('p',`${a.sourceId??'任务'} · ${a.runId} · ${time(a.updatedAt)}`));const form=document.createElement('form');const select=document.createElement('select');select.setAttribute('aria-label','处理状态');for(const v of ['acknowledged','in_progress','ignored','resolved']){const o=node('option',word(v)) as HTMLOptionElement;o.value=v;select.append(o);}if(['acknowledged','in_progress','ignored','resolved'].includes(a.state))select.value=a.state;const reason=document.createElement('input');reason.placeholder='处理原因（必填）';reason.required=true;reason.maxLength=1000;reason.setAttribute('aria-label','处理原因');const ref=document.createElement('input');ref.placeholder='后续成功运行ID（解决时必填）';ref.setAttribute('aria-label','核验运行');const button=node('button','保存处理') as HTMLButtonElement;const status=node('p','');status.setAttribute('role','status');form.append(select,reason,ref,button);const related=node('a','查看关联运行') as HTMLAnchorElement;related.href='/admin/tasks/?runId='+encodeURIComponent(a.runId);box.append(form,status,related,document.createTextNode(' · '),auditLink(a.id));form.addEventListener('submit',async event=>{event.preventDefault();const epoch=generation,key=crypto.randomUUID();button.disabled=true;try{await adminApi('monitor/anomalies/'+encodeURIComponent(a.id),{state:select.value,reason:reason.value,expectedVersion:a.version,resolutionRunId:ref.value||null},key);if(epoch===generation)await load();}catch(e){if(epoch===generation){status.textContent=e instanceof Error?e.message:'保存失败';if(e instanceof AdminApiError&&[401,403].includes(e.status))failure(e);}}finally{button.disabled=false;}});el('monitor-anomalies')!.append(box);}anomalyCursor=data.nextCursor;el('monitor-anomaly-next')!.hidden=!anomalyCursor;if(!data.items.length&&!more)el('monitor-anomalies')!.append(node('p','没有已记录异常；不代表历史完整。'));}catch(e){if(current===generation)failure(e);}}
if(el('monitor-status')){for(const k of ['runId','sourceId']){const field=document.querySelector<HTMLInputElement>(`#monitor-filter [name=${k}]`);if(field)field.value=new URLSearchParams(location.search).get(k)??'';}document.addEventListener('maas:admin-ready',()=>void load());document.addEventListener('maas:admin-cleared',clear);el('monitor-filter')!.addEventListener('submit',e=>{e.preventDefault();void load();});el('monitor-next')?.addEventListener('click',()=>void load(true));el('monitor-anomaly-next')?.addEventListener('click',()=>void anomalies(true));window.addEventListener('pagehide',clear);}
