import {adminApi,AdminApiError,type AdminPage} from './admin-client';
import {paymentTable,paymentText,paymentTime,paymentAmount} from './payment-view';
type Row=Record<string,unknown>;
let generation=0,ready=false,next:string|null=null,actionNext:string|null=null,differenceId='';
const el=(id:string)=>document.getElementById(id)!,form=el('payments-filter') as HTMLFormElement;
function clear(){generation++;ready=false;next=null;actionNext=null;differenceId='';for(const id of ['payments-items','payments-totals','payments-status','payments-detail-records','payments-detail-title'])el(id).replaceChildren();for(const id of ['payments-next','payments-detail','payments-actions-next'])el(id).hidden=true;for(const id of ['payments-filter','payments-range','payments-refund','payments-note']) (el(id) as HTMLFormElement).reset();}
function error(e:unknown,g:number){if(g===generation&&ready)el('payments-status').textContent=e instanceof Error?e.message:'查询失败，请重试';}
function totals(value:Row){el('payments-totals').replaceChildren();for(const [label,text]of [['币种',String(value.currency)],['时间范围',paymentTime(value.from)+' 至 '+paymentTime(value.to)+'（终点不含）'],['窗口内创建订单（不是收入）',String(value.orderCount)+' 笔 / '+paymentAmount(value.orderGross,value.currency)],['窗口内成功支付笔数',String(value.successfulPaymentCount)],['内部成功支付收入',paymentAmount(value.revenue,value.currency)],['内部成功退款',paymentAmount(value.refunds,value.currency)],['供应商支付记录',paymentAmount(value.providerRevenue,value.currency)],['供应商退款记录',paymentAmount(value.providerRefunds,value.currency)],['手续费',paymentAmount(value.fees,value.currency)],['实际结算',paymentAmount(value.settlement,value.currency)],['来源',String(value.source)]]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label!;dd.textContent=text!;el('payments-totals').append(dt,dd);}}
const common:[string,string,((r:Row)=>string)?][]=[['id','ID'],['state','状态'],['amount','金额',r=>paymentAmount(r.amount,r.currency)],['createdAt','时间',r=>paymentTime(r.createdAt)]];
function columns(kind:string):[string,string,((r:Row)=>string)?][]{
 if(kind==='subscriptions')return [['id','订阅ID'],['userId','用户'],['state','状态'],['periodEnd','周期结束',r=>paymentTime(r.periodEnd)],['nextRenewalAt','下次续费',r=>r.nextRenewalAt===null?'无已确认续费计划':paymentTime(r.nextRenewalAt)],['cancelAtPeriodEnd','停止续费'],['renewalFailed','续费失败']];
 if(kind==='differences')return [['id','差异ID'],['objectId','供应商对象'],['kind','差异类型'],['expected','内部金额',r=>paymentAmount(r.expected,r.currency)],['observed','供应商金额',r=>paymentAmount(r.observed,r.currency)],['source','来源'],['actionCount','处理记录数']];
 if(kind==='reconciliations')return [['id','对账ID'],['currency','币种'],['starts','起点',r=>paymentTime(r.starts)],['ends','终点',r=>paymentTime(r.ends)],['source','来源']];
 if(kind==='events')return [['providerEventId','供应商事件ID'],['provider','渠道'],['receivedAt','接收时间',r=>paymentTime(r.receivedAt)],['results','处理结果',r=>{const rows=r.results as Row[];return rows.length?paymentText(rows[0]?.state)+(rows[0]?.error?' / '+rows[0].error:''):'待处理';}]];
 return kind==='orders'?[...common,['refundState','退款状态'],['refundedAmount','已退金额',r=>paymentAmount(r.refundedAmount,r.currency)],['reservedRefundAmount','退款预留',r=>paymentAmount(r.reservedRefundAmount,r.currency)],['refundableAmount','可退余额',r=>paymentAmount(r.refundableAmount,r.currency)]]:common;
}
async function load(cursor?:string){if(!ready)return;const g=++generation;next=null;el('payments-items').replaceChildren();el('payments-next').hidden=true;el('payments-detail').hidden=true;const fields=new FormData(form),kind=String(fields.get('kind')),params=new URLSearchParams();for(const key of ['q','userId'])if(fields.get(key))params.set(key,String(fields.get(key)));if(cursor)params.set('cursor',cursor);try{const rows=await adminApi<AdminPage<Row>>('payments/'+kind+'?'+params);if(g!==generation||!ready)return;el('payments-items').append(paymentTable(rows.items,columns(kind),kind==='events'?undefined:{label:'详情',click:r=>void detail(kind,String(r.id))}));next=rows.nextCursor;el('payments-next').hidden=!next;el('payments-status').textContent=rows.items.length?'记录已加载':'没有符合条件的记录';}catch(e){error(e,g);}}
async function range(){if(!ready)return;const g=generation,p=new URLSearchParams(),fields=new FormData(el('payments-range') as HTMLFormElement);for(const [key,v] of fields)if(String(v).trim())p.set(key,String(v).trim());try{const t=await adminApi<Row>('payments/totals?'+p);if(g===generation&&ready)totals(t);}catch(e){error(e,g);}}
function section(label:string,rows:Row[],cols:[string,string,((r:Row)=>string)?][]){const heading=document.createElement('h3');heading.textContent=label;const wrap=document.createElement('div');wrap.className='admin-table-wrap';wrap.append(paymentTable(rows,cols));el('payments-detail-records').append(heading,wrap);}
async function detail(kind:string,id:string){if(!ready)return;const g=++generation;el('payments-detail-records').replaceChildren();el('payments-detail').hidden=true;actionNext=null;el('payments-actions-next').hidden=true;try{const value=await adminApi<Row>('payments/'+kind+'/'+encodeURIComponent(id));if(g!==generation||!ready)return;el('payments-detail-title').textContent='详情 · '+id;el('payments-detail').hidden=false;
 for(const [key,label,type]of [['order','订单','orders'],['subscription','订阅','subscriptions'],['refund','退款请求','refunds'],['difference','对账差异','differences'],['reconciliation','对账快照','reconciliations']])if(value[key!])section(label!,[value[key!] as Row],columns(type!));
 if(value.summary)totals(value.summary as Row);
 for(const [key,label,type]of [['orders','关联订单','orders'],['refunds','退款请求','refunds'],['differences','差异','differences']])if(Array.isArray(value[key!]))section(label!,value[key!] as Row[],columns(type!));
 for(const [key,label]of [['facts','已核验支付事实'],['records','供应商快照记录']])if(Array.isArray(value[key!]))section(label!,value[key!] as Row[],[['objectId','供应商对象'],['kind','类型'],['amount','金额',r=>paymentAmount(r.amount,r.currency)],['occurredAt','供应商时间',r=>paymentTime(r.occurredAt)]]);
 if(Array.isArray(value.attempts))section('支付尝试',value.attempts as Row[],[['providerObjectId','供应商对象'],['state','状态'],['createdAt','记录时间',r=>paymentTime(r.createdAt)]]);
 if(Array.isArray(value.results))section('退款处理结果',value.results as Row[],[['state','状态'],['source','来源'],['createdAt','时间',r=>paymentTime(r.createdAt)]]);
 if(value.actions){differenceId=id;renderActions(value.actions as AdminPage<Row>);(el('payments-note') as HTMLFormElement).querySelector<HTMLInputElement>('[name=id]')!.value=id;}
 if(value.order)(el('payments-refund') as HTMLFormElement).querySelector<HTMLInputElement>('[name=orderId]')!.value=String((value.order as Row).id);
 }catch(e){error(e,g);}}
function renderActions(rows:AdminPage<Row>){section('处理记录（追加，不修改交易事实）',rows.items,[['actorId','操作者'],['note','记录'],['createdAt','时间',r=>paymentTime(r.createdAt)]]);actionNext=rows.nextCursor;el('payments-actions-next').hidden=!actionNext;}
document.addEventListener('maas:admin-ready',()=>{ready=true;void load();void range();});document.addEventListener('maas:admin-cleared',clear);window.addEventListener('pagehide',clear);
form.addEventListener('submit',e=>{e.preventDefault();void load();});el('payments-range').addEventListener('submit',e=>{e.preventDefault();void range();});el('payments-next').addEventListener('click',()=>{if(next)void load(next);});el('payments-actions-next').addEventListener('click',async()=>{if(!ready||!actionNext)return;const g=generation;try{const rows=await adminApi<AdminPage<Row>>('payments/differences/'+encodeURIComponent(differenceId)+'/actions?cursor='+encodeURIComponent(actionNext));if(g===generation&&ready)renderActions(rows);}catch(e){error(e,g);}});
for(const [id,op] of [['payments-refund','refund'],['payments-note','annotate']]){const f=el(id!) as HTMLFormElement;let key=crypto.randomUUID(),lastInput='';f.addEventListener('submit',async e=>{e.preventDefault();if(!ready)return;const g=generation,data=new FormData(f),target=String(data.get(op==='refund'?'orderId':'id')),input=op==='refund'?{amount:Number(data.get('amount')),reason:String(data.get('reason'))}:{note:String(data.get('note')),reason:String(data.get('reason'))},binding=JSON.stringify({target,input});if(lastInput&&lastInput!==binding){error(new Error('上次提交结果未确认，请先查询对象。'),g);return;}lastInput=binding;const button=f.querySelector('button')!;button.disabled=true;try{const result=await adminApi<Row>(op==='refund'?'payments/orders/'+encodeURIComponent(target)+'/refund':'payments/differences/'+encodeURIComponent(target)+'/annotate',input,key);if(g!==generation||!ready)return;key=crypto.randomUUID();lastInput='';const readGeneration=generation;await load();if(!ready||generation!==readGeneration+1)return;await detail(op==='refund'?'orders':'differences',target);if(ready)el('payments-status').textContent=op==='refund'?'退款请求已保存，等待供应商核验 · '+result.id:'处理记录已追加';}catch(e){if(e instanceof AdminApiError&&e.status>=400&&e.status<500){lastInput='';key=crypto.randomUUID();}error(e,g);}finally{button.disabled=false;}});}
