import {adminApi,AdminApiError,type AdminPage} from './admin-client';
type Row=Record<string,any>;
const el=(id:string)=>document.getElementById(id),node=(tag:string,text:string)=>{const n=document.createElement(tag);n.textContent=text;return n;};
const words:Record<string,string>={digest:'普通摘要',pro:'专业邮件',queued:'入队',sending:'发送中',accepted:'供应商接受',delivered:'确认送达',failed:'失败',unknown:'未知',cancelled:'取消',normal:'正常',abnormal:'异常',api:'外部运维检查',api_runtime:'API当前请求',mail:'邮件适配',release:'发布状态/核验记录',release_runtime:'当前API发布版本',backup:'备份',restore:'恢复验证',collection:'任务采集',data:'数据加载'};
const word=(s:any)=>words[s]??String(s??'未知'),time=(v:any)=>typeof v==='number'?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+' 北京时间':'未知';
let generation=0,cursor:string|null=null;
function clear(){generation++;for(const id of ['delivery-items','delivery-detail','health-items'])el(id)?.replaceChildren();el('delivery-status')!.textContent='';cursor=null;if(el('delivery-next'))el('delivery-next')!.hidden=true;}
function failure(e:unknown){el('delivery-status')!.textContent=e instanceof Error?e.message:'加载失败，请重试';if(e instanceof AdminApiError&&[401,403].includes(e.status)){clear();document.dispatchEvent(new CustomEvent('maas:admin-cleared'));el('admin-private')!.hidden=true;el('admin-status')!.textContent=e.status===401?'请登录':'无后台权限';}}
async function detail(id:string){const epoch=generation;try{const d=await adminApi<Row>('delivery/'+encodeURIComponent(id));if(epoch!==generation)return;const box=node('article','');box.className='admin-card';box.append(node('h2',word(d.type)+' · '+word(d.state)+(d.provider==='local'?'（本地模拟）':'')),node('p',`任务 ${d.id} · 用户 ${d.userId} · ${d.email}`),node('p',`入队 ${time(d.queuedAt)} · 租约 ${time(d.leaseUntil)}`),node('p',`供应商 ${d.provider??'未知'} · 消息 ${d.messageId??'未保存'} · 状态时间 ${time(d.eventAt)}`),node('p','报告 '+(d.reportId??'无')+' · 摘要关联 '+(d.digestItems?.map((r:Row)=>r.eventKey).join('、')??'无')),node('p',d.operation));const a=node('a','投递处置审计') as HTMLAnchorElement;a.href='/admin/audit/?targetType=mail_delivery&targetId='+encodeURIComponent(id);box.append(a);
 for(const r of d.attempts)box.append(node('p',`尝试 ${r.id} · ${time(r.startedAt)} → ${time(r.finishedAt)} · ${word(r.outcome)} · ${r.error??'无已知错误'}`));if(!d.attempts.length)box.append(node('p','没有历史尝试记录；不编造发送时间。'));for(const r of d.evidence)box.append(node('p',`已验证证据 ${r.id} · ${word(r.state)} · ${r.timeBasis==='query'?'查询观察':'事件'} ${time(r.eventAt)} · 收到 ${time(r.receivedAt)}`));
 for(const op of ['retry','reconcile']){const available=op==='retry'?d.retryAvailable:d.reconcileAvailable,form=document.createElement('form'),reason=document.createElement('input'),button=node('button',op==='retry'?'确认重试原任务':'核对已保存供应商证据') as HTMLButtonElement;reason.placeholder='处置原因（必填）';reason.required=true;reason.maxLength=1000;reason.setAttribute('aria-label','处置原因');button.disabled=!available;form.append(reason,button);const status=node('p','');status.setAttribute('role','status');box.append(form,status);let key:string|null=null,body:Row|null=null;form.addEventListener('submit',async e=>{e.preventDefault();if(!available)return;button.disabled=true;if(!body){body={reason:reason.value,expectedVersion:d.version};key=crypto.randomUUID();}try{await adminApi('delivery/'+encodeURIComponent(id)+'/'+op,body,key!);if(epoch===generation){await load();await detail(id);}}catch(err){if(epoch===generation){status.textContent=err instanceof Error?err.message:'处置失败';if(err instanceof AdminApiError){if(err.status<500){body=key=null;}if([401,403].includes(err.status))failure(err);}}}finally{button.disabled=!available;}});}
 el('delivery-detail')!.replaceChildren(box);}catch(e){if(epoch===generation)failure(e);}}
async function load(more=false){const epoch=++generation;el('delivery-status')!.textContent='正在加载…';try{if(el('health-items')){const d=await adminApi<Row>('health');if(epoch!==generation)return;el('health-items')!.replaceChildren(...d.items.map((r:Row)=>{const box=node('article','');box.className='admin-card';box.append(node('h2',word(r.kind)+' · '+word(r.status)+(r.stale?'（记录过期）':'')),node('p','来源 '+r.source+' · 检查 '+time(r.checkedAt)),node('p',r.value??(r.checkedAt===null?'尚未接入检查记录':'无附加说明')));if(r.lastStatus!==undefined)box.append(node('p','最近记录结果 '+word(r.lastStatus)));return box;}));el('delivery-status')!.textContent='检查于 '+time(d.asOf);return;}
 const p=new URLSearchParams();for(const [k,v]of new FormData(el('delivery-filter') as HTMLFormElement))if(String(v).trim())p.set(k,['from','to'].includes(k)?String(v)+':00+08:00':String(v).trim());if(more&&cursor)p.set('cursor',cursor);const d=await adminApi<AdminPage<Row>>('delivery?'+p);if(epoch!==generation)return;if(!more){el('delivery-items')!.replaceChildren();el('delivery-detail')!.replaceChildren();}for(const r of d.items){const box=node('article','');box.className='admin-card';const b=node('button','查看投递详情') as HTMLButtonElement;b.addEventListener('click',()=>void detail(r.id));box.append(node('h2',word(r.type)+' · '+word(r.state)+(r.provider==='local'?'（本地模拟）':'')),node('p',r.email+' · '+time(r.queuedAt)),node('p',r.id),b);el('delivery-items')!.append(box);}cursor=d.nextCursor;el('delivery-next')!.hidden=!cursor;el('delivery-status')!.textContent=d.items.length?'投递记录已加载':'没有符合条件的任务';}catch(e){if(epoch===generation)failure(e);}}
if(el('delivery-status')){document.addEventListener('maas:admin-ready',()=>void load());document.addEventListener('maas:admin-cleared',clear);el('delivery-filter')?.addEventListener('submit',e=>{e.preventDefault();void load();});el('delivery-next')?.addEventListener('click',()=>void load(true));window.addEventListener('pagehide',clear);}
