import {adminApi,AdminApiError} from './admin-client';
interface Rate {numerator:number;denominator:number;immature:number;rate:number|null;status:string;availability:string}
interface Coverage {availability:string;completeSince:string}
interface Result {
 range:{from:string;to:string;timezone:string;end:number};
 website:{availability:string;lastSuccessAt:string|null;reason?:string;stats:{pageviews:number;visitors:number;visits:number}|null;pages:{label:string;count:number}[]|null;sources:{label:string;count:number}[]|null;rankingUnit:string;asOf?:string};
 business:{asOf:string;coverage:Coverage;profilesCreated:number;registrations:Coverage&{count:number;historicalUnknown:number};betaActivated:number;professionalReads:{requests:number;accounts:number};exports:{requests:number;accounts:number};events:{event:string;count:number;accounts:number}[];weekly:{items:{id:string;kind:string;requests:number;readers:number;returningReaders:number}[];truncated:boolean};agents:Coverage&{failures:number;items:{channel:string;requests:number;httpSuccess:number}[]};activation7d:Rate;retentionWeek4:Rate};
}
const form=document.getElementById('analytics-filter') as HTMLFormElement|null;
if(form){
 const el=(id:string)=>document.getElementById('analytics-'+id)!;let generation=0,ready=false;
 const time=(s:string|number)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
 const clear=()=>{generation++;ready=false;for(const id of ['status','website-state','website','pages','sources','coverage','business','weekly','agents','cohorts'])el(id).replaceChildren();};
 const text=(id:string,value:string)=>{el(id).textContent=value;};
 const summary=(id:string,items:[string,string|number][])=>{const list=el(id);list.replaceChildren();for(const [key,value] of items){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=String(value);list.append(dt,dd);}};
 const table=(id:string,headers:string[],rows:(string|number)[][])=>{const host=el(id);host.replaceChildren();if(!rows.length){host.textContent='该范围内没有记录';return;}const wrap=document.createElement('div');wrap.className='admin-table-wrap';const t=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');for(const h of headers){const th=document.createElement('th');th.textContent=h;tr.append(th);}head.append(tr);t.append(head);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');td.textContent=String(value);tr.append(td);}body.append(tr);}t.append(body);wrap.append(t);host.append(wrap);};
 async function load(){if(!ready)return;const current=++generation;text('status','正在查询…');try{const data=new FormData(form!),preset=String(data.get('preset')),params=new URLSearchParams({preset});if(preset==='custom'){params.set('from',String(data.get('from')));params.set('to',String(data.get('to')));}const result=await adminApi<Result>('analytics?'+params);if(current!==generation)return;
   const {business:b,website:w,range:r}=result;text('status',`${r.from} 至 ${r.to} · 北京时间 · 数据截至 ${time(r.end)}`);
   text('website-state',w.availability==='available'?`查询成功于 ${time(w.asOf!)} · 排行单位：${w.rankingUnit==='views'?'浏览量':'访客'}`:`不可用（${w.reason==='not_configured'?'未配置服务端统计凭据':w.reason==='busy'?'查询繁忙':'统计查询失败或配置无效'}）· 最近成功：${w.lastSuccessAt?time(w.lastSuccessAt):'尚无成功记录'}`);
   if(w.stats){summary('website',[['浏览量',w.stats.pageviews],['访客（Umami去重口径）',w.stats.visitors],['访问次数（会话）',w.stats.visits]]);table('pages',['页面',w.rankingUnit==='views'?'浏览量':'访客'],w.pages!.map(x=>[x.label,x.count]));table('sources',['来源',w.rankingUnit==='views'?'浏览量':'访客'],w.sources!.map(x=>[x.label,x.count]));}else{for(const id of ['website','pages','sources'])el(id).replaceChildren();}
   text('coverage',`${b.coverage.availability==='partial'?'所选范围含历史缺失；下列数字仅为已记录结果。':'完整采集范围内的已记录结果。'} 完整采集开始：${time(b.coverage.completeSince)} · 查询于 ${time(b.asOf)}`);
   summary('business',[['资料建立（非注册）',b.profilesCreated],['已知时间的新注册',b.registrations.count],['历史注册时间未知的账号（当前存量）',b.registrations.historicalUnknown],['公测激活账号',b.betaActivated],['专业内容成功读取次数',b.professionalReads.requests],['专业内容去重读取账号',b.professionalReads.accounts],['专业导出次数',b.exports.requests],['专业导出去重账号',b.exports.accounts],['专业Agent工具成功次数',b.events.find(e=>e.event==='agent_tool_success')?.count??0]]);
   table('weekly',['期次 / 内容ID','入口','读取次数','去重读者','跨日回访读者'],b.weekly.items.map(x=>[x.id,x.kind==='briefing'?'正式专业周报':'历史日期周报',x.requests,x.readers,x.returningReaders]));if(b.weekly.truncated){const p=document.createElement('p');p.textContent='仅显示前100项，请缩短日期范围。';el('weekly').append(p);}
   table('agents',['渠道','完成请求','HTTP 2xx'],b.agents.items.map(x=>[({public_api:'公共API',public_mcp:'公共MCP',pro_api:'专业Bearer API',pro_mcp:'专业MCP'} as Record<string,string>)[x.channel]??x.channel,x.requests,x.httpSuccess]));if(b.agents.failures){const p=document.createElement('p');p.textContent=`采集写入失败累计 ${b.agents.failures} 次；请求汇总可能不完整。`;el('agents').append(p);}
   table('cohorts',['队列','分子','成熟分母','未成熟','比例 / 状态'],[['注册后7天公测激活',b.activation7d],['首次已记录专业读取后第4周回访',b.retentionWeek4]].map(([label,raw])=>{const rate=raw as Rate;return [String(label),rate.numerator,rate.denominator,rate.immature,rate.rate===null?(rate.status==='no_denominator'?'分母为0':'样本不足'):(rate.rate*100).toFixed(1)+'%'];}));
 }catch(e){if(current!==generation)return;for(const id of ['website-state','website','pages','sources','coverage','business','weekly','agents','cohorts'])el(id).replaceChildren();if(e instanceof AdminApiError&&(e.status===401||e.status===403)){clear();document.dispatchEvent(new CustomEvent('maas:admin-cleared'));document.getElementById('admin-private')!.hidden=true;}text('status',e instanceof Error?e.message:'查询失败，请重试。');}}
 form.addEventListener('submit',e=>{e.preventDefault();void load();});document.addEventListener('maas:admin-ready',()=>{ready=true;void load();});document.addEventListener('maas:admin-cleared',clear);window.addEventListener('pagehide',clear);
 const preset=form.elements.namedItem('preset') as HTMLSelectElement;const toggle=()=>{for(const name of ['from','to']){const input=form.elements.namedItem(name) as HTMLInputElement;input.disabled=preset.value!=='custom';input.required=preset.value==='custom';}};preset.addEventListener('change',toggle);toggle();
}
