import { adminApi, AdminApiError } from './admin-client';
const root=document.querySelector('[data-editorial-list], [data-editorial-detail]');
if(root){
 const el=(id:string)=>document.getElementById(id)!;
 let generation=0,detail:any=null,cursor:string|null=null,inputCursor:string|null=null,busy=false;
 const id=new URLSearchParams(location.search).get('id')??'';
 const status=(s:string)=>{el('weekly-status').textContent=s;};
 function clear(){generation++;detail=null;cursor=null;inputCursor=null;for(const key of ['weekly-list','weekly-summary','weekly-inputs','weekly-checks','weekly-preview','weekly-runs','weekly-reviews','weekly-publications','weekly-composition','weekly-mail','weekly-monitor'])el(key)?.replaceChildren();const editor=el('weekly-package') as HTMLTextAreaElement|null;if(editor)editor.value='';for(const field of root!.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea'))if(field instanceof HTMLInputElement&&field.type==='checkbox')field.checked=false;else field.value='';}
 function error(e:unknown){if(e instanceof AdminApiError&&(e.status===401||e.status===403)){clear();document.dispatchEvent(new CustomEvent('maas:admin-cleared'));}status(e instanceof Error?e.message:'操作失败，请重试');}
 function text(parent:HTMLElement,s:string){const p=document.createElement('p');p.textContent=s;parent.append(p);}
 function link(parent:HTMLElement,label:string,url:string){const a=document.createElement('a');a.textContent=label;a.href=url;parent.append(a);}
 async function list(){const g=++generation;try{const p=await adminApi<any>('weekly'+(cursor?'?cursor='+encodeURIComponent(cursor):''));if(g!==generation)return;el('weekly-list').replaceChildren();for(const i of p.items){const row=document.createElement('article');link(row,i.periodEnd,`/admin/weekly/detail/?id=${encodeURIComponent(i.id)}`);text(row,`${i.state} · r${i.currentRevision} · ${i.coverage} · ${i.latestRunState??'暂无任务'} · 费用 ${i.actualCost??'未知'} · ${i.createdBy}`);el('weekly-list').append(row);}cursor=p.nextCursor;el('weekly-next').hidden=!cursor;status(p.items.length?'已加载期次':'尚无期次，创建后冻结素材');}catch(e){if(g===generation)error(e);}}
 async function inputs(append=false){const g=generation;const p=await adminApi<any>(`weekly/${encodeURIComponent(id)}/inputs${append&&inputCursor?'?cursor='+inputCursor:''}`);if(g!==generation)return;if(!append)el('weekly-inputs').replaceChildren();for(const e of p.items){const row=document.createElement('details'),summary=document.createElement('summary');summary.textContent=`${e.id} · v${e.revision} · ${e.title}`;row.append(summary);text(row,`${e.observedAt} · ${e.url}\n${e.excerpt}\n${JSON.stringify(e.price)}`);el('weekly-inputs').append(row);}inputCursor=p.nextCursor;el('weekly-input-next').hidden=!inputCursor;}
 async function load(){const g=++generation;try{const d=await adminApi<any>('weekly/'+encodeURIComponent(id));if(g!==generation)return;detail=d;el('weekly-summary').replaceChildren();text(el('weekly-summary'),`${d.issue.periodEnd} · ${d.issue.state} · 版本 ${d.issue.version} · 稿件r${d.issue.currentRevision}\n${d.issue.windowFrom} — ${d.issue.windowTo}\n数据 ${d.issue.datasetVersion??'尚未冻结'} · 截至 ${d.issue.dataThrough??'未知'} · ${d.issue.coverage}: ${d.issue.coverageNote}\n选题 ${d.issue.selection}\n覆盖 缺失/未知来源 ${d.issue.coverageInfo.missingSources?.length??0}；快照截断 ${Boolean(d.issue.coverageInfo.truncated)}；零证据 ${Boolean(d.issue.coverageInfo.zeroEvidence)}\n模型 ${JSON.stringify(d.issue.config)}\n预算 USD ${d.issue.budget}；金额未知时不承诺绝不超支`);
  el('weekly-monitor').textContent=JSON.stringify({basisChanged:d.coverageBasisChanged,...d.monitorCoverage},null,2);(el('weekly-monitor-ack') as HTMLInputElement).checked=false;
  const coverage=document.createElement('details'),coverageTitle=document.createElement('summary');coverageTitle.textContent='查看缺失/未知来源与覆盖详情';coverage.append(coverageTitle);text(coverage,JSON.stringify(d.issue.coverageInfo,null,2));el('weekly-summary').append(coverage);
  (el('weekly-package') as HTMLTextAreaElement).value=d.revision?JSON.stringify(d.revision.payload,null,2):'{"contents":[]}';el('weekly-checks').textContent=JSON.stringify(d.revision?.checks??{manual:['先冻结证据并编辑稿件']},null,2);el('weekly-preview').replaceChildren();for(const c of d.revision?.payload.contents??[])text(el('weekly-preview'),`${c.title}\n${c.preview}`);
  el('weekly-runs').replaceChildren();for(const r of d.runs){const row=document.createElement('article');text(row,`${r.stage} · ${r.state} · attempt ${r.attempt} · 输入 ${r.inputCount}/${r.fullSnapshotCount} 条 · 估算 ${r.estimatedCost??'未知'} / 已知费用 ${r.actualCost??'未知'} / 预留 ${r.reserved}\n${r.errorCode??''}\n${JSON.stringify(r.result??{})}`);if(['queued','running','needs_review'].includes(r.state)){const b=document.createElement('button');b.textContent='取消任务';b.onclick=()=>void action(async()=>{await adminApi('runs/'+r.id+'/cancel',{reason:reason(),expectedVersion:r.version});await load();});row.append(b);}if(r.state==='needs_review'||r.state==='cancelled'&&String(r.errorCode).includes('unknown')){const form=document.createElement('form'),outcome=document.createElement('select'),note=document.createElement('input'),cost=document.createElement('input'),button=document.createElement('button');for(const [value,label] of [['not_executed','供应商确认未执行'],['executed','供应商确认已执行']]){const o=document.createElement('option');o.value=value;o.textContent=label;outcome.append(o);}note.placeholder='供应商核对材料（必填）';note.required=true;cost.type='number';cost.min='0';cost.step='0.000001';cost.placeholder='本任务累计实际费用USD，未知留空';button.textContent='记录核对结果，再允许手动重试';form.append(outcome,note,cost,button);form.onsubmit=e=>{e.preventDefault();void action(async()=>{const g=generation;await adminApi('runs/'+r.id+'/reconcile',{reason:reason(),expectedVersion:r.version,outcome:outcome.value,note:note.value,actualCost:cost.value===''?null:Number(cost.value)});if(g===generation)await load();});};row.append(form);}el('weekly-runs').append(row);}
  el('weekly-reviews').replaceChildren();for(const r of d.reviews)text(el('weekly-reviews'),`r${r.revision} · ${r.decision} · ${r.reviewerId} · ${r.note}`);
  el('weekly-publications').replaceChildren();for(const p of d.publications){text(el('weekly-publications'),`r${p.revision} · publication ${p.id} · ${p.compositionState}`);for(const c of p.contentRefs)link(el('weekly-publications'),`${c.kind} ${c.id} v${c.version} →`,c.kind==='briefing'?'/pro/weekly/?id='+encodeURIComponent(c.id):'/pro/?content='+encodeURIComponent(c.id));}
  el('weekly-composition').textContent=`已有报告 ${d.composition.existing} · 可新建 ${d.composition.possible} · ${d.composition.contains}`;el('weekly-mail').textContent=JSON.stringify(d.composition.mail);await inputs();if(g===generation)status('已读取当前版本；操作前填写原因');
 }catch(e){if(g===generation)error(e);}}
 function reason(){const v=(el('weekly-reason') as HTMLInputElement).value.trim();if(!v)throw new Error('请填写操作原因');return v;}
 async function action(fn:()=>Promise<void>){if(busy)return;busy=true;const g=generation;try{await fn();}catch(e){if(g===generation)error(e);}finally{busy=false;}}
 async function write(op:string,input:Record<string,unknown>){if(!detail)throw new Error('请先刷新当前版本');const g=generation;await adminApi('weekly/'+encodeURIComponent(id)+'/'+op,{...input,reason:reason(),expectedVersion:detail.issue.version});if(g===generation)await load();}
 document.addEventListener('maas:admin-cleared',clear);
 document.addEventListener('maas:admin-ready',()=>void (root.hasAttribute('data-editorial-list')?list():load()));
 el('weekly-next')?.addEventListener('click',()=>void list());el('weekly-refresh')?.addEventListener('click',()=>void load());el('weekly-input-next')?.addEventListener('click',()=>void inputs(true).catch(error));
 el('weekly-create')?.addEventListener('submit',e=>{e.preventDefault();void action(async()=>{const form=new FormData(e.target as HTMLFormElement),g=generation;const r=await adminApi<any>('weekly',{periodEnd:form.get('periodEnd'),selection:form.get('selection'),budget:Number(form.get('budget')),reason:form.get('reason')});if(g===generation)location.href='/admin/weekly/detail/?id='+encodeURIComponent(r.id);});});
 el('weekly-prepare')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target as HTMLFormElement);void action(()=>write('prepare',{coverage:f.get('coverage'),coverageNote:f.get('coverageNote'),monitorAcknowledgedHash:(el('weekly-monitor-ack') as HTMLInputElement).checked?detail?.monitorCoverage?.basisHash:undefined}));});
 el('weekly-save')?.addEventListener('submit',e=>{e.preventDefault();void action(()=>write('revisions',{package:JSON.parse((el('weekly-package') as HTMLTextAreaElement).value)}));});
 el('weekly-run-buttons')?.addEventListener('click',e=>{const stage=(e.target as HTMLElement).dataset.stage;if(stage)void action(()=>write('runs',{stage}));});
 el('weekly-review-form')?.addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target as HTMLFormElement),decision=((e as SubmitEvent).submitter as HTMLButtonElement).value;void action(()=>write('review',{decision,note:form.get('note'),revision:detail?.revision?.revision,outputHash:detail?.revision?.outputHash,checklist:Object.fromEntries(['sources','conditions','conclusions','coverage','preview','attribution'].map(k=>[k,form.get(k)==='on']))}));});
 el('weekly-publish')?.addEventListener('click',()=>void action(()=>write('publish',{revision:detail?.revision?.revision,outputHash:detail?.revision?.outputHash})));
 el('weekly-compose')?.addEventListener('click',()=>void action(()=>write('compose',{queueMail:(el('weekly-queue') as HTMLInputElement).checked})));
 window.addEventListener('pagehide',clear);
}
