export const paymentLabels:Record<string,string>={active:'生效中',incomplete:'等待首次付款',pending:'等待处理',processing:'支付处理中',succeeded:'支付成功',failed:'失败',expired:'已到期',terminated:'已立即终止',disputed:'争议暂停',revoked:'付费权益已撤销',full:'全额退款',partial:'部分退款',none:'未退款',paid:'付款成功',cancel:'周期结束取消',terminate:'立即终止',refund:'退款成功',dispute:'争议',dispute_won:'争议胜诉',dispute_lost:'争议败诉',processed:'已处理',missing_internal:'内部漏记',missing_provider:'供应商未匹配',amount_mismatch:'金额不符',fee:'手续费',settlement:'实际结算',simulator:'本机模拟器'};
export const paymentText=(v:unknown)=>v===null||v===undefined?'未知':typeof v==='boolean'?(v?'是':'否'):paymentLabels[String(v)]??String(v);
export const paymentTime=(v:unknown)=>typeof v==='number'?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+'（北京时间）':'未知';
export const paymentAmount=(v:unknown,currency:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)?`${currency??''} ${v} 最小单位`:'未知';
export function paymentTable(rows:Record<string,unknown>[],columns:[string,string,((r:Record<string,unknown>)=>string)?][],action?:{label:string;click:(r:Record<string,unknown>)=>void}){
 const table=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');for(const [,label]of columns){const th=document.createElement('th');th.textContent=label;tr.append(th);}if(action){const th=document.createElement('th');th.textContent='查看';tr.append(th);}head.append(tr);table.append(head);const body=document.createElement('tbody');
 for(const row of rows){const tr=document.createElement('tr');for(const [key,,format] of columns){const td=document.createElement('td');td.textContent=format?format(row):paymentText(row[key]);tr.append(td);}if(action){const td=document.createElement('td'),button=document.createElement('button');button.type='button';button.textContent=action.label;button.addEventListener('click',()=>action.click(row));td.append(button);tr.append(td);}body.append(tr);}table.append(body);return table;
}

export function userPaymentAmount(value:unknown,currency:unknown){if(currency==='USD'&&typeof value==='number'&&Number.isSafeInteger(value)&&value>=0){const n=BigInt(value);return 'US$'+String(n/100n)+'.'+String(n%100n).padStart(2,'0');}return paymentAmount(value,currency);}
