import { HOME_MODEL_GROUPS } from '../config/home-model-selection';
// One translation catalog for server-rendered pages and client-rendered controls.
// Product data, API identifiers, and saved source excerpts are not rewritten.
export const uiEnglish: Record<string, string> = {
 '条要点':'highlights','搜索厂家与产品变化':'Search provider and product changes','项今日变化依据':'today’s source changes','动态时间范围':'Update time range','今天':'Today','展开更多变化':'Show more changes','按厂家与平台汇总。':'Grouped by provider and platform.',
 '今日模型与平台变化':'Today’s model and platform changes',
 '查看各家近期变化':'Recent changes by provider',
 '各家产品，最近发生了什么':'What changed across providers and products',
 '查模型与报价':'Explore models and prices',
 '近 7 天':'Past 7 days',
 '按厂家与平台汇总，重复摘要合并，保留最近记录。':'Grouped by provider and platform. Duplicate summaries are merged, retaining the latest record.',
 '条变化 · 最近':'changes · latest',
 '展开其余':'Show remaining',
 '条变化':'changes',
 '的变化记录':'change records',
 '查看日期记录可追溯当天摘要与官方来源。':'Follow dated records for daily summaries and official sources.',
 '近 7 天暂无已整理的厂家与产品变化。':'No summarized provider or product changes in the past 7 days.',

 'MaaS Daily — 大模型 API 价格与全球 MaaS 每日动态':'MaaS Daily — Model API prices and daily platform updates',
 '大模型 API 价格比较与 GPU 租赁行情 — MaaS Daily':'Model API prices and GPU rental costs — MaaS Daily',
 '大模型 API 价格查询与价格变化 — MaaS Daily':'Model API prices and pricing changes — MaaS Daily',
 '数据方法说明 — MaaS Daily':'Data method — MaaS Daily','Agent 接入 — MaaS Daily':'Agent connections — MaaS Daily',
 '变化浏览 — MaaS Daily':'Platform changes — MaaS Daily','模型成本与 GPU 行情':'Model costs and GPU markets',
 '全球 MaaS 平台每日追踪 — 模型发布、定价变更、API 更新':'Daily MaaS tracking — model releases, pricing changes and API updates',
 '每日追踪大模型发布、API 价格变化与平台更新。查询模型报价、计费条件和官方证据，查看全球 MaaS 平台周报。':'Track model releases, API price changes and platform updates. Inspect prices, billing conditions, official evidence and weekly reports.',
 '查询大模型 API 价格与成本估算，查看模型原币种报价、计费条件和价格变化，追踪 GPU 租赁行情与国产 AI 芯片动态。':'Compare model API prices and estimated costs, inspect original quotes and billing conditions, and track GPU rentals and AI chip updates.',
 '模型与平台，今日观察。':'Models and platforms, observed today.', 'MAAS DAILY / 今日重点':'MAAS DAILY / TODAY’S HIGHLIGHTS',
 '今日重点':'Today’s highlights','今日模型重点与价格':'Today’s models and prices','今日平台动态':'Today’s platform updates',
 '官方来源追踪 · AI 摘要':'Official sources · AI summaries','最近更新':'Last updated','等待更新':'Awaiting update',
 '查看记录与依据':'View records and evidence','比较模型价格':'Compare model prices','全部动态':'All updates',
 '当前价格一览':'Current prices','各家旗舰与主力模型，怎么选、怎么收费':'Flagship and everyday models: positioning and prices',
 '按官方定位分组，查看输入与输出成本。金额来自采集快照，换算为估算值。数据截至':'Grouped by official positioning. Compare input and output costs from observed quotes. Converted prices are estimates. Data through',
 '全部模型':'All models','模型与定位':'Model and positioning','价格显示币种':'Display currency','模型比较分组':'Model comparison groups',
 '¥ 人民币':'¥ CNY','$ 美元':'$ USD','人民币 · 估算':'CNY · estimate','美元兑人民币估算汇率':'Estimated USD to CNY rate',
 '手动汇率':'Reference exchange rate','非实时':'not live','系统参考汇率 · 非实时':'Reference rate · not live','自定义汇率 · 非实时':'Custom rate · not live',
 '官方定位':'Official positioning','查看条件':'View conditions','完整报价与证据':'Quotes and evidence','查看报价条件':'View billing conditions',
 '来源未单列':'Not separately specified by source','来源未注明':'Not stated by source','百万 token':'million tokens','每百万 tokens':'per million tokens',
 '每百万 token':'per million tokens','输入':'Input','输出':'Output','缓存读取':'Cache read','缓存写入':'Cache write',
 '缓存写入（5 分钟）':'Cache write (5 minutes)','缓存写入（1 小时）':'Cache write (1 hour)',
 '来源原值':'Source value','地区':'Region','平台':'Platform','批处理':'Batch','实时':'Real-time',
 '继续了解':'Explore more','更多平台动态':'More platform updates','复制简报':'Copy brief','动态筛选':'Filter updates',
 '搜索平台、模型或关键词…':'Search platforms, models or keywords…','搜索今日要点与信号':'Search today’s highlights and signals',
 '筛选平台':'Filter platform','全部平台':'All platforms','只看关注':'Following only','要点类型':'Update type',
 '新发布':'Releases','价格变化':'Price changes','下线提醒':'Retirements','本周回顾':'This week',
 '没有找到匹配的动态':'No matching updates','试试其他关键词，或关注下方平台后再使用「只看关注」。':'Try another search, or follow a platform and enable Following only.',
 '重置筛选':'Reset filters','按平台展开，查看完整摘要与变化依据。':'Browse each platform’s summaries and supporting observations.',
 '＋ 关注':'+ Follow','✓ 已关注':'✓ Following','取消关注':'Unfollow','关注':'Follow','已关注':'Following',
 '模型发布':'Model release','定价调整':'Pricing update','功能更新':'Feature update','来源观察':'Source observation','价格事件':'Pricing observation',
 '信号':'Signals','要点':'Highlights','动态':'Updates','观察记录':'Observation records','更新日志':'Release notes',
 '全部变化':'All changes','查看全部变化':'View all changes','查看来源':'View source','官方来源':'Official source','官方定价来源':'Official pricing sources',
 '数据截至':'Data through','数据范围':'Data range','覆盖范围':'Coverage','条变化记录':'change records','条价格事实':'pricing facts','条证据':'evidence records',
 '未关联模型':'Model not resolved','来源未分类':'Source not classified','暂无匹配记录':'No matching records','暂无变化记录':'No changes recorded',
 '价格 / 原始单位':'Price / original unit','平台 / API 模型':'Platform / API model','计费项':'Billing component','条件与依据':'Conditions and evidence',
 'API 模型名':'API model names','当前可观察的 API 价格':'Observed API prices','刷新数据':'Refresh data','变化记录':'Change record','价格证据':'Pricing evidence','暂无链接':'No link available',
 '当前数据中暂无可观察的 API 模型名。':'No API model names have been observed in the current dataset.',
 '以下名称来自实际价格记录。调用时请核对对应平台的 API 文档。':'Names come from pricing records. Check the platform API documentation before calling a model.',
 '当前公开数据范围内暂无价格记录。不能据此判断该模型免费或平台未提供服务。':'No prices were observed in the current public dataset. This does not establish that the model is free or unavailable.',
 '保留原币种和原始计费单位，不合并不同地区、档位、上下文或时间条件。条件字段为来源原值；“来源未单列”不代表没有限制。':'Original currencies and billing units are retained. Regions, tiers, context and time conditions remain separate. Unspecified conditions do not imply unrestricted use.',
 '来源未说明':'Not specified by source','计费方式 / 服务档位':'Billing mode / service tier','上下文条件':'Context condition','时间条件':'Time condition','官方生效时间':'Official effective time','观察时间':'Observed at','数据与证据状态':'Data and evidence status',
 '最近抓取成功':'Latest fetch succeeded','更新失败，沿用旧数据':'Update failed; previous data retained','更新状态未知':'Update status unknown','证据完整':'Complete evidence','证据不完整':'Partial evidence','证据不可用':'Evidence unavailable','最近成功：':'Last successful fetch: ',
 'COST & COMPUTE / 价格观察':'COST & COMPUTE / PRICE OBSERVATIONS','大模型 API 价格，':'Model API prices,','与算力成本全景。':'and the broader cost of compute.',
 '从一次 API 调用，到一张 GPU，再到国产芯片供给。三种价格尺度放在同一页，帮助你看清成本从哪里来。':'From an API call to a GPU rental and chip supply: three cost perspectives on one page.',
 '数据概况':'Dataset overview','个报价来源':'quote sources','个模型':'models','台账更新于':'Ledger updated','价格页面分区':'Pricing sections',
 'API 调用':'API calls','GPU 租赁':'GPU rentals','时租与包月':'Hourly and monthly','国产芯片':'AI chips','出货与进展':'Shipments and developments',
 'API 单价与用量成本，':'API prices and usage costs,','同一把尺子':'the same scale','放在':'on ','上。':'.',
 '从报价台账进入模型，再用实际输入与输出量估算成本。':'Explore observed quotes, then estimate costs using your input and output volumes.',
 '同一份用量，不同的成本':'Same usage, different costs','输入 100 万 + 输出 25 万 tokens · 已选模型预览':'1M input + 250K output tokens · Selected model preview',
 '调整人民币估算汇率':'Adjust the estimated CNY exchange rate','数据加载中':'Loading data','从一个模型，看到更多可能':'Start with a model, explore your options',
 '按报价来源浏览，选择模型加入下方对比。价格单位：元 / 百万 tokens。':'Browse quote sources and add models to compare. Units: CNY per million tokens.',
 '查看对比':'View comparison','报价来源':'Quote sources','模型名搜索（支持 API 名）':'Search model or API name','输入模型名…':'Search model…','排序':'Sort',
 '名称':'Name','输入价格':'Input price','输出价格':'Output price','模型':'Model','模型系列':'Model family','全部系列':'All families',
 '把差别，放在同一把尺子上':'Compare differences on the same scale','选择 2–5 个模型；调整用量，直观看到输入与输出的成本组成。':'Choose 2–5 models and adjust usage to compare input and output costs.',
 '清空对比':'Clear comparison','你的用量，算一算':'Estimate your usage cost','输入用量 / 百万 tokens':'Input usage / million tokens','输出用量 / 百万 tokens':'Output usage / million tokens',
 '轻量试用':'Light trial','日常应用':'Daily usage','高频调用':'High volume','用量成本':'Usage cost','图表价格组件':'Chart billing component',
 '元 / 当前用量':'CNY / selected usage','元 / 百万 tokens':'CNY / million tokens','输入成本':'Input cost','输出成本':'Output cost','线性比例':'Linear scale',
 '估算 = 输入单价 × 输入用量 + 输出单价 × 输出用量。未计缓存优惠、税费及其他附加项。价格不代表模型能力。':'Estimate = input price × input volume + output price × output volume. Cache discounts, taxes and other fees are excluded. Price does not indicate model capability.',
 '没有匹配模型':'No matching models','没有匹配的模型':'No matching models','全部厂商 · 搜索结果':'All providers · Search results','模型详情':'Model details','查看事实':'View pricing facts','加入对比':'Add to comparison','移出对比':'Remove from comparison','已加入':'Added',
 '选择模型':'Select a model','来源与条件':'Sources and conditions','自定义汇率':'Custom exchange rate','人民币估算汇率':'Estimated CNY exchange rate',
 '请输入 0.01–1000 之间的汇率':'Enter a rate between 0.01 and 1000','百万':'million','暂无':'Not available','不限':'Not specified',
 '大模型 API 价格查询':'Model API price directory','同一模型，比较不同调用平台的报价':'Compare quotes across platforms for the same model',
 '这是当前公开数据中有报价的模型目录，不能代表所有模型或全部平台覆盖。':'This directory covers models with observed prices in the current dataset, not every model or platform.',
 '有可观察报价的模型':'Models with observed quotes','API 价格':'API prices','API 价格与价格变化':'API prices and pricing changes','数据方法与覆盖说明':'Data method and coverage',
 '我们如何观察 MaaS 平台':'How we observe MaaS platforms','1. 观察，不是转述':'1. Observations and official announcements','2. 五种时间，各是各的':'2. Five distinct timestamps','3. 证据的完整性分层':'3. Evidence completeness','4. LLM 摘要可能出错':'4. Generated summaries can be wrong',
 '5. 条件先于价格':'5. Conditions before price','来源页变化不等于供应商正式发布、下线或调价':'A page change is not an official release, retirement or price announcement',
 '页面文本的观察':'observations of page text','首次观察时间':'First observed','来源发布时间':'Source publication time','价格事实观察范围':'Price observation interval','站点构建时间':'Site build time',
 '稳定 ID → 结构化事实 → 证据摘录 → 官方页面':'Stable ID → structured facts → saved excerpt → official source',
 '把 MaaS 动态，':'MaaS updates,','接进你的 Agent。':'connected to your Agent.','平台有什么变化、模型价格是多少、这周值得关注什么。':'What changed, what models cost, and what matters this week.',
 '让 Agent 带着来源回答你。':'Let your Agent answer with sources.','匿名只读':'Anonymous read-only','无需 API Key':'No API key required','选择接入方式':'Choose a connection',
 '让 Agent 帮你安装':'Let your Agent install it','连接你的 AI 客户端':'Connect your AI client','在阅读器里订阅':'Subscribe in your reader','接入代码与工作流':'Connect code and workflows','已上线':'Available','待部署':'Pending','不可用':'Unavailable',
 '复制提示词':'Copy prompt','安装 Skill':'Install Skill','更新 Skill':'Update Skill','复制配置':'Copy configuration','复制':'Copy','已复制':'Copied','验证接入':'Verify connection',
 '追踪平台变化':'Track platform updates','核对模型价格':'Verify model prices','读最新周报':'Read the latest weekly report','安装位置':'Install location','下载':'Download','安装说明':'Install instructions',
 '平台变化流':'Platform change stream','来源观察与价格事件，按模型或系列筛选。数据截至':'Source observations and pricing events, filtered by model or family. Data through',
 '全部类型':'All types','查询':'Search','加载更多':'Load more','正在加载…':'Loading…','没有更多记录':'No more records',
 '信源目录':'Source directory','数据来源':'Data sources','平台榜单':'Platform rankings','模型榜单':'Model rankings','周报归档':'Weekly archive','正式周报':'Published weekly report','本周':'This week','历史周报':'Past weekly reports',
 '最新一期':'Latest issue','查看周报':'Read report','阅读周报':'Read report','观察周报':'Observation reports','期正式周报':'published reports',
 '关于 MaaS Daily':'About MaaS Daily','接口变更记录':'Interface changelog','接口变更':'Interface changes','数据状态':'Data status','修订历史':'Revision history','原始证据':'Original evidence','保存的摘录':'Saved excerpt','原文摘录':'Source excerpt',
 '已撤回':'Withdrawn','历史版本':'Historical version','记录详情':'Record detail','来源链接':'Source link','观察日期':'Observation date','生成摘要':'Generated summary','原始记录':'Original record','返回':'Back',
 '阿里百炼':'Alibaba Cloud Bailian','阿里云':'Alibaba Cloud','火山引擎':'Volcengine','智谱':'Zhipu','百度':'Baidu','腾讯':'Tencent','讯飞':'iFlytek',
};

Object.assign(uiEnglish, {
  "每日定时抓取各平台官方页面（模型列表/定价/更新日志/博客），与上一次快照逐行对比。这是": "We periodically fetch official model lists, pricing pages, release notes and blogs, then compare them with the previous snapshot. These are ",
  "：受截断、页面抖动与重算影响，存在噪声边界。": ": truncation, page movement and recomputation can introduce noise.",
  "——那需要官方公告佐证。": "; that requires an official announcement.",
  "（observedAt）：我们的抓取程序看到该内容的时间；": " (observedAt): when our collector saw the content;",
  "（publishedAt）：供应商官方声明的时间（无来源则为空，不用观察时间顶替）；": " (publishedAt): the supplier’s stated publication time; empty without a source, never substituted with the observation time;",
  "：该价格成立的观察区间（版本链）；": ": the observation interval and version history of the price;",
  "（dataThrough）：本数据集的覆盖上限——当前为": " (dataThrough): the dataset coverage boundary, currently ",
  "：网页发布时刻，与数据时间无关。": ": when the site was published, distinct from source data time.",
  "首页与价格页显示各自的数据时间，不用构建时间冒充。": "The home and pricing pages show their own data timestamps, rather than the site build time.",
  "每条价格事实附证据（当时保存的页面摘录 + 定位方式 + 摘录哈希）。完整性分三档：": "Each pricing fact includes a saved excerpt, locator and excerpt hash. Evidence has three completeness states: ",
  "（模型/金额/单位可在摘录内复核）、": " (the model, amount and unit can be checked in the excerpt), ",
  "（形态完整但某要素不在摘录内——如实披露，不因存在就算已验证）、": " (the evidence structure exists but an element cannot be checked in the excerpt; existence alone is not verification), ",
  "（历史数据无证据可回溯）。摘要、定位、官方来源各自能证明的内容不同——逐层看，不跳层。": " (historical evidence cannot be recovered). Summaries, locators and official sources support different levels of verification.",
  "部分变化摘录由 LLM 生成（标记 summaryOrigin=llm），可能出错。核验路径：": "Some observation summaries are generated by an LLM (summaryOrigin=llm) and may be wrong. Verify through: ",
  "，逐层可查。RSS 与 API 中的 LLM 摘要均带披露标记。": ". Generated RSS and API summaries disclose their origin.",
  "5. 价格的条件完整性": "5. Complete billing conditions",
  "每条价格保留原币种（USD/CNY）、单位（如 /1M token）、计费组件（输入/输出/缓存读/缓存写）、区域、档位、计费模式与附加条件（长上下文阶梯、峰谷时段）。": "Each price retains its currency (USD/CNY), unit, input/output/cache component, region, tier, billing mode and additional conditions such as context bands and peak/off-peak periods.",
  "不做跨单位、跨条件的自动「最低价」结论": "We do not infer a lowest price across incompatible units or conditions",
  "——多候选逐项列出，由你按适用条件判断。": ". Candidates remain separate so you can assess their applicable conditions.",
  "6. 衍生数据的边界": "6. Supplemental datasets",
  "榜单（如 OpenRouter 调用量）来自第三方，汇率与部分能力榜为人工维护——各自标注更新时间；未知值显示未知，不补数字。": "Usage rankings come from third parties; exchange rates and some capability rankings are manually maintained. Each shows its own update time. Unknown values remain unknown.",
  "7. 三种健康信号": "7. Three distinct health signals",
  "抓取成功": "Fetch succeeded",
  "：页面下载与解析完成；": ": the page was downloaded and parsed;",
  "价格解析通过": "Pricing validation passed",
  "：门禁校验（金额/证据链/身份）通过；": ": amounts, evidence chains and identities passed validation;",
  "最后有效事实时间": "Last accepted fact",
  "：该来源最近一次产出被接受的事实。": ": the most recent accepted fact from this source.",
  "三者不同。失败沿用旧数据时状态标": "These signals are distinct. When an update fails and previous data is retained, the state is ",
  "（附最后成功时间），不显示为新数据；partial/unknown/unavailable 各按字面理解。": " (with the last successful time), rather than fresh data. partial, unknown and unavailable retain their literal meanings.",
  "8. 修订、撤回与缓存": "8. Revisions, withdrawals and caches",
  "记录可修订（修订链保留历史）与撤回（详情页仍可访问并标注）。RSS 是静态投影：修订保持条目身份，但已缓存的撤回内容无法可靠召回——": "Records support revisions and withdrawals while retaining history and reachable detail pages. RSS is a static projection; revisions preserve identity, but cached withdrawn entries cannot reliably be recalled. ",
  "详情页与 API 是最新状态的权威来源": "Detail pages and API responses are authoritative for current record status",
  "。接口变更见": ". For interface changes, see ",
  "变更记录": "the changelog",
  "语言选择与国家识别": "Language preference and country lookup",
  "仅首页入口按国家选择默认语言：中国大陆（CN）中文，其他地区英文。手动选择保存在浏览器本地 180 天，优先于自动判断；具体语言页面的地址不随国家改变。定位失败按浏览器首选语言回退，无 JavaScript 时首页保留中文。VPN 或数据库误差可通过语言链接纠正。": "Only the homepage entry selects a default language by country: Chinese for mainland China (CN), English elsewhere. Your manual choice takes priority and is stored locally for 180 days. Deep links retain their language. Failed lookups fall back to your browser preference; without JavaScript the homepage stays Chinese. Use the language links to correct VPN or database inaccuracies.",
  "国家识别在本站服务器使用本地数据库，不把访客地址交给新的第三方定位服务，不新增原始 IP 埋点。数据库超过 21 天未更新时停止查询并回退。This product includes GeoLite2 data created by": "Country lookup uses a local server database without adding a third-party address lookup or raw IP tracking. A database more than 21 days old is disabled and the fallback is used. This product includes GeoLite2 data created by ",
  "；由": "; distributed by ",
  "提供，数据库受": ". The database is governed by ",
  "约束。": ".",
  "反馈": "Feedback",
  "联系我：": "Contact me: ",
  "从这里开始": "Start here",
  "复制给 Agent，剩下的交给它": "Copy this to your Agent and let it connect",
  "适合支持 Skills 的 Agent。安装一次，以后直接用中文问。": "For Agents that support Skills. Install once, then ask in your preferred language.",
  "复制下方提示词": "Copy the prompt below",
  "发给你正在使用的 Agent": "Send it to your Agent",
  "按提示开新会话": "Start a new session if prompted",
  "让客户端发现新安装的 Skill": "Let your client discover the installed Skill",
  "问一句，确认接通": "Ask a question to verify the connection",
  "看到日期、摘要和来源链接": "Look for dates, summaries and source links",
  "安装提示词": "Installation prompt",
  "完整复制，直接发送": "Copy the complete prompt and send it",
  "复制安装提示词": "Copy installation prompt",
  "复制后粘贴到 Agent 对话框发送；本页不会自动安装。": "Paste the prompt into your Agent chat. This page does not perform installation.",
  "装好后，试着这样问": "After installation, try these questions",
  "查看提问": "View question",
  "复制问题": "Copy question",
  "已有 Skill？更新到最新版": "Already installed? Update the existing Skill",
  "复制更新提示词": "Copy update prompt",
  "手动安装与排查": "Manual installation and troubleshooting",
  "在当前客户端支持的 skills 目录下安装。以下是 Claude Code 的目录示例；其他客户端请替换路径，保留末尾的 maas-daily。": "Install in your client’s supported Skills directory. The example uses Claude Code; replace the directory for other clients and retain the final maas-daily folder.",
  "复制安装命令": "Copy installation command",
  "更新时使用同一 --dir 重跑命令。安装器会校验完整包；发现未知文件时拒绝覆盖。": "To update, rerun with the same --dir. The installer validates the package and refuses to overwrite unknown files.",
  "确认最终目录顶层存在 SKILL.md。": "Check that SKILL.md exists at the top level of the final directory.",
  "开启新会话，再让 Agent 列出发现的 Skills。": "Start a new session and ask your Agent to list discovered Skills.",
  "查询失败时检查网络与服务状态，不用模型记忆补答。": "If a query fails, check the network and service status; do not substitute model memory.",
  "阅读完整安装说明": "Read installation instructions",
  "远程工具连接": "Remote tool connection",
  "把 MaaS Daily 加入你的工具列表": "Add MaaS Daily to your tools",
  "适合支持远程 Streamable HTTP MCP 的客户端。无需填写 token。": "For clients supporting remote Streamable HTTP MCP. No token is required.",
  "服务器地址": "Server address",
  "复制MCP 地址": "Copy MCP address",
  "在客户端的 MCP 设置中添加远程服务器，保存后刷新工具列表或开启新会话。": "Add a remote server in your client’s MCP settings, save, then refresh tools or start a new session.",
  "使用 JSON 配置": "JSON configuration",
  "复制MCP 配置": "Copy MCP configuration",
  "Codex 的 TOML 配置": "Codex TOML configuration",
  "复制TOML 配置": "Copy TOML configuration",
  "连接后，发一句验证": "After connecting, verify with a question",
  "复制验证问题": "Copy verification question",
  "平台变化": "Platform changes",
  "模型价格": "Model prices",
  "条目详情": "Record details",
  "证据核验": "Evidence verification",
  "调用默认 10 条、最多 30 条；更多结果使用 cursor 翻页。遇到 429 按 Retry-After 等待，503 时稍后重试。": "Calls return 10 records by default, up to 30. Use cursor pagination for more. On 429 follow Retry-After; on 503 retry later.",
  "订阅阅读": "Subscribe and read",
  "更新来了，在阅读器里看": "Read updates in your feed reader",
  "复制订阅地址，粘贴到阅读器的「添加订阅」中。": "Copy a feed URL into your reader’s Add subscription field.",
  "最近的平台变化与价格事件，最多 100 条。": "Up to 100 recent platform observations and pricing events.",
  "复制变化订阅地址": "Copy changes feed URL",
  "按期阅读整理后的周报，最多 30 期。": "Read published weekly reports, up to 30 issues.",
  "复制周报订阅地址": "Copy weekly feed URL",
  "RSS 2.0，支持 ETag / 304。自动化轮询请间隔至少 30 分钟。详情页保留最新修订与撤回状态，阅读器内的旧条目可能不会同步撤回；订阅不包含第三方全文或再分发许可。": "RSS 2.0 supports ETag / 304. Poll at least 30 minutes apart. Detail pages retain current revisions and withdrawals; cached reader entries may not reflect withdrawals. Subscription does not include third-party full text or redistribution rights.",
  "开发者接入": "Developer access",
  "接入你的脚本与工作流": "Connect your scripts and workflows",
  "匿名 GET 请求，从一次真实查询开始。": "Anonymous GET requests. Start with a real query.",
  "复制查询命令": "Copy query command",
  "复制状态查询": "Copy status query",
  "数据版本与覆盖范围": "Dataset version and coverage",
  "证据详情": "Evidence details",
  "列表默认 20 条、最多 100 条；翻页原样传回 cursor，过期后从第一页重查。支持 ETag / 304，错误返回 Problem JSON；429 按 Retry-After 等待。": "Lists return 20 records by default, up to 100. Return cursors unchanged; restart from the first page when they expire. Supports ETag / 304 and Problem JSON errors. Follow Retry-After on 429.",
  "查看 OpenAPI 完整定义": "View the OpenAPI specification",
  "你能获得什么": "What you can access",
  "回答有来源，": "Answers with sources,",
  "判断有依据。": "decisions with evidence.",
  "模型发布、API 更新与价格事件": "Model releases, API updates and pricing observations",
  "价格事实": "Pricing facts",
  "币种、计费单位、适用条件与证据": "Currencies, units, conditions and evidence",
  "按期查阅，回到原始记录": "Browse published issues and return to original records",
  "怎样算接入成功？": "How do you verify a connection?",
  "完成一次真实查询，回答带有数据截至日期、覆盖范围和站内链接；响应包含 datasetVersion。下载或保存配置只是第一步。": "Complete a real query with the data-through date, coverage and site links. Responses include datasetVersion. Downloading or saving configuration is only the first step.",
  "接入资源": "Connection resources",
  "给 Agent 的站点说明": "Site instructions for Agents",
  "Skill 安装文档": "Skill installation guide",
  "Skill 文件清单": "Skill package manifest",
  "OpenAPI 定义": "OpenAPI specification",
  "更新记录": "Update history",
  "关于这些数据": "About the data",
  "观察快照，每次回答都带上时间": "Observation snapshots: include dates in every answer",
  "了解数据方法与边界": "Read the data method and limitations",
  "查询模型 API 价格与变化": "Find model API prices and changes",
  "查看原币种报价、计费条件、观察时间和官方来源。": "Inspect original currencies, billing conditions, observation timestamps and official sources.",
  "浏览全部模型价格": "Browse all model prices",
  "模型 API 价格台账": "Model API pricing ledger",
  "统一折算为人民币与每百万 tokens；可按厂商浏览、搜索模型，并把 2–5 个模型放入用量计算器比较。": "Prices are estimated in CNY per million tokens. Browse providers, search models and compare 2–5 models with the usage calculator.",
  "¥ 人民币 · 汇率": "¥ CNY · FX",
  "按名称": "By name",
  "模型 / 计费条件": "Model / billing conditions",
  "输入单价": "Input price",
  "输出单价": "Output price",
  "对比": "Compare",
  "没有找到匹配的模型。试试其他名称或厂商。": "No matching models. Try another name or provider.",
  "人民币换算": "CNY conversion",
  "手动估算 · 非实时汇率": "Manual estimate · not a live exchange rate",
  "原始报价与来源保留在模型详情中": "Original quotes and sources are retained on model detail pages",
  "MaaS Daily / 每日自动抓取八家官方定价页。": "MaaS Daily / Daily collection from eight official pricing sources.",
  "按计费条件查看原始报价。来源地址仅展示，便于核对。": "Inspect original quotes by billing conditions. Source URLs are shown for verification.",
  "GPU 算力租赁行情": "GPU rental market",
  "低": "Low",
  "包月成本区间": "Monthly cost range",
  "高": "High",
  "推理 / 绘图 / 微调入门": "Entry-level inference, graphics and fine-tuning",
  "时租": "Hourly",
  "包月": "Monthly",
  "中等规模训练 / 微调": "Mid-scale training and fine-tuning",
  "高端训练": "High-end training",
  "国产替代训练/推理": "Domestic training and inference alternative",
  "口径": "Basis",
  "包月参考按 24/7 折算，价格随供需和机房配置波动，实际以平台实时报价为准。": "Monthly estimates assume 24/7 operation. Prices vary with supply, demand and facility configuration; verify current platform quotes.",
  "国产 AI 芯片进展": "AI chip developments",
  "华为昇腾": "Huawei Ascend",
  "寒武纪": "Cambricon",
  "燧原科技": "Enflame",
  "说明": "Notes",
  "近半数": "Nearly half",
  "国产算力出货份额": "Share of domestic compute shipments",
  "芯片销量": "Chip sales",
  "全年出货": "Full-year shipments",
  "营收": "Revenue",
  "IPO 进程": "IPO progress",
  "上市": "Listed",
  "量产": "Mass production",
  "新一代旗舰云端 AI 芯片，双 die 封装": "Next-generation flagship cloud AI chip with dual-die packaging",
  "国产 AI 芯片「四小龙」陆续登陆资本市场": "Four leading domestic AI chip companies enter capital markets",
  "推理": "Inference",
  "训练": "Training",
  "（旧名）": " (former name)"
});

for (const group of HOME_MODEL_GROUPS) {
  uiEnglish[group.title] = group.titleEn; uiEnglish[group.description] = group.descriptionEn;
  for (const model of group.models) uiEnglish[model.reason] = model.reasonEn;
}

Object.assign(uiEnglish, {
  "暂停": "Pause",
  "非实时": "not live",
  "报价条件": "Billing conditions",
  "原价": "Original price",
  "全球": "Global",
  "实时": "Real time",
  "标准档": "Standard tier",
  "中国内地": "Mainland China",
  "上下文": "Context",
  "观察于": "Observed on",
  "报价与证据 ↗": "Price and evidence ↗",
  "未单列": "Not separately listed",
  "时段": "Time window",
  "高峰（UTC）": "Peak (UTC)",
  "优惠期间（UTC）": "Promotional period (UTC)",
  "智谱": "Zhipu AI",
  "服务下线": "Service retirement",
  "平台更新": "Platform update",
  "与": "and",
  "COST & COMPUTE / 价格观察": "COST & COMPUTE / PRICE OBSERVATIONS",
  "2026-08 国内平台参考价。价格带按包月成本的平方根刻度展示，兼顾消费级与数据中心卡的量级差异。": "Domestic platform reference prices, August 2026. Monthly costs use a square-root scale to show both consumer and data-center GPUs.",
  "2026-09-01 公开信息快照。按厂商归并关键经营与产品节点，避免把不同口径误读成同一排行榜。": "Public information snapshot, September 1, 2026. Business and product milestones are grouped by vendor; figures with different definitions do not form a single ranking.",
  "算家云 / AutoDL 等": "Suanjia Cloud / AutoDL and others",
  "AutoDL / 极智算": "AutoDL / Jizhisuan",
  "InfoQ 评测 / 行情": "InfoQ reviews / market reports",
  "社区行情 2026-07": "Community market reports, July 2026",
  "昇腾 910C": "Ascend 910C",
  "81.2 万颗": "812,000 chips",
  "政务/国企/运营商市场份额超 70%": "Over 70% share in government, state-owned enterprise and telecom markets",
  "川观新闻 2026-08": "Chuanguan News, August 2026",
  "IDC 2025 国产 AI 加速卡交付份额 41%": "41% of domestic AI accelerator deliveries in 2025 (IDC)",
  "南方财经 2026-07": "Southern Finance, July 2026",
  "11.74 万卡 (+201.57%)": "117,400 cards (+201.57%)",
  "产量 12.77 万卡 (+409.84%)": "Production: 127,700 cards (+409.84%)",
  "证券时报 2026-07": "Securities Times, July 2026",
  "2026H1 营收": "2026 H1 revenue",
  "59.96 亿元 (+108.13%)": "CNY 5.996 billion (+108.13%)",
  "净利 23.11 亿元 (+122.61%)，科创板首家万亿市值": "Net profit: CNY 2.311 billion (+122.61%); first STAR Market company to reach a CNY 1 trillion valuation",
  "大河财立方 2026-09": "Dahe Financial Cube, September 2026",
  "思元 690": "Siyuan 690",
  "2026 年初量产": "Mass production in early 2026",
  "2026-09 上市": "Listed in September 2026",
  "观察者网 2026-08": "Guancha, August 2026",
  "数据来自证券时报 / 财联社 / 新华网 / 川观新闻等公开报道。2026 年被业内视为国产 AI 芯片「全线兑现元年」。": "Data comes from public reporting by Securities Times, Cailian Press, Xinhua, Chuanguan News and others. Industry reporting describes 2026 as a year of broad delivery for domestic AI chips.",
  "。按模型查看报价与变化；不同地区、计费方式和上下文条件分开列示。": ". Browse prices and changes by model. Regions, billing modes and context conditions remain separate.",
  "，不代表供应商实时官网。未记录到匹配项，不等于外部世界没有变化；不同条件的价格需分别核对。详情页是修订与撤回状态的权威来源。": ". This is not a live provider quote. No matching record does not imply no external change. Check prices against their billing conditions. Detail pages are authoritative for revisions and withdrawals.",
  "生产 feed 于 2026-09-20 上线（rl_31c918e04d）；feedparser 真实订阅验收通过（pubDate 精度语义、ETag/304）": "Production feed launched September 20, 2026 (rl_31c918e04d); real feedparser subscription checks passed for pubDate precision and ETag/304.",
  "数据版本": "Dataset version",
  "变化覆盖": "Change coverage",
  "语音转写模型2.0上线，1.0退役": "Voice transcription 2.0 launches; 1.0 retires",
  "grok-voice-transcribe-1.0 标记为 deprecated，2026-10-02 起所有请求自动切换至 2.0": "grok-voice-transcribe-1.0 is deprecated; requests automatically switch to 2.0 from October 2, 2026.",
  "榜单新增多款旗舰模型，价格微调": "Flagship models join rankings with minor price adjustments",
  "Claude Fable 5.1 (Max) 价格从 $4.66/task 下调至 $4.56/task": "Claude Fable 5.1 (Max) drops from $4.66/task to $4.56/task.",
  "Claude Sonnet 5.5 推理档位命名简化": "Claude Sonnet 5.5 simplifies reasoning tier names",
  "Claude Sonnet 5.5 的 Adaptive Reasoning 档位名称简化为 High/Low/Max/Medium/Xhigh": "Claude Sonnet 5.5 Adaptive Reasoning tiers are renamed High/Low/Max/Medium/Xhigh."
});

Object.assign(uiEnglish, {
  "当前覆盖范围内暂无相关记录。": "No records in the current coverage range.",
  "加载中…": "Loading…",
  "MODEL INTELLIGENCE / 榜单观察": "MODEL INTELLIGENCE / RANKINGS",
  "用数据，找到合适的模型。": "Find the right model with data.",
  "从真实调用到能力评测，换一个角度看模型。选择榜单，搜索、排序，再做比较。": "Explore models through real usage and independent benchmarks. Select a ranking, search, sort and compare.",
  "榜单分区": "Ranking sections",
  "谁在被使用": "Which models are used",
  "调用量 · 份额 · 成本 · 应用": "Usage · share · cost · apps",
  "谁更擅长": "Which models perform better",
  "偏好 · 智能 · 中文 · 编程 · Agent": "Preference · intelligence · Chinese · coding · agents",
  "开发者采用 · OpenRouter": "Developer adoption · OpenRouter",
  "按经 OpenRouter API 路由的真实 token 量统计，每日自动抓取。它衡量采用而非质量，只反映 OpenRouter 流量而非全市场。": "Based on real token usage routed through the OpenRouter API and collected daily. It measures adoption rather than quality and covers OpenRouter traffic, not the entire market.",
  "模型调用量": "Model usage",
  "厂商份额": "Provider share",
  "会话成本": "Session costs",
  "热门应用": "Popular apps",
  "采用数据视图": "Adoption data views",
  "每日更新": "Updated daily",
  "抓取": "Fetched",
  "当前排名": "Current rank",
  "本期调用量": "Token usage this period:",
  "，较上期": ", versus the previous period: ",
  "。调用量反映采用情况，不等同于模型能力。": ". Usage reflects adoption, not model capability.",
  "查看 OpenRouter 原榜 ↗": "View the original OpenRouter ranking ↗",
  "占 OpenRouter 本期流量": "Share of OpenRouter traffic this period: ",
  "。份额变化以百分点计。": ". Changes in share are measured in percentage points.",
  "查看份额来源 ↗": "View share source ↗",
  "能力榜": "Capability benchmarks",
  "五个独立第三方评测，口径互补：真实使用偏好（LMArena）、综合智能（AA）、中文场景（SuperCLUE）、工程实战（SWE-bench）、Agent 任务（Terminal-Bench）。": "Five independent benchmarks provide complementary views: user preference (LMArena), general intelligence (AA), Chinese-language tasks (SuperCLUE), software engineering (SWE-bench) and agent tasks (Terminal-Bench).",
  "能力评测视图": "Benchmark views",
  "AA 智能指数": "AA Intelligence Index",
  "新上榜": "New entry",
  "备注": "Notes",
  "轮次": "Turns",
  "$ / 会话": "$ / session",
  "应用": "App",
  "请求": "Requests",
  "官方信源解决「有什么」· 第三方榜单解决「好不好」· 社区解决「好不好用」· 融资财报解决「赚不赚钱」。所有 URL 均于 2026-09-02 验证可用。": "Official sources show availability; third-party rankings show performance; communities show practical usability; financial reporting shows business results. All URLs were checked on September 2, 2026.",
  "国内平台": "Domestic platforms",
  "海外平台": "International platforms",
  "行业源": "Industry sources",
  "官网 ↗": "Official site ↗",
  "模型列表": "Model list",
  "定价": "Pricing",
  "API 文档": "API docs",
  "博客/新闻": "Blog / news",
  "模型广场": "Model catalog",
  "百度千帆": "Baidu Qianfan",
  "火山方舟": "Volcengine Ark",
  "腾讯混元": "Tencent Hunyuan",
  "硅基流动": "SiliconFlow",
  "智谱AI": "Zhipu AI",
  "归档": "Archive",
  "周度归档": "Weekly archive",
  "每日动态按周聚合，含周度回顾与逐日要点。": "Daily updates grouped by week, with weekly summaries and daily highlights.",
  "深度周报": "In-depth reports",
  "周度归档数据积累中。": "Weekly archives are being collected.",
  "关于": "About",
  "是一个追踪全球主流 MaaS（Model as a Service）平台动态的每日报告站点。": "is a daily reporting site tracking leading MaaS (Model as a Service) platforms worldwide.",
  "追踪维度": "Tracking dimensions",
  "每个平台覆盖以下 6 个维度：": "Six dimensions are tracked for each platform:",
  "API 定价（P0）": "API pricing (P0)",
  "更新日志 / 发布公告（P0）": "Changelogs / release announcements (P0)",
  "API 参考文档（P1）": "API reference documentation (P1)",
  "官方 GitHub 仓库（P1）": "Official GitHub repositories (P1)",
  "官方博客 / 新闻（P1）": "Official blogs / news (P1)",
  "更新频率": "Update frequency",
  "每周二、周五各一期追踪报告，覆盖上一周期的模型发布、定价变更、API 更新与开源动态。": "Reports are published every Tuesday and Friday, covering model releases, pricing changes, API updates and open-source developments from the preceding period.",
  "首页": "Home",
  "跨平台比较": "Cross-platform comparison",
  "同一模型，不同平台怎么收费？": "How do platforms price the same model?",
  "开发者与调用平台分别标注。以下展示标准实时档的已核验报价，保留区域、上下文和优惠条件；没有报价不代表免费。": "Developers and serving platforms are identified separately. Verified standard real-time prices retain region, context and promotional conditions. A missing quote does not mean free service.",
  "。相同上游模型不代表服务限制、地域或计费条件相同。": ". Sharing an upstream model does not imply identical service limits, regions or billing conditions.",
  "开发者：": "Developer: ",
  "官方模型关系": "Official model relationship",
  "核验于": "Verified on",
  "价格详情与变化 →": "Price details and changes →",
  "调用平台 / API 标识": "Serving platform / API identifier",
  "地区与条件": "Region and conditions",
  "报价依据": "Pricing evidence",
  "可用关系 ↗": "Availability evidence ↗",
  "实时 · 标准档": "Real time · standard tier",
  "上下文：": "Context: ",
  "输入：": "Input: ",
  "输出：": "Output: ",
  "等待完整、最新的价格证据": "Waiting for complete, current pricing evidence",
  "报价待补齐": "Quote not available",
  "美国多区域": "US multi-region",
  "欧盟多区域": "EU multi-region",
  "非全球端点": "Regional endpoint",
  "当前公开版本尚未收录经核验的跨平台关系。": "This public release has no verified cross-platform relationships yet.",
  "批处理、优先档、缓存写入和其他条件报价见模型详情；此页不把不同条件混合成最低价排名。": "See model details for batch, priority, cache-write and other conditional prices. This page does not combine incompatible conditions into a lowest-price ranking.",
  "公开接口变更日志": "Public interface changelog",
  "接口": "Interface",
  "状态": "Status",
  "网页": "Website",
  "只记录真实发生的接口变更。当前无任何 Deprecation/Sunset 计划—— 出现时将附确定的停止日期与迁移路径。": "This log records actual interface changes. There is currently no deprecation or sunset plan; any future announcement will include a specific end date and migration path.",
  "v1 兼容策略": "v1 compatibility policy",
  "v1 内允许": "Within v1 we allow ",
  "新增": "additions",
  "可选字段、端点说明和兼容能力；": " of optional fields, endpoint documentation and compatible capabilities;",
  "删除字段、改变字段含义、改变稳定 ID 或改变默认排序属于": "removing fields or changing field meanings, stable IDs or default ordering are ",
  "破坏性变更": "breaking changes",
  "——将新开 v2；": " and require a new v2;",
  "稳定 ID（obs_/price_/ev_/pfv_ 前缀）一经发布不复用。": "Published stable IDs (obs_/price_/ev_/pfv_ prefixes) are never reused.",
  "Agent 接口公开可用（GA）：REST / MCP / Skill / RSS 上线": "Agent interfaces are generally available: REST / MCP / Skill / RSS",
  "本条目不包含破坏性变更。": "This entry contains no breaking changes."
});
