import {onAccountChange} from './account-client';
import {paymentTable,paymentText,paymentTime,userPaymentAmount} from '../lib/payment-view';
type Row=Record<string,unknown>;type Billing={subscriptions:Row[];orders:Row[];entitlement:Row;checkoutAvailability:string;truncated:boolean};
let generation=0,authenticated=false,busy=false;
const el=(id:string)=>document.getElementById(id)!,status=el('billing-status'),buy=el('billing-buy') as HTMLButtonElement;
function clear(){generation++;authenticated=false;for(const id of ['billing-records','billing-subscriptions','billing-entitlement'])el(id).replaceChildren();buy.disabled=true;}
async function write(route:string,input:Row){const r=await fetch('/api/pro/billing/'+route,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),v=await r.json();if(!r.ok)throw Error(v.message);return v as Row;}
async function load(){clear();const g=generation;status.textContent='正在读取订阅…';try{const r=await fetch('/api/pro/billing',{credentials:'same-origin',cache:'no-store'}),v=await r.json() as Billing&{message:string};if(g!==generation)return;if(!r.ok)throw Error(v.message);authenticated=true;buy.disabled=busy||v.checkoutAvailability!=='simulator';status.textContent=v.checkoutAvailability==='simulator'?'本机支付模拟器；不接真实支付、不扣款。':'真实沙箱尚未配置，暂不能购买。';el('billing-entitlement').textContent='当前权益：'+(v.entitlement.status==='active'?'Plus':'Free')+(v.entitlement.starts===null?' · 无有效权益':' · 来源 '+({paid:'付费',beta:'免费公测',manual:'手工授权'}[String(v.entitlement.source)]??paymentText(v.entitlement.source)));
 if(!v.subscriptions.length)el('billing-subscriptions').textContent='尚无付费订阅';
 for(const s of v.subscriptions){const article=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent='订阅 · '+paymentText(s.state);p.textContent='服务周期结束：'+paymentTime(s.periodEnd)+'；'+(s.cancelAtPeriodEnd?'已停止续费':s.renewalFailed?'续费失败，已付周期保留至到期':s.nextRenewalAt?'下次续费：'+paymentTime(s.nextRenewalAt):'无已确认续费计划');article.append(h,p);const order=v.orders.find(o=>o.subscriptionId===s.id);
 if(order&&!s.cancelAtPeriodEnd&&s.state==='active'){const button=document.createElement('button');button.type='button';button.textContent='取消续费（当前周期保留）';button.disabled=v.checkoutAvailability!=='simulator';button.addEventListener('click',async()=>{if(!authenticated||g!==generation||busy)return;busy=true;button.disabled=true;try{await write('cancel',{orderId:order.id});if(g===generation&&authenticated)await load();}catch(e){if(g===generation)status.textContent=e instanceof Error?e.message:'取消结果未知，请刷新查询';}finally{busy=false;if(g===generation)button.disabled=false;}});article.append(button);}el('billing-subscriptions').append(article);}
 el('billing-records').append(paymentTable(v.orders,[['id','订单'],['state','付款状态'],['amount','支付金额',o=>userPaymentAmount(o.amount,o.currency)],['refundState','退款'],['refundedAmount','已退金额',o=>userPaymentAmount(o.refundedAmount,o.currency)],['createdAt','创建时间',o=>paymentTime(o.createdAt)]]));if(v.truncated)status.textContent+=' 仅显示最近100个订单。';
 }catch(e){if(g===generation){clear();status.textContent=e instanceof Error?e.message:'订阅查询失败';}}}
let purchaseKey=crypto.randomUUID();buy.addEventListener('click',async()=>{if(!authenticated||busy)return;const g=generation;busy=true;buy.disabled=true;try{const v=await write('checkout',{key:purchaseKey});if(g!==generation||!authenticated)return;if(v.mode==='simulator'&&typeof v.url==='string'&&v.url.startsWith('/subscription/sandbox/'))location.assign(v.url);else{purchaseKey=crypto.randomUUID();status.textContent='结账地址不可用，请刷新查询订单。';}}catch(e){if(g===generation)status.textContent=e instanceof Error?e.message:'结账结果未知，请刷新查询订单';}finally{busy=false;if(g===generation&&authenticated)buy.disabled=false;}});
onAccountChange(()=>{purchaseKey=crypto.randomUUID();void load();});el('billing-refresh').addEventListener('click',()=>void load());window.addEventListener('pagehide',clear);
