import { accountApi, currentAccount, onAccountChange, openAccountLogin } from './account-client';
const root=document.querySelector<HTMLElement>('[data-feedback-page]');
if(root){
  const t=(zh:string,en:string)=>root.dataset.locale==='en'?en:zh;
  const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
  const form=el<HTMLFormElement>('feedback-form'),files=el<HTMLInputElement>('feedback-files');
  let selected:File[]=[],urls:string[]=[],generation=0,busy=false,ownerId: string | null=null;
  const status=(message:string,error=false)=>{el('feedback-status').textContent=message;el('feedback-status').dataset.error=String(error);};
  function previews(){for(const url of urls)URL.revokeObjectURL(url);urls=[];el('feedback-previews').replaceChildren();selected.forEach((file,index)=>{const figure=document.createElement('figure'),image=document.createElement('img'),caption=document.createElement('figcaption'),remove=document.createElement('button');const url=URL.createObjectURL(file);urls.push(url);image.src=url;image.alt=t('待提交截图','Screenshot to submit');caption.textContent=file.name;remove.type='button';remove.textContent=t('移除','Remove');remove.disabled=busy;remove.onclick=()=>{selected.splice(index,1);previews();};figure.append(image,caption,remove);el('feedback-previews').append(figure);});}
  function clear(){form.reset();selected=[];previews();}
  function controls(){el<HTMLButtonElement>('feedback-submit').disabled=busy;form.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>('input,textarea').forEach(field=>field.disabled=busy);el('feedback-previews').querySelectorAll<HTMLButtonElement>('button').forEach(button=>button.disabled=busy);}
  const node=(tag:string,value:string)=>{const n=document.createElement(tag);n.textContent=value;return n;};
  type Report={id:string;title:string;description:string;page:string;status:string;reply:string;created:number;imageCount:number};
  async function history(){const version=generation;const response=await accountApi<{items:Report[]}>('feedback');if(version!==generation)return;const list=el('feedback-history');list.replaceChildren();if(!response.items.length)list.append(node('p',t('还没有反馈记录。','No reports yet.')));for(const item of response.items){const article=document.createElement('article');article.className='feedback-report';const labels:Record<string,string>={open:t('待处理','Open'),investigating:t('处理中','Investigating'),resolved:t('已解决','Resolved')};article.append(node('h3',item.title),node('small',`${labels[item.status]??item.status} · ${new Date(item.created).toLocaleString()} · ${item.id}`),node('p',item.description));if(item.page)article.append(node('small',item.page));if(item.reply)article.append(node('p',t('处理说明：','Reply: ')+item.reply));for(let i=0;i<item.imageCount;i++){const link=document.createElement('a');link.href=`/api/account/feedback/${item.id}/image/${i}`;link.target='_blank';link.rel='noopener';link.textContent=t(`截图 ${i+1}`,`Screenshot ${i+1}`);article.append(link);}list.append(article);}}
  const fillPage=()=>{let path=new URL(location.href).searchParams.get('from')??'';if(!path&&document.referrer){const ref=new URL(document.referrer);if(ref.origin===location.origin)path=ref.pathname;}if(path.startsWith('/')&&!path.startsWith('//')&&!/[?#]/.test(path))el<HTMLInputElement>('feedback-page').value=path.slice(0,500);};
  files.addEventListener('change',()=>{const incoming=Array.from(files.files??[]);files.value='';if(selected.length+incoming.length>3){status(t('最多上传3张截图。','You can upload up to 3 screenshots.'),true);return;}if(incoming.some(file=>!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024||!file.size)){status(t('截图需为PNG、JPEG或WebP，每张不超过2MB。','Use PNG, JPEG or WebP images up to 2 MB each.'),true);return;}selected.push(...incoming);previews();status('');});
  const encode=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.onerror=()=>reject(new Error(t('截图读取失败，请重新选择。','Could not read screenshot. Select it again.')));reader.readAsDataURL(file);});
  form.addEventListener('submit',async event=>{event.preventDefault();if(busy||!form.reportValidity())return;if(!currentAccount()){openAccountLogin();return;}const owner=generation;busy=true;controls();status(t('正在提交…','Submitting…'));try{const images=await Promise.all(selected.map(async file=>({mime:file.type,data:await encode(file)})));if(owner!==generation)return;const result=await accountApi<{id:string}>('feedback',{title:el<HTMLInputElement>('feedback-title').value,description:el<HTMLTextAreaElement>('feedback-description').value,page:el<HTMLInputElement>('feedback-page').value,images});if(owner!==generation)return;clear();status(t(`提交成功，反馈编号：${result.id}`,`Report submitted. ID: ${result.id}`));try{await history();}catch{if(owner===generation)status(t(`提交成功，编号：${result.id}。暂时无法读取历史，请刷新处理进度。`,`Report submitted. ID: ${result.id}. Refresh to load history.`));}}catch(error){if(owner===generation)status(error instanceof Error?error.message:t('提交失败，请稍后重试。','Could not submit. Try again.'),true);}finally{busy=false;controls();}});
  el('feedback-login').onclick=openAccountLogin;
  el('feedback-refresh').onclick=()=>{void history().catch(error=>status(error.message,true));};
  onAccountChange(account=>{const next=account?.user.id??null;if(next===ownerId)return;ownerId=next;generation++;clear();status('');el('feedback-workspace').hidden=!account;el('feedback-guest').hidden=Boolean(account);el('feedback-history').replaceChildren();if(account){fillPage();void history().catch(error=>status(error.message,true));}});
  window.addEventListener('pagehide',()=>{for(const url of urls)URL.revokeObjectURL(url);urls=[];});
}
