const data=JSON.parse(document.querySelector('#lab-data')!.textContent!);
const styles=[
  {id:'swiss',name:'瑞士极简',en:'Swiss',note:'01 / Swiss Minimalist — 严格网格、红色定位线、清晰的字号层级。'},
  {id:'spec',name:'技术规格',en:'Spec Sheet',note:'02 / Spec Sheet — 冷灰网格、等宽数字、紧凑的信息终端。'},
  {id:'ink',name:'电子墨水',en:'E-Ink',note:'03 / E-Ink Digital — 黑白、纸面质感、适合阅读的单列节奏。'},
  {id:'brutal',name:'新粗野主义',en:'Neubrutalism',note:'04 / Neubrutalism — 明黄、硬边框、错位阴影与按压反馈。'},
  {id:'bauhaus',name:'包豪斯',en:'Bauhaus',note:'05 / Bauhaus — 红黄蓝几何、非对称构图、醒目的内容分区。'},
  {id:'glass',name:'液态玻璃',en:'Liquid Glass',note:'06 / Liquid Glass — 通透面板、柔和景深、悬浮与弹性反馈。'}
];
const esc=(v:any)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const read=(key:string,fallback:any)=>{try{return JSON.parse(localStorage.getItem(key)??'null')??fallback}catch{return fallback}};
const state={style:new URL(location.href).searchParams.get('style')??read('maas-lab-style','swiss'),route:new URL(location.href).searchParams.get('view')??'daily',filter:'all',search:'',saved:read('maas-lab-saved',[]) as number[],compare:[] as string[],favorites:read('maas-lab-favorites',[]) as string[]};
if(!styles.some(s=>s.id===state.style))state.style='swiss';
if(!['daily','prices','saved'].includes(state.route))state.route='daily';
const product=document.querySelector<HTMLElement>('.product')!;
const app=document.querySelector<HTMLElement>('#app')!;
const dialog=document.querySelector<HTMLDialogElement>('#detail')!;
const labels:Record<string,string>={release:'新发布',pricing:'价格变化',sunset:'下线提醒',other:'平台更新'};
let toastTimer:ReturnType<typeof setTimeout>;
function persist(key:string,value:any){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function toast(message:string){const el=document.querySelector<HTMLElement>('.toast')!;el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),2400)}
function url(){const u=new URL(location.href);u.searchParams.set('style',state.style);u.searchParams.set('view',state.route);history.replaceState(null,'',u)}
function applyStyle(){product.dataset.style=state.style;document.body.dataset.style=state.style;document.querySelector('#style-note')!.textContent=styles.find(s=>s.id===state.style)!.note;document.querySelectorAll<HTMLButtonElement>('[data-style-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.styleChoice===state.style)));document.querySelector('.favorite')!.textContent=state.favorites.includes(state.style)?'★ 已收藏':'☆ 收藏风格';persist('maas-lab-style',state.style);url()}
document.querySelector('.style-switcher')!.innerHTML=styles.map((s,i)=>`<button data-style-choice="${s.id}" aria-pressed="false"><span class="swatch swatch-${s.id}"></span><span>${s.name}<small>${s.en}</small></span><em>0${i+1}</em></button>`).join('');
document.querySelectorAll<HTMLButtonElement>('[data-style-choice]').forEach(b=>b.addEventListener('click',()=>{state.style=b.dataset.styleChoice!;applyStyle()}));
document.querySelector('.favorite')!.addEventListener('click',()=>{state.favorites=state.favorites.includes(state.style)?state.favorites.filter(x=>x!==state.style):[...state.favorites,state.style];persist('maas-lab-favorites',state.favorites);applyStyle();toast(state.favorites.includes(state.style)?'已收藏这个风格':'已取消收藏')});
function card(e:any,i:number){return `<article class="event-card type-${e.type}" style="--order:${i}"><div class="event-top"><span class="event-number">${String(e.id+1).padStart(2,'0')}</span><span class="event-type">${labels[e.type]}</span><button class="save" data-save="${e.id}" aria-label="${state.saved.includes(e.id)?'取消关注':'关注'} ${esc(e.platform)}" aria-pressed="${state.saved.includes(e.id)}">${state.saved.includes(e.id)?'★':'☆'}</button></div><div class="platform">${e.logo?`<img src="${esc(e.logo)}" alt=""/>`:''}<span>${esc(e.platform)}</span></div><h2><button data-detail="${e.id}">${esc(e.title)}</button></h2><p>${esc(e.items[0]?.text)}</p><button class="text-action" data-detail="${e.id}">展开完整动态 <span>↗</span></button></article>`}
function render(){url();document.querySelectorAll<HTMLButtonElement>('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===state.route)));document.querySelector('#saved-count')!.textContent=String(state.saved.length);
  if(state.route==='prices'){renderPrices();return}
  const all=state.route==='saved'?data.events.filter((e:any)=>state.saved.includes(e.id)):data.events;
  const list=all.filter((e:any)=>(state.filter==='all'||e.items.some((x:any)=>x.type===state.filter))&&JSON.stringify(e).toLowerCase().includes(state.search.toLowerCase()));
  app.innerHTML=`<section class="edition"><div class="edition-copy"><span class="eyebrow">${state.route==='saved'?'YOUR WATCHLIST':'DAILY INTELLIGENCE / '+data.date.replaceAll('-','.')}</span><h1>${state.route==='saved'?'你关注的，<br>都在这里。':'模型世界，<br><span>今天发生了什么？</span>'}</h1><p>${state.route==='saved'?'关注值得持续跟踪的平台动态。':'跟踪新模型、价格与下线信息。把今天的变化，看清楚。'}</p></div><div class="edition-art" aria-hidden="true"><span class="art-circle"></span><span class="art-square"></span><span class="art-triangle"></span><b>M<span>↗</span></b><small>OBSERVE / COMPARE / DECIDE</small></div><div class="edition-stats"><div><strong>${data.events.length.toString().padStart(2,'0')}</strong><span>平台动态</span></div><div><strong>${data.events.filter((e:any)=>e.items.some((x:any)=>x.type==='release')).length.toString().padStart(2,'0')}</strong><span>发布信号</span></div><div><strong>${data.events.filter((e:any)=>e.items.some((x:any)=>x.type==='sunset')).length.toString().padStart(2,'0')}</strong><span>下线提醒</span></div></div></section>
  <section class="feed-section"><div class="section-title"><div><span class="eyebrow">01 / SIGNALS</span><h2>${state.route==='saved'?'关注列表':'今日动态'}</h2></div><span class="result-count">${list.length} 条动态</span></div><div class="filter-bar"><div class="filters">${[['all','全部'],['release','新发布'],['pricing','价格变化'],['sunset','下线提醒']].map(([v,l])=>`<button data-filter="${v}" aria-pressed="${state.filter===v}">${l}</button>`).join('')}</div><label class="search"><span>⌕</span><input type="search" id="event-search" placeholder="搜索平台或模型" aria-label="搜索平台或模型" value="${esc(state.search)}"/><kbd>/</kbd></label></div><div class="event-grid">${list.length?list.map(card).join(''):`<div class="empty"><h3>${state.route==='saved'&&!state.saved.length?'还没有关注动态':'没有匹配的动态'}</h3><p>${state.route==='saved'&&!state.saved.length?'点击动态卡片上的 ☆，建立你的关注列表。':'换个关键词，或重置筛选条件。'}</p><button data-reset class="primary">${state.route==='saved'&&!state.saved.length?'浏览每日动态':'重置筛选'}</button></div>`}</div></section><section class="market-link"><div><span class="eyebrow">02 / MODEL PRICES</span><h2>变化之后，看看价格。</h2><p>${data.models.length} 个重点模型 · 明确档位 · 原币种报价</p></div><button class="primary" data-go-prices>进入模型价格 <span>→</span></button></section>`;
  bind();
}
function renderPrices(){app.innerHTML=`<section class="price-edition"><span class="eyebrow">MODEL PRICE SHEET / ${data.through}</span><h1>模型价格，<br><span>放在一起看。</span></h1><p>每个模型展示一个明确档位的原币种报价。勾选模型，比较价格与适用条件。</p></section><div class="section-title"><h2>重点模型 / ${data.models.length}</h2><span class="result-count">单位与条件随报价展示</span></div><div class="price-table-wrap"><table class="price-table"><thead><tr><th>比较</th><th>模型 / 平台</th><th>输入</th><th>输出</th><th>缓存读取</th><th>报价单位 / 档位</th><th>详情</th></tr></thead><tbody>${data.models.map((m:any)=>`<tr class="${state.compare.includes(m.id)?'selected':''}"><td><input type="checkbox" data-compare="${esc(m.id)}" aria-label="比较 ${esc(m.name)}" ${state.compare.includes(m.id)?'checked':''}/></td><td><strong>${esc(m.name)}</strong><small>${esc(m.provider)}</small></td><td class="number">${esc(m.input)}</td><td class="number">${esc(m.output)}</td><td class="number">${esc(m.cache)}</td><td>${esc(m.unit)}<small>${esc(m.condition)}</small><small>观察于 ${esc(m.date)}</small></td><td><button class="text-action" data-model="${esc(m.id)}">详情 ↗</button></td></tr>`).join('')}</tbody></table></div><p class="price-footnote">不同币种、区域、上下文与时段的价格需分别解读；此处展示原始报价，不做最低价排名。</p><section class="market-link"><div><span class="eyebrow">FOLLOW THE SIGNAL</span><h2>回到今天的变化。</h2></div><button class="primary" data-go-daily>每日动态 →</button></section>`;bind();updateTray()}
function bind(){app.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter!;render()});const search=app.querySelector<HTMLInputElement>('#event-search');if(search)search.oninput=()=>{const pos=search.selectionStart;state.search=search.value;render();const next=app.querySelector<HTMLInputElement>('#event-search')!;next.focus();try{next.setSelectionRange(pos,pos)}catch{}};
  app.querySelectorAll<HTMLButtonElement>('[data-save]').forEach(b=>b.onclick=()=>{const id=Number(b.dataset.save);state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];persist('maas-lab-saved',state.saved);render();toast(state.saved.includes(id)?'已加入我的关注':'已取消关注')});
  app.querySelectorAll<HTMLButtonElement>('[data-detail]').forEach(b=>b.onclick=()=>showEvent(Number(b.dataset.detail)));
  app.querySelectorAll<HTMLInputElement>('[data-compare]').forEach(b=>b.onchange=()=>{const id=b.dataset.compare!;if(b.checked&&state.compare.length>=3){b.checked=false;toast('最多同时比较 3 个模型');return}state.compare=b.checked?[...state.compare,id]:state.compare.filter(x=>x!==id);b.closest('tr')!.classList.toggle('selected',b.checked);updateTray()});
  app.querySelectorAll<HTMLButtonElement>('[data-model]').forEach(b=>b.onclick=()=>showModel(b.dataset.model!));
  const reset=app.querySelector<HTMLButtonElement>('[data-reset]');if(reset)reset.onclick=()=>{state.filter='all';state.search='';if(state.route==='saved'&&!state.saved.length)state.route='daily';render()};
  for(const [selector,route] of [['[data-go-prices]','prices'],['[data-go-daily]','daily']]){const b=app.querySelector<HTMLButtonElement>(selector);if(b)b.onclick=()=>navigate(route)}
}
function navigate(route:string){state.route=route;state.filter='all';state.search='';render();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll<HTMLButtonElement>('[data-route]').forEach(b=>b.onclick=()=>navigate(b.dataset.route!));
function show(content:string){dialog.querySelector('.dialog-inner')!.innerHTML=`<button class="dialog-close" aria-label="关闭详情">×</button>${content}`;dialog.querySelector<HTMLButtonElement>('.dialog-close')!.onclick=()=>dialog.close();dialog.showModal()}
function showEvent(id:number){const e=data.events.find((x:any)=>x.id===id);show(`<span class="eyebrow">${esc(e.platform)} / ${data.date}</span><h2>${esc(e.title)}</h2><div class="detail-items">${e.items.map((x:any)=>`<div><span class="event-type">${labels[x.type]??labels.other}</span><p>${esc(x.text)}</p></div>`).join('')}</div><a class="primary" href="/#digest" target="_blank">查看完整日报与依据 ↗</a>`)}
function showModel(id:string){const m=data.models.find((x:any)=>x.id===id);show(`<span class="eyebrow">${esc(m.provider)} / PRICE RECORD</span><h2>${esc(m.name)}</h2><div class="model-quotes"><div><span>输入</span><strong>${esc(m.input)}</strong></div><div><span>输出</span><strong>${esc(m.output)}</strong></div><div><span>缓存读取</span><strong>${esc(m.cache)}</strong></div></div><p>${esc(m.unit)}</p><p>${esc(m.condition)}</p><p>观察于 ${esc(m.date)}</p><a class="primary" href="/model/${encodeURIComponent(m.id)}/" target="_blank">查看全部档位与证据 ↗</a>`)}
function updateTray(){const tray=document.querySelector<HTMLElement>('.compare-tray')!;tray.hidden=!state.compare.length;document.querySelector('#compare-count')!.textContent=`已选择 ${state.compare.length} 个模型`;document.querySelector<HTMLButtonElement>('#open-compare')!.disabled=state.compare.length<2}
document.querySelector<HTMLButtonElement>('#clear-compare')!.onclick=()=>{state.compare=[];if(state.route==='prices')render();updateTray()};
document.querySelector<HTMLButtonElement>('#open-compare')!.onclick=()=>{const chosen=data.models.filter((x:any)=>state.compare.includes(x.id));show(`<span class="eyebrow">SIDE BY SIDE / ${chosen.length} MODELS</span><h2>模型报价比较</h2><div class="comparison-grid">${chosen.map((m:any)=>`<article><h3>${esc(m.name)}</h3><p>${esc(m.provider)}</p><dl>${[['输入',m.input],['输出',m.output],['缓存读取',m.cache]].map(([l,v])=>`<dt>${l}</dt><dd>${esc(v)}</dd>`).join('')}</dl><p>${esc(m.unit)}</p><small>${esc(m.condition)}</small></article>`).join('')}</div><p>按各自原币种和适用档位展示，未做汇率或计费条件换算。</p>`)};
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!dialog.open&&!(e.target instanceof HTMLInputElement)){const s=app.querySelector<HTMLInputElement>('#event-search');if(s){e.preventDefault();s.focus()}}});
applyStyle();render();updateTray();
