import { AccountError, hash } from './account-store.js';
import { AdminStore, type AdminCommand } from './admin-store.js';
import { page, query } from './admin-operations.js';

const bad=(message:string,code='invalid_parameter',status=400)=>new AccountError(status,code,message);
const enumValue=(v:unknown,values:readonly string[])=>{if(typeof v!=='string'||!values.includes(v))throw bad('记录枚举无效');return v;};
const id=(v:unknown)=>{if(typeof v!=='string'||!/^[a-zA-Z0-9:_-]{1,128}$/.test(v))throw bad('记录标识无效');return v;};
const text=(v:unknown,max=120)=>{if(typeof v!=='string'||v.length>max||/[\x00-\x1f]/.test(v))throw bad('记录文本无效');return v;};
const stamp=(v:unknown)=>{if(v===null)return null;if(!Number.isSafeInteger(v)||Number(v)<0)throw bad('记录时间无效');return Number(v);};
const fields=(v:any,keys:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k))||keys.some(k=>!(k in v)))throw bad('采集协议字段无效');};
const states=['queued','running','succeeded','failed','needs_review','cancelled'] as const;
const results=['success','partial','failed','unchanged','not_run','unknown'] as const;
const errors=['fetch_failed','parse_failed','fetch_or_parse_failed','validation_failed','execution_failed','interrupted','coverage_missing','unknown'] as const;
export const errorSummary=(code:unknown)=>code===null?null:({fetch_failed:'抓取失败',parse_failed:'解析失败',fetch_or_parse_failed:'抓取或解析失败（历史记录无法区分）',validation_failed:'已有校验未通过',execution_failed:'执行失败，请检查受控运行入口',interrupted:'运行中断，需核查',coverage_missing:'覆盖缺失',unknown:'原因未知'}[String(code)]??'原因未知');
export const workflowLink=(v:unknown)=>{if(v===null)return null;const s=text(v,300);if(!/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+\/actions\/runs\/\d+$/.test(s))throw bad('运行链接无效');return s;};
export class AdminMonitor {
 readonly db;
 constructor(readonly admin:AdminStore){this.db=admin.db;admin.accounts.transaction(()=>{
  if(this.db.prepare("SELECT 1 FROM sqlite_master WHERE name='editorial_runs'").get())this.db.exec('CREATE INDEX IF NOT EXISTS editorial_runs_monitor_order ON editorial_runs(createdAt DESC,id DESC)');
  if(this.db.prepare('SELECT 1 FROM admin_schema_migrations WHERE version=5').get())return;
  this.db.exec(`CREATE TABLE monitor_sources(id TEXT PRIMARY KEY,name TEXT NOT NULL,platform TEXT NOT NULL,kind TEXT NOT NULL,budgetHours INTEGER NOT NULL);
   CREATE TABLE monitor_runs(id TEXT PRIMARY KEY,kind TEXT NOT NULL,trigger TEXT NOT NULL,state TEXT NOT NULL,stage TEXT NOT NULL,startedAt INTEGER,finishedAt INTEGER,observedAt INTEGER NOT NULL,inputVersion TEXT,outputVersion TEXT,result TEXT NOT NULL,validation TEXT NOT NULL,publication TEXT NOT NULL,errorCode TEXT,runLink TEXT,payloadHash TEXT NOT NULL,receivedAt INTEGER NOT NULL);
   CREATE INDEX monitor_runs_order ON monitor_runs(observedAt DESC,id DESC);
   CREATE INDEX monitor_runs_kind ON monitor_runs(kind,observedAt DESC,id DESC);
   CREATE TABLE monitor_observations(runId TEXT NOT NULL REFERENCES monitor_runs(id),sourceId TEXT NOT NULL REFERENCES monitor_sources(id),attemptAt INTEGER,successAt INTEGER,dataThrough INTEGER,outcome TEXT NOT NULL,coverage TEXT NOT NULL,errorCode TEXT,PRIMARY KEY(runId,sourceId));
   CREATE INDEX monitor_source_history ON monitor_observations(sourceId,attemptAt DESC,runId DESC);
   CREATE TABLE monitor_anomalies(id TEXT PRIMARY KEY,runId TEXT NOT NULL REFERENCES monitor_runs(id),sourceId TEXT REFERENCES monitor_sources(id),code TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'open',version INTEGER NOT NULL DEFAULT 0,createdAt INTEGER NOT NULL,updatedAt INTEGER NOT NULL,resolutionRunId TEXT REFERENCES monitor_runs(id));
   CREATE INDEX monitor_anomaly_order ON monitor_anomalies(updatedAt DESC,id DESC);
   CREATE INDEX monitor_anomaly_source ON monitor_anomalies(sourceId,state);
   CREATE TABLE monitor_receipts(id TEXT PRIMARY KEY,payloadHash TEXT NOT NULL,receivedAt INTEGER NOT NULL);
  `);this.db.prepare('INSERT INTO admin_schema_migrations VALUES(5,?)').run(admin.accounts.now());
 });}
 // Only the offline operator CLI calls import. No browser collector, path, URL or command execution.
 ingest(value:unknown){const v=value as any;fields(v,['schemaVersion','batchId','sources','runs']);if(v.schemaVersion!==1||!Array.isArray(v.sources)||!Array.isArray(v.runs)||v.sources.length>500||v.runs.length>500||Buffer.byteLength(JSON.stringify(v))>4*1024*1024)throw bad('采集包超限或版本无效');id(v.batchId);
 const sources=v.sources.map((s:any)=>{fields(s,['id','name','platform','kind','budgetHours']);if(!Number.isInteger(s.budgetHours)||s.budgetHours<1||s.budgetHours>720)throw bad('新鲜度预算无效');return {id:id(s.id),name:text(s.name),platform:text(s.platform),kind:id(s.kind),budgetHours:s.budgetHours};});
 const runs=v.runs.map((r:any)=>{fields(r,['id','kind','trigger','state','stage','startedAt','finishedAt','observedAt','inputVersion','outputVersion','result','validation','publication','errorCode','runLink','sources']);if(!Array.isArray(r.sources)||r.sources.length>500)throw bad('信源记录超限');const start=stamp(r.startedAt),end=stamp(r.finishedAt),observed=stamp(r.observedAt);if(observed===null||(start!==null&&end!==null&&end<start)||observed>this.admin.accounts.now()+300000)throw bad('记录时间顺序无效');const normalized={id:id(r.id),kind:id(r.kind),trigger:enumValue(r.trigger,['schedule','manual','workflow','worker','unknown']),state:enumValue(r.state,states),stage:id(r.stage),startedAt:start,finishedAt:end,observedAt:observed,inputVersion:r.inputVersion===null?null:id(r.inputVersion),outputVersion:r.outputVersion===null?null:id(r.outputVersion),result:enumValue(r.result,results),validation:enumValue(r.validation,['passed','failed','not_run','unknown']),publication:enumValue(r.publication,['completed','failed','not_run','unknown']),errorCode:r.errorCode===null?null:enumValue(r.errorCode,errors),runLink:workflowLink(r.runLink),sources:r.sources.map((s:any)=>{fields(s,['sourceId','attemptAt','successAt','dataThrough','outcome','coverage','errorCode']);return {sourceId:id(s.sourceId),attemptAt:stamp(s.attemptAt),successAt:stamp(s.successAt),dataThrough:stamp(s.dataThrough),outcome:enumValue(s.outcome,['success','unchanged','fetch_failed','parse_failed','failed','not_run','unknown']),coverage:enumValue(s.coverage,['full','partial','missing','unknown']),errorCode:s.errorCode===null?null:enumValue(s.errorCode,errors)};})};
 if(['succeeded','failed','cancelled'].includes(normalized.state)&&end===null&&start!==null)throw bad('终态缺少结束时间');if(normalized.publication==='completed'&&(normalized.state!=='succeeded'||normalized.result!=='success'))throw bad('发布完成必须有成功执行记录');return normalized;});
 if(runs.some((r:any)=>r.sources.some((s:any)=>[s.attemptAt,s.successAt,s.dataThrough].some(t=>t!==null&&t>this.admin.accounts.now()+300000))))throw bad('来源记录时间超前');
 if(new Set(sources.map((s:any)=>s.id)).size!==sources.length||new Set(runs.map((r:any)=>r.id)).size!==runs.length||runs.some((r:any)=>new Set(r.sources.map((s:any)=>s.sourceId)).size!==r.sources.length))throw bad('采集包含重复对象');
 const payloadHash=hash(JSON.stringify({sources,runs}));return this.admin.accounts.transaction(()=>{const prior=this.db.prepare('SELECT payloadHash FROM monitor_receipts WHERE id=?').get(v.batchId);if(prior){if(prior.payloadHash!==payloadHash)throw bad('同一采集包内容变化','idempotency_conflict',409);return {imported:0,duplicate:true};}
 for(const s of sources)this.db.prepare('INSERT INTO monitor_sources VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,platform=excluded.platform,kind=excluded.kind,budgetHours=excluded.budgetHours').run(s.id,s.name,s.platform,s.kind,s.budgetHours);
 let imported=0;for(const r of runs){const h=hash(JSON.stringify(r)),priorRun=this.db.prepare('SELECT payloadHash FROM monitor_runs WHERE id=?').get(r.id);if(priorRun){if(priorRun.payloadHash!==h)throw bad('同一运行内容变化','idempotency_conflict',409);continue;}
 this.db.prepare('INSERT INTO monitor_runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(r.id,r.kind,r.trigger,r.state,r.stage,r.startedAt,r.finishedAt,r.observedAt,r.inputVersion,r.outputVersion,r.result,r.validation,r.publication,r.errorCode,r.runLink,h,this.admin.accounts.now());imported++;
 for(const s of r.sources){if(!this.db.prepare('SELECT 1 FROM monitor_sources WHERE id=?').get(s.sourceId))throw bad('信源未注册');this.db.prepare('INSERT INTO monitor_observations VALUES(?,?,?,?,?,?,?,?)').run(r.id,s.sourceId,s.attemptAt,s.successAt,s.dataThrough,s.outcome,s.coverage,s.errorCode);if(['fetch_failed','parse_failed','failed'].includes(s.outcome)||['partial','missing'].includes(s.coverage))this.anomaly(r.id,s.sourceId,s.errorCode??'coverage_missing',r.observedAt);}
 if(r.state==='failed'||r.state==='needs_review'||r.validation==='failed'||r.publication==='failed')this.anomaly(r.id,null,r.errorCode??(r.validation==='failed'?'validation_failed':'execution_failed'),r.observedAt);
 }
 this.db.prepare('INSERT INTO monitor_receipts VALUES(?,?,?)').run(v.batchId,payloadHash,this.admin.accounts.now());return {imported,duplicate:false};});
 }
 private anomaly(runId:string,sourceId:string|null,code:string,at:number){const key='anomaly_'+hash(runId+':'+sourceId+':'+code).slice(0,40);this.db.prepare('INSERT OR IGNORE INTO monitor_anomalies(id,runId,sourceId,code,createdAt,updatedAt) VALUES(?,?,?,?,?,?)').run(key,runId,sourceId,code,at,at);}
 private runSql(){let base='SELECT * FROM monitor_runs';if(this.db.prepare("SELECT 1 FROM sqlite_master WHERE name='diagnostic_runs'").get())base+=` UNION ALL SELECT 'diagnostic_'||e.id AS id,'diagnostic' AS kind,'worker' AS trigger,e.state,'diagnose' AS stage,e.startedAt,e.finishedAt,e.createdAt AS observedAt,e.inputHash AS inputVersion,NULL AS outputVersion,CASE e.state WHEN 'succeeded' THEN 'success' WHEN 'failed' THEN 'failed' ELSE 'unknown' END AS result,'unknown' AS validation,'not_run' AS publication,CASE WHEN e.errorCode IS NOT NULL THEN 'unknown' ELSE NULL END AS errorCode,NULL AS runLink,'' AS payloadHash,e.createdAt AS receivedAt FROM diagnostic_runs e`;if(!this.db.prepare("SELECT 1 FROM sqlite_master WHERE name='editorial_runs'").get())return base;
 return base+` UNION ALL SELECT 'editorial_'||e.id AS id,'editorial' AS kind,'worker' AS trigger,e.state,e.stage,e.startedAt,e.finishedAt,e.createdAt AS observedAt,e.inputHash AS inputVersion,(SELECT outputHash FROM editorial_revisions WHERE runId=e.id LIMIT 1) AS outputVersion,CASE e.state WHEN 'succeeded' THEN 'success' WHEN 'failed' THEN 'failed' ELSE 'unknown' END AS result,CASE WHEN e.stage='verify' AND e.state='succeeded' THEN 'passed' ELSE 'unknown' END AS validation,'not_run' AS publication,CASE WHEN e.errorCode IS NOT NULL THEN 'unknown' ELSE NULL END AS errorCode,NULL AS runLink,'' AS payloadHash,e.createdAt AS receivedAt FROM editorial_runs e`;
 }
 run(id:string){const row=this.db.prepare('SELECT * FROM ('+this.runSql()+') WHERE id=?').get(id);if(!row)throw bad('运行不存在','not_found',404);return row;}
 sources(params:URLSearchParams){query(params,['platform','health']);if(params.has('cursor'))throw bad('信源列表不接受游标');const platform=params.get('platform');const rows=this.db.prepare('SELECT * FROM monitor_sources WHERE (? IS NULL OR platform=?) ORDER BY id LIMIT 501').all(platform,platform);const health=params.get('health');if(health&&!['unknown','normal','degraded','stale','not_run'].includes(health))throw bad('健康筛选无效');const items=rows.slice(0,500).map(s=>{
 const history=this.db.prepare(`SELECT o.*,r.observedAt,r.runLink FROM monitor_observations o JOIN monitor_runs r ON r.id=o.runId WHERE sourceId=? ORDER BY r.observedAt DESC,r.id DESC LIMIT 501`).all(String(s.id));const latest=history[0];const attempted=history.filter(o=>o.attemptAt!==null&&o.outcome!=='not_run').sort((a,b)=>Number(b.attemptAt)-Number(a.attemptAt));let consecutiveFailures:number|null=attempted.length?0:null;for(const o of attempted){if(!['failed','fetch_failed','parse_failed'].includes(String(o.outcome)))break;consecutiveFailures=(consecutiveFailures??0)+1;}
 const timestamps=this.db.prepare('SELECT max(attemptAt) AS attempt,max(successAt) AS success,max(dataThrough) AS through FROM monitor_observations WHERE sourceId=?').get(String(s.id))!;const success=timestamps.success??null,through=timestamps.through??null;const freshness=success===null?'unknown':this.admin.accounts.now()-Number(success)>Number(s.budgetHours)*3600000?'stale':'fresh';const currentHealth=!latest?'unknown':latest.outcome==='not_run'?'not_run':['failed','fetch_failed','parse_failed'].includes(String(latest.outcome))||['partial','missing'].includes(String(latest.coverage))?'degraded':freshness==='stale'?'stale':freshness==='unknown'||latest.outcome==='unknown'?'unknown':'normal';return {...s,latestAttemptAt:timestamps.attempt??null,latestSuccessAt:success,dataThrough:through,consecutiveFailures,failureCountTruncated:history.length>500,health:currentHealth,freshness,coverage:latest?.coverage??'unknown',outcome:latest?.outcome??'unknown',errorSummary:errorSummary(latest?.errorCode??null),runId:latest?.runId??null,runLink:latest?.runLink??null};});return {items:items.filter(s=>!health||s.health===health),truncated:rows.length>500,asOf:this.admin.accounts.now()};}
 runs(params:URLSearchParams){query(params,['kind','state','sourceId','runId']);const where:string[]=[],args:string[]=[];for(const k of ['kind','state'])if(params.has(k)){where.push(`r.${k}=?`);args.push(params.get(k)!);}if(params.has('runId')){where.push('r.id=?');args.push(params.get('runId')!);}if(params.has('sourceId')){where.push('EXISTS(SELECT 1 FROM monitor_observations o WHERE o.runId=r.id AND o.sourceId=?)');args.push(params.get('sourceId')!);}return page(this.admin,params,'monitor-runs','SELECT r.* FROM ('+this.runSql()+') r'+(where.length?' WHERE '+where.join(' AND '):''),args,['observedAt','id'],r=>this.projectRun(r));}
 projectRun(r:any){const {payloadHash,receivedAt,errorCode,...safe}=r;return {...safe,errorSummary:errorSummary(errorCode),sources:this.db.prepare('SELECT sourceId,outcome,coverage FROM monitor_observations WHERE runId=? ORDER BY sourceId').all(r.id),retryAvailable:false,operation:r.kind==='diagnostic'?'进入问题工作台核查；诊断结果仅为建议，不是验证或解决依据。':r.kind==='editorial'?'进入周报工作台核查并使用T03已有阶段动作。':'在受控终端核对原运行，按现有恢复协议操作；抓取恢复不触发发布。'};}
 anomalies(params:URLSearchParams){query(params,['state','sourceId']);const where:string[]=[],args:string[]=[];for(const k of ['state','sourceId'])if(params.has(k)){where.push(`${k}=?`);args.push(params.get(k)!);}return page(this.admin,params,'monitor-anomalies','SELECT * FROM monitor_anomalies'+(where.length?' WHERE '+where.join(' AND '):''),args,['updatedAt','id'],r=>({...r,summary:errorSummary(r.code)}));}
 anomalyVersion(id:string){const r=this.db.prepare('SELECT version FROM monitor_anomalies WHERE id=?').get(id);if(!r)throw bad('异常不存在','not_found',404);return Number(r.version);}
 update(c:AdminCommand){const state=enumValue(c.input.state,['acknowledged','in_progress','ignored','resolved']),resolution=c.input.resolutionRunId===null||c.input.resolutionRunId===undefined?null:id(c.input.resolutionRunId);
 return this.admin.command(c,['state','version','resolutionRunId'],['id','state','version','resolutionRunId'],()=>{const issue=this.db.prepare('SELECT * FROM monitor_anomalies WHERE id=?').get(c.targetId)!;if(state==='resolved'){if(!resolution)throw bad('解决需关联后续成功运行或核验');const r=this.run(resolution),original=this.run(String(issue.runId));if(Number(r.observedAt)<=Number(original.observedAt)||r.state!=='succeeded'||(!issue.sourceId&&r.kind!==original.kind))throw bad('核验必须在异常之后且执行成功');if(issue.sourceId){const s=this.db.prepare('SELECT * FROM monitor_observations WHERE runId=? AND sourceId=?').get(resolution,issue.sourceId);if(!s||!['success','unchanged'].includes(String(s.outcome))||s.coverage!=='full'||s.successAt===null||Number(s.successAt)<=Number(original.observedAt))throw bad('核验未证明关联来源恢复');}else if(issue.code==='validation_failed'?r.validation!=='passed':original.publication==='failed'?r.publication!=='completed':r.kind!==original.kind||!['success','unchanged'].includes(String(r.result)))throw bad('核验未证明原任务恢复');}else if(resolution)throw bad('仅解决可关联核验');const version=Number(issue.version)+1;this.db.prepare('UPDATE monitor_anomalies SET state=?,version=?,updatedAt=?,resolutionRunId=? WHERE id=?').run(state,version,this.admin.accounts.now(),resolution,c.targetId);return {result:{id:c.targetId,state,version,resolutionRunId:resolution},before:{state:issue.state,version:issue.version,resolutionRunId:issue.resolutionRunId},after:{state,version,resolutionRunId:resolution}};});}
}
