import path from 'node:path';
import { AccountError, hash } from './account-store.js';
import { AdminStore, type AdminCommand, timestamp } from './admin-store.js';
import { query,page } from './admin-operations.js';
import { ProStore } from './pro-store.js';
import { MailLedger, type MailKind } from './mail-ledger.js';
const bad=(s:string)=>new AccountError(400,'invalid_parameter',s);
export class AdminDelivery {
 readonly ledger;readonly pro;readonly db;
 constructor(readonly admin:AdminStore){this.pro=new ProStore(admin.accounts);this.ledger=new MailLedger(admin.accounts);this.db=admin.db;admin.accounts.transaction(()=>{this.db.exec(`CREATE TABLE IF NOT EXISTS service_checks(id TEXT PRIMARY KEY,kind TEXT NOT NULL,status TEXT NOT NULL,checkedAt INTEGER NOT NULL,budgetSeconds INTEGER NOT NULL,source TEXT NOT NULL,value TEXT,payloadHash TEXT NOT NULL);CREATE INDEX IF NOT EXISTS service_checks_latest ON service_checks(kind,checkedAt DESC,id DESC);`);this.db.prepare('INSERT OR IGNORE INTO admin_schema_migrations VALUES(6,?)').run(admin.accounts.now());});}
 parse(id:string){const m=/^(digest|pro):([a-zA-Z0-9_-]{1,200})$/.exec(id);if(!m)throw bad('投递标识无效');return {kind:m[1] as MailKind,jobId:m[2]!};}
 row(id:string){const k=this.parse(id),r=this.db.prepare(`SELECT j.id,j.userId,j.created,j.lease,j.status,${k.kind==='pro'?'j.reportId':'NULL AS reportId'},u.email FROM ${this.ledger.table(k.kind)} j JOIN users u ON u.id=j.userId WHERE j.id=?`).get(k.jobId);if(!r)throw new AccountError(404,'not_found','投递不存在');return {...r,...k};}
 version(id:string){const r=this.row(id);return Number(this.db.prepare('SELECT version FROM mail_delivery WHERE kind=? AND jobId=?').get(r.kind,r.jobId)?.version??0);}
 eligible(kind:MailKind,userId:string){if(kind==='pro')return this.pro.entitlement(userId).status==='active'&&!!this.pro.settings(userId)?.emailEnabled;return !!this.db.prepare('SELECT 1 FROM users WHERE id=? AND emailEnabled=1').get(userId);}
 project(r:any){const d=this.db.prepare('SELECT provider,messageId,eventAt,version FROM mail_delivery WHERE kind=? AND jobId=?').get(r.kind,r.jobId),state=this.ledger.state(r.kind,r.jobId),retryAvailable=state==='failed'&&!d?.messageId&&!!this.db.prepare("SELECT 1 FROM mail_attempts WHERE kind=? AND jobId=? AND outcome='failed' AND error='provider_rejected' ORDER BY startedAt DESC LIMIT 1").get(r.kind,r.jobId)&&this.eligible(r.kind,r.userId);return {id:r.kind+':'+r.jobId,type:r.kind,userId:r.userId,email:r.email,queuedAt:r.created,reportId:r.reportId,state,version:Number(d?.version??0),provider:d?.provider??null,messageId:d?.messageId??null,eventAt:d?.eventAt??null,retryAvailable,reconcileAvailable:['unknown','accepted','failed'].includes(state),leaseUntil:r.lease||null};}
 list(params:URLSearchParams){query(params,['type','state','from','to','user']);const values:(string|number)[]=[],where:string[]=[];if(params.has('type')){if(!['digest','pro'].includes(params.get('type')!))throw bad('类型无效');where.push('kind=?');values.push(params.get('type')!);}if(params.has('user')){const u=params.get('user')!;if(!u||u.length>254)throw bad('用户筛选无效');where.push('(userId=? OR instr(lower(email),lower(?))>0)');values.push(u,u);}for(const k of ['from','to'])if(params.has(k)){where.push(`created${k==='from'?'>=':'<='}?`);values.push(timestamp(params.get(k)!));}if(params.has('from')&&params.has('to')&&timestamp(params.get('from')!)>timestamp(params.get('to')!))throw bad('时间范围无效');
 const base=`SELECT 'digest' kind,j.id jobId,j.userId,j.created,j.lease,j.status,NULL reportId,u.email FROM mail_jobs j JOIN users u ON u.id=j.userId UNION ALL SELECT 'pro',j.id,j.userId,j.created,j.lease,j.status,j.reportId,u.email FROM pro_mail j JOIN users u ON u.id=j.userId`;
 const sql=`SELECT r.*,r.kind||':'||r.jobId id,CASE WHEN r.status='cancelled' AND d.state IS NULL AND r.lease>0 THEN 'unknown' WHEN r.status='cancelled' AND (d.state IS NULL OR d.state IN ('queued','failed','cancelled')) THEN 'cancelled' WHEN d.state='sending' AND r.lease<=${this.admin.accounts.now()} THEN 'unknown' WHEN d.state IS NOT NULL THEN d.state WHEN r.status='sent' THEN 'accepted' WHEN r.status='review' THEN 'unknown' WHEN r.lease>0 THEN CASE WHEN r.lease>${this.admin.accounts.now()} THEN 'sending' ELSE 'unknown' END ELSE 'queued' END state FROM (${base}) r LEFT JOIN mail_delivery d ON d.kind=r.kind AND d.jobId=r.jobId`;
 if(params.has('state')){if(!['queued','sending','accepted','delivered','failed','unknown','cancelled'].includes(params.get('state')!))throw bad('状态无效');where.push('state=?');values.push(params.get('state')!);}return page(this.admin,params,'delivery',`SELECT * FROM (${sql}) ${where.length?'WHERE '+where.join(' AND '):''}`,values,['created','id'],r=>this.project(r));}
 detail(id:string){const r=this.row(id);return {...this.project(r),digestItems:r.kind==='digest'?this.db.prepare('SELECT eventKey FROM mail_items WHERE jobId=? ORDER BY eventKey LIMIT 101').all(r.jobId):null,attempts:this.db.prepare('SELECT id,startedAt,finishedAt,lease,outcome,error,provider,messageId FROM mail_attempts WHERE kind=? AND jobId=? ORDER BY startedAt DESC,id DESC LIMIT 100').all(r.kind,r.jobId),evidence:this.db.prepare('SELECT id,provider,messageId,state,eventAt,receivedAt,timeBasis FROM mail_evidence WHERE kind=? AND jobId=? ORDER BY eventAt DESC,id DESC LIMIT 100').all(r.kind,r.jobId),operation:'未知或review须先由受控投递CLI核对供应商，再核对已保存证据。无消息ID无法查询，不得重置。重试仅重新入队同任务，同幂等键；发送前再次检查权益与偏好。'};}
 write(c:AdminCommand,operation:string){return this.admin.command(c,['state','version'],['id','state','version'],()=>{const r=this.row(c.targetId),before={state:this.ledger.state(r.kind,r.jobId),version:this.version(c.targetId)};let state=before.state;
 if(operation==='retry'){if(!this.project(r).retryAvailable)throw bad('无确认未接受的失败证据，或当前偏好/权益不允许重试');this.db.prepare(`UPDATE ${this.ledger.table(r.kind)} SET status='pending',lease=0 WHERE id=?`).run(r.jobId);state='queued';}
 else {if(!['unknown','accepted','failed'].includes(state))throw bad('当前投递不能核对');const e=this.db.prepare('SELECT * FROM mail_evidence WHERE kind=? AND jobId=? ORDER BY CASE state WHEN \'delivered\' THEN 1 ELSE 0 END DESC,eventAt DESC,CASE state WHEN \'delivered\' THEN 3 WHEN \'failed\' THEN 2 WHEN \'accepted\' THEN 1 ELSE 0 END DESC,id DESC LIMIT 1').get(r.kind,r.jobId);if(!e)throw bad('尚无已验证供应商证据，请在受控终端核查');const d=this.db.prepare('SELECT * FROM mail_delivery WHERE kind=? AND jobId=?').get(r.kind,r.jobId);if(d?.messageId&&d.messageId!==e.messageId)throw bad('消息标识不一致');// Attempt completion is an observation, not a provider event clock; do not compare them.
state=String(e.state);this.db.prepare(`UPDATE ${this.ledger.table(r.kind)} SET status=?,lease=0 WHERE id=?`).run(['accepted','delivered'].includes(state)?'sent':'review',r.jobId);this.db.prepare('INSERT INTO mail_delivery(kind,jobId,state,provider,messageId,eventAt) VALUES(?,?,?,?,?,?) ON CONFLICT(kind,jobId) DO UPDATE SET provider=excluded.provider,messageId=excluded.messageId,eventAt=excluded.eventAt').run(r.kind,r.jobId,state,e.provider!,e.messageId!,e.eventAt!);}
 const version=before.version+1;this.db.prepare('INSERT INTO mail_delivery(kind,jobId,state,version) VALUES(?,?,?,?) ON CONFLICT(kind,jobId) DO UPDATE SET state=excluded.state,version=excluded.version').run(r.kind,r.jobId,state,version);return {result:{id:c.targetId,state,version},before,after:{state,version}};});}
 // Called only by a trusted operator CLI after authenticating the source. Never an HTTP ingest.
 evidence(v:any){if(!v||Object.keys(v).sort().join(',')!=='eventAt,id,job,messageId,provider,state,timeBasis'||!['event','query'].includes(v.timeBasis)||!['accepted','delivered','failed','unknown'].includes(v.state)||!['resend','local'].includes(v.provider)||typeof v.id!=='string'||!/^[\w:-]{1,200}$/.test(v.id)||typeof v.messageId!=='string'||!/^[\w-]{1,128}$/.test(v.messageId)||!Number.isSafeInteger(v.eventAt)||v.eventAt<0||v.eventAt>this.admin.accounts.now()+300000)throw bad('证据格式无效');const r=this.row(v.job),d=this.db.prepare('SELECT provider,messageId FROM mail_delivery WHERE kind=? AND jobId=?').get(r.kind,r.jobId);if(!d?.messageId||d.messageId!==v.messageId||d.provider!==v.provider)throw bad('证据未匹配已保存的供应商消息');return this.admin.accounts.transaction(()=>{const prior=this.db.prepare('SELECT * FROM mail_evidence WHERE id=?').get(v.id);if(prior){if(prior.kind!==r.kind||prior.jobId!==r.jobId||prior.messageId!==v.messageId||prior.state!==v.state||prior.eventAt!==v.eventAt||prior.provider!==v.provider||prior.timeBasis!==v.timeBasis)throw new AccountError(409,'idempotency_conflict','证据ID冲突');return {duplicate:true};}this.db.prepare('INSERT INTO mail_evidence VALUES(?,?,?,?,?,?,?,?,?)').run(v.id,r.kind,r.jobId,v.provider,v.messageId,v.state,v.eventAt,this.admin.accounts.now(),v.timeBasis);return {duplicate:false};});}
 healthImport(v:any){if(!v||Object.keys(v).sort().join(',')!=='budgetSeconds,checkedAt,id,kind,source,status,value'||!['api','mail','release','backup','restore'].includes(v.kind)||!['normal','abnormal','unknown'].includes(v.status)||!Number.isSafeInteger(v.checkedAt)||v.checkedAt<0||v.checkedAt>this.admin.accounts.now()+300000||!Number.isInteger(v.budgetSeconds)||v.budgetSeconds<60||v.budgetSeconds>2592000||typeof v.id!=='string'||!/^[\w:-]{1,200}$/.test(v.id)||!['account-maintenance.backup','account-maintenance.restore','account-maintenance.health','release.status','release.verify','mail.adapter'].includes(v.source)||!(v.value===null||typeof v.value==='string'&&/^[\w .:-]{1,200}$/.test(v.value)))throw bad('健康记录无效');const allowed:Record<string,string[]>= {api:['account-maintenance.health'],mail:['mail.adapter'],release:['release.status','release.verify'],backup:['account-maintenance.backup'],restore:['account-maintenance.restore']};if(!allowed[v.kind]!.includes(v.source))throw bad('来源与检查项不匹配');const h=hash(JSON.stringify(Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]]))));return this.admin.accounts.transaction(()=>{const p=this.db.prepare('SELECT payloadHash FROM service_checks WHERE id=?').get(v.id);if(p&&p.payloadHash!==h)throw new AccountError(409,'idempotency_conflict','健康记录冲突');this.db.prepare('INSERT OR IGNORE INTO service_checks VALUES(?,?,?,?,?,?,?,?)').run(v.id,v.kind,v.status,v.checkedAt,v.budgetSeconds,v.source,v.value,h);return {duplicate:!!p};});}
 health(holder:any){const now=this.admin.accounts.now();const items:any[]=['api','mail','release','backup','restore'].map(kind=>{const r=this.db.prepare('SELECT id,status,checkedAt,budgetSeconds,source,value FROM service_checks WHERE kind=? ORDER BY checkedAt DESC,id DESC LIMIT 1').get(kind);return {kind,...(r??{checkedAt:null,source:'尚未接入',value:null}),status:r&&now-Number(r.checkedAt)<=Number(r.budgetSeconds)*1000?r.status:'unknown',lastStatus:r?.status??null,stale:r?now-Number(r.checkedAt)>Number(r.budgetSeconds)*1000:false};});const latest=this.db.prepare('SELECT observedAt,state,result FROM monitor_runs ORDER BY observedAt DESC,id DESC LIMIT 1').get();items.push({kind:'collection',checkedAt:latest?.observedAt??null,source:'T05 monitor_runs',value:latest?String(latest.state)+' / '+String(latest.result):null,status:!latest||now-Number(latest.observedAt)>48*3600000?'unknown':latest.state==='failed'||latest.state==='needs_review'||latest.result==='partial'?'abnormal':latest.state==='succeeded'&&['success','unchanged'].includes(String(latest.result))?'normal':'unknown',stale:!!latest&&now-Number(latest.observedAt)>48*3600000});const runtimeRelease=path.basename(process.env.MAAS_RELEASE_DIR??'');items.push({kind:'release_runtime',checkedAt:now,source:'当前API启动MAAS_RELEASE_DIR（无文件读取）',value:/^rl_[a-f0-9]{10}_[a-f0-9]{12}$/.test(runtimeRelease)?runtimeRelease:null,status:/^rl_[a-f0-9]{10}_[a-f0-9]{12}$/.test(runtimeRelease)?'normal':'unknown',stale:false});items.push({kind:'api_runtime',checkedAt:now,source:'当前鉴权API + SQLite SELECT 1',value:'当前请求可用',status:this.db.prepare('SELECT 1').get()?'normal':'abnormal',stale:false});items.push({kind:'data',checkedAt:now,source:'当前DatasetHolder（重载错误只显示状态）',value:holder.current?.version??null,status:holder.current&&!holder.lastReloadError?'normal':'abnormal',stale:false});return {asOf:now,items,operation:'重启、生产回滚、备份恢复均在受控运维终端执行既有ops流程。备份与恢复记录独立；无实际恢复核验不能声称可恢复。'};}
}
