import { pathToFileURL } from 'node:url';
import { AccountStore } from './account-store.js';
import { AdminStore } from './admin-store.js';
import { AdminProblems, diagnosisSchema } from './admin-problems.js';
import { ModelTaskLease, boundedModelCall } from './model-task-runtime.js';
import { ModelFailure, MockModel, OpenAIModel, modelConfigSchema, type EditorialModel } from './editorial-model.js';
export class DiagnosticWorker {
 readonly lease:ModelTaskLease;
 constructor(readonly problems:AdminProblems,readonly adapter?:EditorialModel){this.lease=new ModelTaskLease(problems.admin,'diagnostic_runs');}
 async once(){const p=this.problems,db=p.db,now=()=>p.admin.accounts.now();this.lease.recover();const r=p.admin.accounts.transaction(()=>{
 const candidate=db.prepare("SELECT * FROM diagnostic_runs WHERE state='queued' AND availableAt<=? ORDER BY createdAt,id LIMIT 1").get(now());if(!candidate)return null;
 if(Number(db.prepare('SELECT coalesce(sum(attempt),0) n FROM diagnostic_runs WHERE problemId=?').get(String(candidate.problemId))!.n)>=30){db.prepare("UPDATE diagnostic_runs SET state='failed',errorCode='call_limit',version=version+1,finishedAt=? WHERE id=?").run(now(),String(candidate.id));return null;}
 db.prepare("UPDATE diagnostic_runs SET state='running',attempt=attempt+1,leaseOwner=?,leaseUntil=?,fencingVersion=fencingVersion+1,version=version+1,startedAt=? WHERE id=?").run(this.lease.owner,now()+300000,now(),String(candidate.id));return p.run(String(candidate.id));});if(!r)return false;
 const id=String(r.id),fence=Number(r.fencingVersion),cfg=modelConfigSchema.parse(JSON.parse(String(r.config))),input=p.modelInput(JSON.parse(String(r.payload))),timer=setInterval(()=>this.lease.heartbeat(id,fence),30000);timer.unref();
 const finish=(state:string,result:unknown,error:string|null)=>{if(!this.lease.active(id,fence))return;db.prepare('UPDATE diagnostic_runs SET state=?,result=?,errorCode=?,finishedAt=?,leaseUntil=0,version=version+1 WHERE id=?').run(state,result===null?null:JSON.stringify(result),error,now(),id);};
 try{const output=await boundedModelCall(this.adapter??(cfg.adapter==='mock'?new MockModel():new OpenAIModel()),input,cfg);
 p.admin.accounts.transaction(()=>{const current=p.run(id),usage=JSON.parse(String(current.usage));usage.push({attempt:r.attempt,inputTokens:output.inputTokens,outputTokens:output.outputTokens,actualCost:output.actualCost,requestId:output.requestId,adapter:cfg.adapter});db.prepare('UPDATE diagnostic_runs SET usage=?,actualCost=? WHERE id=?').run(JSON.stringify(usage),output.actualCost===null?current.actualCost??null:Number(current.actualCost??0)+output.actualCost,id);
 if(!this.lease.active(id,fence))return;if(output.inputTokens>cfg.maxInputTokens||output.outputTokens>cfg.maxOutputTokens){finish('failed',null,'token_limit');return;}const parsed=diagnosisSchema.safeParse(output.output);if(!parsed.success){finish('needs_review',null,'invalid_diagnosis_schema');return;}
 const sources=new Set(['description','reproduction','versions','errorSummary',...(input.diagnostic as any).screenshotSources]);if(parsed.data.facts.some(f=>!sources.has(f.source))||parsed.data.possibleCauses.some(c=>c.evidence.some(s=>!sources.has(s)))){finish('needs_review',null,'unknown_source');return;}finish('succeeded',{...parsed.data,advisoryOnly:true},null);});
 }catch(e){const failure=e instanceof ModelFailure?e:new ModelFailure('invalid_output');p.admin.accounts.transaction(()=>{if(!this.lease.active(id,fence))return;const current=p.run(id),usage=JSON.parse(String(current.usage));usage.push({attempt:current.attempt,error:failure.code,uncertain:failure.uncertain,actualCost:null,at:now()});db.prepare('UPDATE diagnostic_runs SET usage=? WHERE id=?').run(JSON.stringify(usage),id);if(failure.retryable&&Number(current.attempt)<3)db.prepare("UPDATE diagnostic_runs SET state='queued',leaseUntil=0,version=version+1,errorCode=?,availableAt=? WHERE id=?").run(failure.code,now()+2**Number(current.attempt)*1000,id);else finish(failure.uncertain?'needs_review':'failed',null,failure.code);});}finally{clearInterval(timer);}return true;
 }
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){if(!process.env.MAAS_ACCOUNT_DB)throw Error('MAAS_ACCOUNT_DB required');const accounts=new AccountStore(process.env.MAAS_ACCOUNT_DB),worker=new DiagnosticWorker(new AdminProblems(new AdminStore(accounts)));let stopped=false;process.on('SIGINT',()=>{stopped=true;});process.on('SIGTERM',()=>{stopped=true;});try{do{const worked=await worker.once();if(process.argv.includes('--once'))break;if(!worked&&!stopped)await new Promise(r=>setTimeout(r,1000));}while(!stopped);}finally{accounts.close();}}
