import type { AccountStore } from './account-store.js';
import { randomUUID } from 'node:crypto';
import type { Mail, Mailer, MailAcceptance } from './account-mail.js';
export type MailKind='digest'|'pro';
export class MailLedger {
 readonly db;
 constructor(readonly accounts:AccountStore){this.db=accounts.db;accounts.transaction(()=>this.db.exec(`
 CREATE TABLE IF NOT EXISTS mail_delivery(kind TEXT NOT NULL,jobId TEXT NOT NULL,state TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 0,provider TEXT,messageId TEXT,eventAt INTEGER,PRIMARY KEY(kind,jobId));
 CREATE TABLE IF NOT EXISTS mail_attempts(id TEXT PRIMARY KEY,kind TEXT NOT NULL,jobId TEXT NOT NULL,startedAt INTEGER NOT NULL,finishedAt INTEGER,lease INTEGER NOT NULL,outcome TEXT NOT NULL,error TEXT,provider TEXT,messageId TEXT);
 CREATE INDEX IF NOT EXISTS mail_attempts_job ON mail_attempts(kind,jobId,startedAt DESC);
 CREATE TABLE IF NOT EXISTS mail_evidence(id TEXT PRIMARY KEY,kind TEXT NOT NULL,jobId TEXT NOT NULL,provider TEXT NOT NULL,messageId TEXT NOT NULL,state TEXT NOT NULL,eventAt INTEGER NOT NULL,receivedAt INTEGER NOT NULL,timeBasis TEXT NOT NULL);
 `));}
 table(kind:MailKind){return kind==='digest'?'mail_jobs':'pro_mail';}
 state(kind:MailKind,id:string){const j=this.db.prepare(`SELECT status,lease FROM ${this.table(kind)} WHERE id=?`).get(id)!;const d=this.db.prepare('SELECT * FROM mail_delivery WHERE kind=? AND jobId=?').get(kind,id);if(j.status==='cancelled'&&!d&&Number(j.lease)>0)return 'unknown';if(j.status==='cancelled'&&(!d||['queued','failed','cancelled'].includes(String(d.state))))return 'cancelled';if(d){if(d.state==='sending'&&Number(j.lease)<=this.accounts.now())return 'unknown';return String(d.state);}return j.status==='sent'?'accepted':j.status==='review'||Number(j.lease)>0?(Number(j.lease)>this.accounts.now()&&j.status==='pending'?'sending':'unknown'):'queued';}
 begin(kind:MailKind,id:string,lease:number){const attempt=randomUUID();this.db.prepare(`INSERT INTO mail_delivery(kind,jobId,state) VALUES(?,?,'sending') ON CONFLICT(kind,jobId) DO UPDATE SET state='sending',version=version+1`).run(kind,id);this.db.prepare("INSERT INTO mail_attempts VALUES(?,?,?,?,NULL,?,'sending',NULL,NULL,NULL)").run(attempt,kind,id,this.accounts.now(),lease);return attempt;}
 async send(kind:MailKind,id:string,lease:number,attempt:string,mailer:Mailer,mail:Mail){try{const j=this.db.prepare(`SELECT lease,status FROM ${this.table(kind)} WHERE id=?`).get(id);if(!j||Number(j.lease)!==lease||j.status!=='pending'||lease<=this.accounts.now()){this.finish(kind,id,lease,attempt,j?.status==='cancelled'?'cancelled':'unknown',undefined,'lease_or_preference_changed');return;}const result=await mailer.send(mail);this.finish(kind,id,lease,attempt,'accepted',result);}catch(e){this.finish(kind,id,lease,attempt,e instanceof MailSendError&&e.notAccepted?'failed':'unknown',{provider:mailer.provider},e instanceof MailSendError&&['provider_rejected','invalid_acceptance'].includes(e.reason)?e.reason:'timeout_or_unknown');}}
 finish(kind:MailKind,id:string,lease:number,attempt:string,state:string,result?:void|Partial<MailAcceptance>,error:string|null=null){this.accounts.transaction(()=>{this.db.prepare('UPDATE mail_attempts SET finishedAt=?,outcome=?,error=?,provider=?,messageId=? WHERE id=?').run(this.accounts.now(),state,error,result?.provider??null,result?.messageId??null,attempt);const j=this.db.prepare(`SELECT lease,status FROM ${this.table(kind)} WHERE id=?`).get(id);if(!j||Number(j.lease)!==lease||!['pending','review','cancelled'].includes(String(j.status)))return;this.db.prepare(`UPDATE ${this.table(kind)} SET status=?,lease=0 WHERE id=?`).run(state==='accepted'?'sent':state==='cancelled'?'cancelled':'review',id);this.db.prepare('UPDATE mail_delivery SET state=?,provider=?,messageId=?,eventAt=?,version=version+1 WHERE kind=? AND jobId=?').run(state,result?.provider??null,result?.messageId??null,this.accounts.now(),kind,id);});}
}
export class MailSendError extends Error{constructor(readonly reason:string,readonly notAccepted=false){super(reason);}}
