import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {PaymentStore,checkedMinorTotal} from './payment-store.js';
import {AccountError} from './account-store.js';
const record=z.object({kind:z.enum(['paid','refund','fee','settlement']),objectId:z.string().min(1).max(200),amount:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),currency:z.string().regex(/^[A-Z]{3}$/),occurredAt:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER)}).strict();
export function reconcilePayments(store:PaymentStore,input:unknown){const p=z.object({currency:z.string().regex(/^[A-Z]{3}$/),from:z.number().int().nonnegative(),to:z.number().int().nonnegative(),source:z.string().min(1).max(500),records:z.array(record).max(10000)}).strict().parse(input);if(p.from>=p.to||p.to-p.from>366*86400000)throw new AccountError(400,'invalid_range','对账时间范围无效');const unique=new Set<string>();for(const r of p.records){if(r.currency!==p.currency||r.occurredAt<p.from||r.occurredAt>=p.to||unique.has(r.kind+':'+r.objectId))throw new AccountError(400,'invalid_reconciliation','供应商记录币种/范围/标识冲突');unique.add(r.kind+':'+r.objectId);}
 return store.admin.accounts.transaction(()=>{const db=store.db,id=randomUUID();db.prepare('INSERT INTO paid_reconciliations VALUES(?,?,?,?,?,?)').run(id,p.currency,p.from,p.to,p.source,store.admin.accounts.now());for(const r of p.records)db.prepare('INSERT INTO paid_provider_records VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),id,r.kind,r.objectId,r.amount,r.currency,r.occurredAt,p.source);
 const internal=db.prepare("SELECT kind,objectId,amount FROM paid_facts WHERE currency=? AND occurredAt>=? AND occurredAt<? AND kind IN ('paid','refund')").all(p.currency,p.from,p.to),expected=new Map(internal.map(r=>[String(r.kind)+':'+r.objectId,Number(r.amount)])),observed=new Map(p.records.filter(r=>r.kind==='paid'||r.kind==='refund').map(r=>[r.kind+':'+r.objectId,r.amount]));let differences=0;
 for(const key of new Set([...expected.keys(),...observed.keys()])){const e=expected.get(key)??null,o=observed.get(key)??null;if(e===o)continue;const index=key.indexOf(':');db.prepare('INSERT INTO paid_differences VALUES(?,?,?,?,?,?,?)').run(randomUUID(),id,key.slice(index+1),e===null?'missing_internal':o===null?'missing_provider':'amount_mismatch',e,o,p.source);differences++;}
 return {id,differences,currency:p.currency,source:p.source,fees:p.records.some(r=>r.kind==='fee')?p.records.filter(r=>r.kind==='fee').reduce((n,r)=>checkedMinorTotal(n+r.amount),0):null,settlement:p.records.some(r=>r.kind==='settlement')?p.records.filter(r=>r.kind==='settlement').reduce((n,r)=>checkedMinorTotal(n+r.amount),0):null};});
}
