import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import http from 'node:http';
import {AccountStore} from '../account-store.js';
import {AdminStore,type AdminCommand} from '../admin-store.js';
import {AdminMonitor} from '../admin-monitor.js';
import {AdminDelivery} from '../admin-delivery.js';
import {MailSendError} from '../mail-ledger.js';
import {importReceipt} from '../mail-receipt.js';
import {queryMail} from '../mail-query.js';
import {deliverPro} from '../pro-digest.js';
import {createAdminHandler} from '../admin-http.js';
import type {DatasetHolder} from '../dataset.js';
const now=Date.parse('2026-10-04T08:00:00Z'),secret='fixed-code-secret-for-local-only-tests';
function fixture(){let clock=now;const accounts=new AccountStore(':memory:',()=>clock,secret),admin=new AdminStore(accounts);new AdminMonitor(admin);const delivery=new AdminDelivery(admin);const u=accounts.verify('local@example.test',accounts.issueCode('local@example.test'));accounts.preferences(u.user.id,true);return {accounts,admin,delivery,userId:u.user.id,session:u.session,setNow:(n:number)=>clock=n};}
function job(f:ReturnType<typeof fixture>,id='one',kind='digest'){if(kind==='digest')f.accounts.db.prepare("INSERT INTO mail_jobs(id,userId,payload,created) VALUES(?,?,'PRIVATE',?)").run(id,f.userId,now);else{f.accounts.db.prepare("INSERT INTO pro_reports VALUES(?,?,?,'{\"providers\":[],\"models\":[],\"families\":[],\"topics\":[]}','[]','normal',?)").run('report-'+id,f.userId,id==='other'?'2026-10-12':'2026-10-05',now);f.accounts.db.prepare('INSERT INTO pro_mail(id,userId,reportId,created) VALUES(?,?,?,?)').run(id,f.userId,'report-'+id,now);}return kind+':'+id;}
function command(f:ReturnType<typeof fixture>,id:string,op:string,key='k'):AdminCommand{return {actor:{type:'cli',id:'local-ops'},action:'delivery.'+op,targetType:'mail_delivery',targetId:id,reason:'已核对供应商',requestId:'req',idempotencyKey:key,input:{reason:'已核对供应商'},expectedVersion:f.delivery.version(id),currentVersion:()=>f.delivery.version(id)};}
async function send(f:ReturnType<typeof fixture>,id='one',outcome='accepted'){const l=f.delivery.ledger;f.accounts.db.prepare('UPDATE mail_jobs SET lease=? WHERE id=?').run(now+300000,id);const a=l.begin('digest',id,now+300000);await l.send('digest',id,now+300000,a,{async send(){if(outcome==='failed')throw new MailSendError('provider_rejected',true);if(outcome==='unknown')throw Error('raw secret exception');return {provider:'local',messageId:'message-'+id};}},{to:'local@example.test',key:'digest-'+id,subject:'test',text:'private'});}
function envelope(f:ReturnType<typeof fixture>,type='email.delivered',at=now+1000,id='event1'){const raw=JSON.stringify({type,created_at:new Date(at).toISOString(),data:{email_id:'message-one',text:'PRIVATE_BODY'}}),ts=String(Math.floor(f.accounts.now()/1000)),key='whsec_'+Buffer.from('local-signing-secret-32-characters').toString('base64'),sig=createHmac('sha256',Buffer.from(key.slice(6),'base64')).update(id+'.'+ts+'.'+raw).digest('base64');return {key,value:{raw,headers:{'svix-id':id,'svix-timestamp':ts,'svix-signature':'v1,'+sig}}};}
test('two business kinds project legacy sent as accepted; private bodies and credentials excluded',()=>{const f=fixture();try{job(f);job(f,'two','pro');f.accounts.db.prepare("UPDATE mail_jobs SET status='sent',mail='PRIVATE_UNSUBSCRIBE'").run();f.accounts.db.prepare("UPDATE pro_mail SET status='review',mail='PRIVATE_RSS'").run();const rows=f.delivery.list(new URLSearchParams());assert.equal(rows.items.length,2);assert.equal(f.delivery.detail('digest:one').state,'accepted');assert.equal(f.delivery.detail('pro:two').state,'unknown');assert.equal(f.delivery.detail('digest:one').messageId,null);assert.ok(!JSON.stringify(rows).includes('PRIVATE'));assert.ok(!JSON.stringify(f.delivery.detail('digest:one')).includes('PRIVATE'));new AdminDelivery(f.admin);}finally{f.accounts.close();}});
test('timeout is unknown and never automatically retried; expired lease is unknown',async()=>{const f=fixture();try{job(f);await send(f,'one','unknown');assert.equal(f.delivery.detail('digest:one').state,'unknown');assert.equal(f.accounts.claim(),null);assert.throws(()=>f.delivery.write(command(f,'digest:one','retry'),'retry'));assert.throws(()=>f.delivery.write(command(f,'digest:one','reconcile'),'reconcile'));job(f,'two');f.accounts.db.prepare('UPDATE mail_jobs SET lease=? WHERE id=?').run(now-1,'two');assert.equal(f.delivery.detail('digest:two').state,'unknown');assert.equal(f.accounts.claim(),null);assert.equal(f.delivery.detail('digest:two').state,'unknown');assert.ok(!JSON.stringify(f.delivery.detail('digest:one')).includes('secret'));}finally{f.accounts.close();}});
test('confirmed rejection retries same job with audit, version and duplicate submission once',async()=>{const f=fixture();try{job(f);await send(f,'one','failed');const c=command(f,'digest:one','retry'),r=f.delivery.write(c,'retry');assert.equal(r.state,'queued');assert.deepEqual(f.delivery.write(c,'retry'),r);assert.equal(f.accounts.db.prepare("SELECT count(*) n FROM admin_audit WHERE action='delivery.retry'").get()!.n,1);assert.throws(()=>f.delivery.write({...c,idempotencyKey:'new'},'retry'));assert.equal(f.accounts.claim()!.id,'one');}finally{f.accounts.close();}});
test('unsubscribe and entitlement revoke block retry without enabling subscriptions',async()=>{const f=fixture();try{job(f);await send(f,'one','failed');f.accounts.preferences(f.userId,false);assert.equal(f.delivery.detail('digest:one').retryAvailable,false);assert.throws(()=>f.delivery.write(command(f,'digest:one','retry'),'retry'));job(f,'pro','pro');const scope={providers:['openai'],models:[],families:[],topics:['price']};f.delivery.pro.grant(f.userId,now-1000,now+86400000,'ops','test');f.delivery.pro.configure(f.userId,scope,true);f.accounts.db.prepare("INSERT INTO mail_delivery(kind,jobId,state) VALUES('pro','pro','failed')").run();f.accounts.db.prepare("INSERT INTO mail_attempts VALUES('a','pro','pro',?, ?,0,'failed','provider_rejected',NULL,NULL)").run(now,now);assert.equal(f.delivery.detail('pro:pro').retryAvailable,true);f.delivery.pro.grant(f.userId,now-1000,now+86400000,'ops','revoked',true);assert.equal(f.delivery.detail('pro:pro').retryAvailable,false);assert.throws(()=>f.delivery.write(command(f,'pro:pro','retry'),'retry'));assert.equal(f.accounts.user(f.session)!.emailEnabled,0);}finally{f.accounts.close();}});
test('verified duplicate and out of order receipts retain event time; bounce never enables resend',async()=>{const f=fixture();try{job(f);await send(f);f.setNow(now+2000);const delivered=envelope(f),result=importReceipt(f.delivery,delivered.value,delivered.key,true);assert.equal(result.duplicate,false);assert.equal(importReceipt(f.delivery,delivered.value,delivered.key,true).duplicate,true);const older=envelope(f,'email.sent',now,'old');importReceipt(f.delivery,older.value,older.key,true);f.delivery.write(command(f,'digest:one','reconcile'),'reconcile');assert.equal(f.delivery.detail('digest:one').state,'delivered');assert.equal(f.delivery.detail('digest:one').eventAt,now+1000);const bounce=envelope(f,'email.bounced',now+1500,'bounce');importReceipt(f.delivery,bounce.value,bounce.key,true); // Delivered is a terminal verified fact; later bounce is retained for inspection, not made retryable.
 assert.equal(f.delivery.detail('digest:one').retryAvailable,false);const detail=f.delivery.detail('digest:one');assert.equal(detail.evidence.length,3);assert.ok(!JSON.stringify(detail).includes('PRIVATE_BODY'));}finally{f.accounts.close();}});
test('signature, timestamp, mismatched message and conflicting receipt rejection',async()=>{const f=fixture();try{job(f);await send(f);const e=envelope(f,'email.delivered',now);assert.throws(()=>importReceipt(f.delivery,{...e.value,raw:e.value.raw+' '},e.key,true));assert.throws(()=>importReceipt(f.delivery,e.value,'whsec_'+Buffer.from('wrong').toString('base64'),true));f.setNow(now+301000);assert.throws(()=>importReceipt(f.delivery,e.value,e.key,true));f.setNow(now);importReceipt(f.delivery,e.value,e.key,true);const conflicting=envelope(f,'email.bounced',now,'event1');assert.throws(()=>importReceipt(f.delivery,conflicting.value,conflicting.key,true));assert.throws(()=>f.delivery.evidence({id:'unmatched',job:'digest:one',provider:'local',messageId:'another',state:'delivered',eventAt:now,timeBasis:'event'}));}finally{f.accounts.close();}});
test('late acceptance after unsubscribe is accepted, never reported cancelled; no second sender',async()=>{const f=fixture();try{job(f);const l=f.delivery.ledger,lease=now+300000;f.accounts.db.prepare('UPDATE mail_jobs SET lease=?').run(lease);const a=l.begin('digest','one',lease);let complete!:(v:any)=>void;const work=l.send('digest','one',lease,a,{send:()=>new Promise(r=>complete=r)},{to:'x',key:'digest-one',subject:'s',text:'t'});assert.equal(f.accounts.claim(),null);f.accounts.preferences(f.userId,false);assert.equal(f.delivery.detail('digest:one').state,'sending');complete({provider:'local',messageId:'message-one'});await work;assert.equal(f.delivery.detail('digest:one').state,'accepted');}finally{f.accounts.close();}});
test('professional sender checks current entitlement and preferences, unknown has no automatic reexecution',async()=>{const f=fixture();try{job(f,'pro','pro');f.delivery.pro.grant(f.userId,now-1000,now+86400000,'ops','test');f.delivery.pro.configure(f.userId,{providers:['openai'],models:[],families:[],topics:['price']},true);let calls=0;await deliverPro(f.delivery.pro,{async send(){calls++;throw Error('timeout');}},'http://localhost');assert.equal(f.delivery.detail('pro:pro').state,'unknown');f.setNow(now+301000);await deliverPro(f.delivery.pro,{async send(){calls++;}},'http://localhost');assert.equal(calls,1);job(f,'other','pro');f.delivery.pro.grant(f.userId,now-1000,now+86400000,'ops','revoke',true);await deliverPro(f.delivery.pro,{async send(){calls++;}},'http://localhost');assert.equal(calls,1);assert.equal(f.delivery.detail('pro:other').state,'cancelled');}finally{f.accounts.close();}});
test('authenticated provider query saves observation time and omits returned body; 404 is unknown',async()=>{const f=fixture();try{job(f);await send(f);f.accounts.db.prepare("UPDATE mail_delivery SET provider='resend'").run();let url='';await queryMail(f.delivery,'digest:one','test-key',(async(u:any)=>{url=String(u);return new Response(JSON.stringify({id:'message-one',last_event:'delivered',text:'PRIVATE'}));}) as typeof fetch);assert.equal(url,'https://api.resend.com/emails/message-one');assert.equal(f.delivery.detail('digest:one').evidence[0]!.timeBasis,'query');assert.ok(!JSON.stringify(f.delivery.detail('digest:one')).includes('PRIVATE'));await assert.rejects(queryMail(f.delivery,'digest:one','key',(async()=>new Response('',{status:404})) as typeof fetch));}finally{f.accounts.close();}});
test('health missing, stale and dependency failures are unknown/abnormal; backup never implies restore',()=>{const f=fixture();try{const initial=f.delivery.health({current:null});assert.equal(initial.items.find(r=>r.kind==='restore').status,'unknown');assert.equal(initial.items.find(r=>r.kind==='data').status,'abnormal');const record={id:'b',kind:'backup',status:'normal',checkedAt:now,budgetSeconds:60,source:'account-maintenance.backup',value:null};f.delivery.healthImport(record);assert.equal(f.delivery.healthImport(record).duplicate,true);assert.equal(f.delivery.health({current:null}).items.find(r=>r.kind==='backup').status,'normal');assert.equal(f.delivery.health({current:null}).items.find(r=>r.kind==='restore').status,'unknown');assert.throws(()=>f.delivery.healthImport({...record,status:'abnormal'}));assert.throws(()=>f.delivery.healthImport({...record,id:'bad',kind:'restore'}));f.setNow(now+61000);const old=f.delivery.health({current:{version:'ds_test'},lastReloadError:'SECRET'});assert.equal(old.items.find(r=>r.kind==='backup').status,'unknown');assert.equal(old.items.find(r=>r.kind==='backup').stale,true);assert.equal(old.items.find(r=>r.kind==='data').status,'abnormal');assert.ok(!JSON.stringify(old).includes('SECRET'));}finally{f.accounts.close();}});
test('filters, bounded pagination and signed cursor bind type/state/user/time',()=>{const f=fixture();try{for(const id of ['a','b','c'])job(f,id);const p=f.delivery.list(new URLSearchParams('limit=1'));assert.equal(p.items.length,1);assert.ok(p.nextCursor);assert.equal(f.delivery.list(new URLSearchParams({limit:'1',cursor:p.nextCursor!})).items.length,1);assert.throws(()=>f.delivery.list(new URLSearchParams({state:'failed',cursor:p.nextCursor!})));assert.equal(f.delivery.list(new URLSearchParams('user=local%40example.test&type=digest&state=queued')).items.length,3);assert.equal(f.delivery.list(new URLSearchParams('from=2026-10-05T00%3A00%3A00%2B08%3A00')).items.length,0);assert.throws(()=>f.delivery.list(new URLSearchParams('shell=x')));}finally{f.accounts.close();}});
test('HTTP admin permission, Origin, no-store, audited idempotent retry and no remote ingest or shell',async()=>{const f=fixture();job(f);await send(f,'one','failed');const owner=f.accounts.verify('owner@example.test',f.accounts.issueCode('owner@example.test'));f.admin.setMember(owner.user.id,true,'ops','test');const handler=createAdminHandler(f.admin,{current:null} as unknown as DatasetHolder,{origin:'http://localhost',secure:false}),server=http.createServer(handler);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+(server.address() as any).port,headers={Cookie:'maas_session='+owner.session,Origin:'http://localhost','Content-Type':'application/json','Idempotency-Key':'http'},body=JSON.stringify({reason:'retry verified rejection',expectedVersion:f.delivery.version('digest:one')});try{assert.equal((await fetch(base+'/api/admin/delivery')).status,401);assert.equal((await fetch(base+'/api/admin/health',{headers:{Cookie:'maas_session='+f.session}})).status,403);const r=await fetch(base+'/api/admin/delivery',{headers});assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await fetch(base+'/api/admin/delivery/digest%3Aone/retry',{method:'POST',headers:{...headers,Origin:'https://evil.test'},body})).status,403);for(let i=0;i<2;i++)assert.equal((await fetch(base+'/api/admin/delivery/digest%3Aone/retry',{method:'POST',headers,body})).status,200);assert.equal((await fetch(base+'/api/admin/delivery/ingest',{method:'POST',headers,body:'{}'})).status,404);assert.equal((await fetch(base+'/api/admin/health/restart',{method:'POST',headers,body:'{}'})).status,404);f.admin.setMember(owner.user.id,false,'ops','revoke');assert.equal((await fetch(base+'/api/admin/health',{headers})).status,403);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));f.accounts.close();}});

test('expired lease before adapter handoff cannot dispatch',async()=>{const f=fixture();try{job(f);const l=f.delivery.ledger,lease=now+1000;f.accounts.db.prepare('UPDATE mail_jobs SET lease=?').run(lease);const attempt=l.begin('digest','one',lease);f.setNow(now+1001);let calls=0;await l.send('digest','one',lease,attempt,{async send(){calls++;}},{to:'x',key:'digest-one',subject:'s',text:'t'});assert.equal(calls,0);assert.equal(f.delivery.detail('digest:one').state,'unknown');}finally{f.accounts.close();}});
test('confirmed professional retry preserves frozen body and supplier key',async()=>{const f=fixture();try{job(f,'pro','pro');f.delivery.pro.grant(f.userId,now-1000,now+86400000,'ops','test');f.delivery.pro.configure(f.userId,{providers:['openai'],models:[],families:[],topics:['price']},true);const mails:any[]=[];await deliverPro(f.delivery.pro,{async send(m){mails.push(m);throw new MailSendError('provider_rejected',true);}},'http://localhost');const id='pro:pro',c=command(f,id,'retry');f.delivery.write(c,'retry');f.delivery.write(c,'retry');await deliverPro(f.delivery.pro,{async send(m){mails.push(m);return {provider:'local',messageId:'retry-message'};}},'http://changed-localhost');await deliverPro(f.delivery.pro,{async send(){throw Error('must not duplicate');}},'http://localhost');assert.equal(mails.length,2);assert.deepEqual(mails[0],mails[1]);assert.equal(mails[1].key,'pro-pro');assert.equal(f.delivery.detail(id).state,'accepted');assert.equal(f.delivery.detail(id).attempts.length,2);}finally{f.accounts.close();}});
test('Svix official independent signature vector verifies exact algorithm',()=>{const f=fixture();try{f.setNow(1731705121000);assert.throws(()=>importReceipt(f.delivery,{raw:'{"event_type":"ping","data":{"success":true}}',headers:{'svix-id':'msg_loFOjxBNrRLzqYUf','svix-timestamp':'1731705121','svix-signature':'v1,rAvfW3dJ/X/qxhsaXPOyyCGmRKsaKWcsNccKXlIktD0='}},'whsec_plJ3nmyCDGBKInavdOK15jsl',true),/unsupported receipt/);}finally{f.accounts.close();}});

test('delivered evidence never loses to later accepted observation or local completion clock',async()=>{const f=fixture();try{job(f);await send(f);f.setNow(now+2000);const e=envelope(f,'email.delivered',now-1000,'delivered-earlier-clock');importReceipt(f.delivery,e.value,e.key,true);const later=envelope(f,'email.sent',now+1000,'accepted-later');importReceipt(f.delivery,later.value,later.key,true);f.delivery.write(command(f,'digest:one','reconcile'),'reconcile');assert.equal(f.delivery.detail('digest:one').state,'delivered');assert.equal(f.delivery.detail('digest:one').eventAt,now-1000);}finally{f.accounts.close();}});
