import {test} from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {EditorialStore} from '../editorial-store.js';
import {AccountStore,AccountError} from '../account-store.js';
import {AdminStore,type AdminCommand} from '../admin-store.js';
import {AdminMonitor} from '../admin-monitor.js';
import {createAdminHandler} from '../admin-http.js';
import type {DatasetHolder} from '../dataset.js';
const now=Date.parse('2026-10-04T08:00:00Z'),secret='monitor-local-fixed-secret-32-characters';
function fixture(){const accounts=new AccountStore(':memory:',()=>now,secret),admin=new AdminStore(accounts),monitor=new AdminMonitor(admin);return {accounts,admin,monitor};}
const source={id:'openai-pricing',name:'OpenAI 定价',platform:'openai',kind:'pricing',budgetHours:48};
function run(id='r1',extra:Record<string,unknown>={}){return {id,kind:'prices',trigger:'manual',state:'succeeded',stage:'archive-committed',startedAt:now-60000,finishedAt:now-30000,observedAt:now-30000,inputVersion:'inv_one',outputVersion:'inv_two',result:'success',validation:'unknown',publication:'not_run',errorCode:null,runLink:null,sources:[{sourceId:source.id,attemptAt:now-60000,successAt:now-45000,dataThrough:now-45000,outcome:'success',coverage:'full',errorCode:null}],...extra};}
function batch(runs:unknown[],id='b1'){return {schemaVersion:1,batchId:id,sources:[source],runs};}
function command(f:ReturnType<typeof fixture>,id:string,input:Record<string,unknown>,key='key1'):AdminCommand{return {actor:{type:'cli',id:'local-ops'},action:'monitor.anomaly.update',targetType:'monitor_anomaly',targetId:id,reason:'已核对受控运行',requestId:'request',idempotencyKey:key,input,expectedVersion:f.monitor.anomalyVersion(id),currentVersion:()=>f.monitor.anomalyVersion(id)};}
test('additive migration is repeatable and rollback leaves no partial schema',()=>{const f=fixture();try{new AdminMonitor(f.admin);assert.equal(f.accounts.db.prepare('SELECT count(*) n FROM admin_schema_migrations WHERE version=5').get()!.n,1);}finally{f.accounts.close();}const a=new AccountStore(':memory:',()=>now,secret),s=new AdminStore(a);try{a.db.exec('CREATE TABLE monitor_runs(x TEXT)');assert.throws(()=>new AdminMonitor(s));assert.equal(a.db.prepare("SELECT 1 FROM sqlite_master WHERE name='monitor_sources'").get(),undefined);assert.equal(a.db.prepare('SELECT 1 FROM admin_schema_migrations WHERE version=5').get(),undefined);}finally{a.close();}});
test('success and unchanged are executions; validation and publication remain independent',()=>{const f=fixture();try{f.monitor.ingest(batch([run()]));let s=f.monitor.sources(new URLSearchParams()).items[0]!;assert.equal(s.health,'normal');assert.equal(s.latestSuccessAt,now-45000);assert.equal(s.consecutiveFailures,0);const r=f.monitor.runs(new URLSearchParams()).items[0];assert.equal(r.validation,'unknown');assert.equal(r.publication,'not_run');f.monitor.ingest(batch([run('r2',{result:'unchanged',observedAt:now-1000,sources:[{sourceId:source.id,attemptAt:now-2000,successAt:now-2000,dataThrough:now-2000,outcome:'unchanged',coverage:'full',errorCode:null}]})],'b2'));s=f.monitor.sources(new URLSearchParams()).items[0]!;assert.equal(s.outcome,'unchanged');assert.equal(s.health,'normal');assert.equal(s.latestSuccessAt,now-2000);}finally{f.accounts.close();}});
test('partial and full failure preserve prior success, distinguish fetch and parse, no not-run success',()=>{const f=fixture();try{f.monitor.ingest(batch([run()]));for(const [i,outcome]of ['fetch_failed','parse_failed'].entries())f.monitor.ingest(batch([run('bad'+i,{state:i?'failed':'succeeded',result:i?'failed':'partial',observedAt:now-10000+i*1000,sources:[{sourceId:source.id,attemptAt:now-12000+i*1000,successAt:null,dataThrough:null,outcome,coverage:'missing',errorCode:outcome}]})],'batch'+i));let s=f.monitor.sources(new URLSearchParams()).items[0]!;assert.equal(s.health,'degraded');assert.equal(s.errorSummary,'解析失败');assert.equal(s.consecutiveFailures,2);assert.equal(s.latestSuccessAt,now-45000);f.monitor.ingest(batch([run('skip',{result:'not_run',observedAt:now-100,sources:[{sourceId:source.id,attemptAt:null,successAt:null,dataThrough:null,outcome:'not_run',coverage:'unknown',errorCode:null}]})],'skip'));s=f.monitor.sources(new URLSearchParams()).items[0]!;assert.equal(s.health,'not_run');assert.equal(s.consecutiveFailures,2);assert.equal(s.latestSuccessAt,now-45000);}finally{f.accounts.close();}});
test('unknown history and stale evidence never invent success',()=>{const f=fixture();try{f.monitor.ingest(batch([]));let s=f.monitor.sources(new URLSearchParams()).items[0]!;assert.equal(s.health,'unknown');assert.equal(s.latestSuccessAt,null);assert.equal(s.consecutiveFailures,null);f.monitor.ingest(batch([run('old',{startedAt:null,finishedAt:null,observedAt:now-3*86400000,sources:[{sourceId:source.id,attemptAt:null,successAt:now-3*86400000,dataThrough:null,outcome:'success',coverage:'full',errorCode:null}]})],'old'));s=f.monitor.sources(new URLSearchParams()).items[0]!;assert.equal(s.health,'stale');assert.equal(s.latestAttemptAt,null);assert.equal(s.dataThrough,null);}finally{f.accounts.close();}});
test('duplicate receipt and duplicate run are idempotent; conflicting replay rolls back whole batch',()=>{const f=fixture();try{const b=batch([run()]);assert.equal(f.monitor.ingest(b).imported,1);assert.equal(f.monitor.ingest(b).duplicate,true);assert.equal(f.monitor.ingest(batch([run()],'newbatch')).imported,0);assert.throws(()=>f.monitor.ingest({...b,runs:[run('changed')]}),AccountError);assert.throws(()=>f.monitor.ingest(batch([run('rnew'),run('r1',{result:'partial'})],'conflict')),AccountError);assert.throws(()=>f.monitor.run('rnew'));assert.equal(f.accounts.db.prepare('SELECT count(*) n FROM monitor_runs').get()!.n,1);}finally{f.accounts.close();}});
test('strict bounded protocol rejects arbitrary logs, commands, URLs, errors and unknown sources',()=>{const f=fixture();try{for(const b of [ {...batch([]),shell:'rm'},batch([run('r',{logPath:'/etc/passwd'})]),batch([run('r',{errorCode:'Authorization: Bearer SECRET'})]),batch([run('r',{runLink:'https://example.com/?token=secret'})]),batch([run('r',{sources:[{sourceId:'unregistered',attemptAt:null,successAt:null,dataThrough:null,outcome:'unknown',coverage:'unknown',errorCode:null}]})]),batch([run('r',{publication:'completed',state:'failed'})])])assert.throws(()=>f.monitor.ingest(b));assert.equal(f.accounts.db.prepare('SELECT count(*) n FROM monitor_runs').get()!.n,0);}finally{f.accounts.close();}});
test('queue ignores do not heal sources; resolution requires later successful same source and full coverage',()=>{const f=fixture();try{f.monitor.ingest(batch([run('bad',{state:'failed',result:'failed',sources:[{sourceId:source.id,attemptAt:now-60000,successAt:null,dataThrough:null,outcome:'fetch_failed',coverage:'missing',errorCode:'fetch_failed'}]})]));const a=f.monitor.anomalies(new URLSearchParams()).items.find(x=>x.sourceId===source.id)!;f.monitor.update(command(f,a.id,{state:'ignored'}));assert.equal(f.monitor.sources(new URLSearchParams()).items[0]!.health,'degraded');assert.throws(()=>f.monitor.update(command(f,a.id,{state:'resolved',resolutionRunId:'bad'},'k2')));f.monitor.ingest(batch([run('wrong',{observedAt:now-2000,sources:[]})],'wrong'));assert.throws(()=>f.monitor.update(command(f,a.id,{state:'resolved',resolutionRunId:'wrong'},'k3')));f.monitor.ingest(batch([run('good',{observedAt:now-1000,sources:[{sourceId:source.id,attemptAt:now-2000,successAt:now-1500,dataThrough:now-1500,outcome:'success',coverage:'full',errorCode:null}]})],'good'));const c=command(f,a.id,{state:'resolved',resolutionRunId:'good'},'k4'),result=f.monitor.update(c);assert.equal(result.state,'resolved');assert.deepEqual(f.monitor.update(c),result);assert.equal(f.accounts.db.prepare("SELECT count(*) n FROM admin_audit WHERE action='monitor.anomaly.update'").get()!.n,2);assert.throws(()=>f.monitor.update({...c,idempotencyKey:'stale',input:{state:'ignored'}}),AccountError);}finally{f.accounts.close();}});
test('validation anomaly cannot resolve using merely successful execution',()=>{const f=fixture();try{f.monitor.ingest(batch([run('invalid',{validation:'failed',errorCode:'validation_failed'})]));const a=f.monitor.anomalies(new URLSearchParams()).items[0]!;f.monitor.ingest(batch([run('success',{observedAt:now-1000})],'success'));assert.throws(()=>f.monitor.update(command(f,a.id,{state:'resolved',resolutionRunId:'success'})));f.monitor.ingest(batch([run('checked',{validation:'passed',observedAt:now-500})],'checked'));assert.equal(f.monitor.update(command(f,a.id,{state:'resolved',resolutionRunId:'checked'},'checked')).state,'resolved');}finally{f.accounts.close();}});
test('runs pagination binds filters and omits private diagnostic payloads',()=>{const f=fixture();try{f.monitor.ingest(batch(Array.from({length:4},(_,i)=>run('r'+i,{observedAt:now-10000+i}))));const first=f.monitor.runs(new URLSearchParams('limit=2'));assert.equal(first.items.length,2);assert.ok(first.nextCursor);assert.equal(f.monitor.runs(new URLSearchParams({limit:'2',cursor:first.nextCursor!})).items.length,2);assert.throws(()=>f.monitor.runs(new URLSearchParams({kind:'sources',cursor:first.nextCursor!})));assert.throws(()=>f.monitor.runs(new URLSearchParams('shell=x')));assert.ok(!JSON.stringify(first).includes('payloadHash'));assert.equal(first.items[0].retryAvailable,false);}finally{f.accounts.close();}});
test('HTTP permission, CSRF, write audit, version and no execution endpoints',async()=>{const f=fixture();const ordinary=f.accounts.verify('ordinary@example.test',f.accounts.issueCode('ordinary@example.test')),owner=f.accounts.verify('admin@example.test',f.accounts.issueCode('admin@example.test'));f.admin.setMember(owner.user.id,true,'ops','test');f.monitor.ingest(batch([run('bad',{validation:'failed'})]));const a=f.monitor.anomalies(new URLSearchParams()).items[0]!;const server=http.createServer(createAdminHandler(f.admin,{current:null} as unknown as DatasetHolder,{origin:'http://localhost',secure:false}));await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${(server.address() as any).port}`,headers={Cookie:'maas_session='+owner.session,Origin:'http://localhost','Content-Type':'application/json','Idempotency-Key':'write'};try{assert.equal((await fetch(base+'/api/admin/monitor/sources')).status,401);assert.equal((await fetch(base+'/api/admin/monitor/runs',{headers:{Cookie:'maas_session='+ordinary.session}})).status,403);const result=await fetch(base+'/api/admin/monitor/sources',{headers});assert.equal(result.status,200);assert.equal(result.headers.get('cache-control'),'no-store');assert.equal((await fetch(base+'/api/admin/monitor/ingest',{method:'POST',headers,body:'{}'})).status,404);assert.equal((await fetch(base+'/api/admin/monitor/retry',{method:'POST',headers,body:'{}'})).status,404);const body=JSON.stringify({state:'ignored',reason:'测试忽略',expectedVersion:0});assert.equal((await fetch(base+'/api/admin/monitor/anomalies/'+a.id,{method:'POST',headers:{...headers,Origin:'https://evil.test'},body})).status,403);assert.equal((await fetch(base+'/api/admin/monitor/anomalies/'+a.id,{method:'POST',headers,body})).status,200);assert.equal((await fetch(base+'/api/admin/monitor/anomalies/'+a.id,{method:'POST',headers,body})).status,200);assert.equal((await fetch(base+'/api/admin/monitor/anomalies/'+a.id,{method:'POST',headers:{...headers,'Idempotency-Key':'another'},body})).status,409);f.admin.setMember(owner.user.id,false,'ops','revoke');assert.equal((await fetch(base+'/api/admin/monitor/sources',{headers})).status,403);}finally{await new Promise<void>(r=>server.close(()=>r()));f.accounts.close();}});

test('two connections and restart preserve receipts and source history',()=>{const dir=mkdtempSync(join(tmpdir(),'monitor-')),db=join(dir,'account.sqlite');const a=new AccountStore(db,()=>now,secret),b=new AccountStore(db,()=>now,secret);try{const m=new AdminMonitor(new AdminStore(a)),n=new AdminMonitor(new AdminStore(b));assert.equal(m.ingest(batch([run()])).imported,1);assert.equal(n.ingest(batch([run()])).duplicate,true);assert.equal(n.runs(new URLSearchParams()).items.length,1);}finally{a.close();b.close();}const restored=new AccountStore(db,()=>now,secret);try{const m=new AdminMonitor(new AdminStore(restored));assert.equal(m.sources(new URLSearchParams()).items[0]!.latestSuccessAt,now-45000);assert.equal(m.ingest(batch([run()])).duplicate,true);}finally{restored.close();rmSync(dir,{recursive:true,force:true});}});
test('T03 live state and safe versions project without config, payload or provider error text',()=>{const f=fixture();try{const editorial=new EditorialStore(f.admin);const user=f.accounts.verify('editorial@example.test',f.accounts.issueCode('editorial@example.test')).user.id;f.accounts.db.prepare("INSERT INTO editorial_issues(id,periodEnd,windowFrom,windowTo,coverage,coverageNote,selection,state,budget,config,createdBy,createdAt) VALUES('issue','2026-09-28','from','to','normal','','','draft',1,'{}',?,?)").run(user,now);f.accounts.db.prepare("INSERT INTO editorial_runs(id,issueId,stage,state,inputHash,config,budget,createdAt,payload,errorCode) VALUES('live','issue','analyze','needs_review','input_hash','PRIVATE_PROVIDER_CONFIG',1,?,'PRIVATE_INPUT_EVIDENCE','SECRET_RAW_EXCEPTION')").run(now);new AdminMonitor(f.admin);const r=f.monitor.runs(new URLSearchParams('kind=editorial')).items[0];assert.equal(r.id,'editorial_live');assert.equal(r.state,'needs_review');assert.equal(r.finishedAt,null);assert.equal(r.validation,'unknown');assert.equal(r.publication,'not_run');assert.ok(!JSON.stringify(r).includes('PRIVATE'));assert.ok(!JSON.stringify(r).includes('SECRET'));assert.equal(f.monitor.runs(new URLSearchParams('runId=editorial_live')).items.length,1);assert.ok(f.accounts.db.prepare("SELECT 1 FROM sqlite_master WHERE name='editorial_runs_monitor_order'").get());void editorial;}finally{f.accounts.close();}});
