import { test } from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { AccountStore } from '../account-store.js';
import { AdminStore, type AdminCommand } from '../admin-store.js';
import { EditorialStore, monday, packageSchema } from '../editorial-store.js';
import { EditorialService } from '../editorial-service.js';
import { EditorialWorker } from '../editorial-worker.js';
import { MockModel, ModelFailure, type EditorialModel, type ModelInput } from '../editorial-model.js';
import { Dataset, type DatasetHolder } from '../dataset.js';
import { createAdminHandler } from '../admin-http.js';
import { createProHandler } from '../pro-http.js';
import { checkPackage } from '../editorial-checks.js';
const end='2026-09-28';
function setup(){let now=Date.parse('2026-10-04T00:00:00Z');const accounts=new AccountStore(':memory:',()=>now,'editorial-test-secret-at-least-32-chars');const admin=new AdminStore(accounts),store=new EditorialStore(admin);const ds=Dataset.load(fileURLToPath(new URL('../../../../data/public/v1',import.meta.url)));const holder={current:ds} as DatasetHolder;const service=new EditorialService(store,holder);const id='weekly-'+end;const command=(op:string,input:Record<string,unknown>={},key:string=randomUUID()):AdminCommand=>({actor:{type:'cli',id:'editor-test'},action:'weekly.'+op,targetType:'editorial_issue',targetId:id,requestId:randomUUID(),idempotencyKey:key,reason:'isolated evidence test',input,...(op==='create'?{}:{expectedVersion:store.issue(id).version,currentVersion:()=>store.issue(id).version})});const write=(op:string,input:Record<string,unknown>={},key?:string)=>service.write(command(op,input,key),op);
 write('create',{periodEnd:end,selection:'真实历史观察演练',budget:0});write('prepare',{coverage:'partial',coverageNote:'本地历史素材，未确认全量覆盖'});
 return {accounts,admin,store,holder,service,id,write,command,setNow:(n:number)=>now=n};}
async function manual(s:ReturnType<typeof setup>){const i=s.store.issue(s.id);const input:ModelInput={stage:'analyze',periodEnd:end,windowFrom:i.windowFrom,windowTo:i.windowTo,dataThrough:i.dataThrough!,coverage:i.coverage,coverageNote:i.coverageNote,selection:i.selection,inputs:s.store.inputs(s.id),upstream:null};return packageSchema.parse((await new MockModel().call(input)).output);}
function approve(s:ReturnType<typeof setup>){const r=s.store.revision(s.id);s.write('review',{decision:'submit',revision:r.revision,outputHash:r.outputHash,note:'逐条人工复核'});s.write('review',{decision:'approve',revision:r.revision,outputHash:r.outputHash,note:'已核对隔离演练来源、范围、预览；模拟结果不代表模型质量',checklist:{sources:true,conditions:true,conclusions:true,coverage:true,preview:true,attribution:true}});return r;}

test('real calendar Monday boundaries, migration additive and snapshots immutable',()=>{assert.throws(()=>monday('2026-02-30'));assert.throws(()=>monday('2026-10-04'));assert.deepEqual(monday('2026-06-01'),{from:'2026-05-25T00:00:00+08:00',to:'2026-06-01T00:00:00+08:00'});const s=setup();try{assert.ok(s.store.inputs(s.id).length);const first=s.store.issue(s.id).inputHash;s.write('prepare',{coverage:'failed',coverageNote:'新覆盖说明'});assert.notEqual(s.store.issue(s.id).inputHash,first);assert.ok(s.store.db.prepare('SELECT 1 FROM editorial_inputs WHERE snapshotId=?').get(first!));new EditorialStore(s.admin);assert.equal(s.store.db.prepare('SELECT count(*) n FROM admin_schema_migrations WHERE version=3').get()!.n,1);assert.equal(s.write('create',{periodEnd:end,selection:'duplicate',budget:0}).created,false);}finally{s.accounts.close();}});

test('manual revision/review hash binding, atomic package publication and duplicate replay',async()=>{const s=setup();try{const pack=await manual(s);s.write('revisions',{package:pack});const r=approve(s);s.write('revisions',{package:pack});assert.equal(s.store.issue(s.id).state,'draft');assert.throws(()=>s.write('publish',{revision:r.revision,outputHash:r.outputHash}));const next=approve(s);s.store.db.exec("CREATE TRIGGER publication_failure BEFORE INSERT ON editorial_publications BEGIN SELECT RAISE(ABORT,'injected fault'); END");assert.throws(()=>s.write('publish',{revision:next.revision,outputHash:next.outputHash}));assert.equal(s.service.pro.contents().length,0);assert.equal(s.store.db.prepare('SELECT count(*) n FROM pro_content').get()!.n,0);s.store.db.exec('DROP TRIGGER publication_failure');const c=s.command('publish',{revision:next.revision,outputHash:next.outputHash});const p=s.service.write(c,'publish');assert.deepEqual(s.service.write(c,'publish'),p);const again=s.write('publish',{revision:next.revision,outputHash:next.outputHash});assert.equal(again.publicationId,p.publicationId);assert.equal(s.service.pro.contents().length,2);assert.equal(s.store.db.prepare('SELECT count(*) n FROM editorial_publications').get()!.n,1);const user=s.accounts.verify('reader@example.test',s.accounts.issueCode('reader@example.test')).user;s.service.pro.activateBeta(user.id);s.service.pro.configure(user.id,{providers:pack.contents[0]!.providers,models:[],families:[],topics:['capability']},false);assert.equal(s.write('compose',{queueMail:false}).created,1);assert.equal(s.write('compose',{queueMail:true}).created,0);assert.equal(s.store.db.prepare('SELECT count(*) n FROM pro_mail').get()!.n,0);assert.ok(s.service.pro.report(user.id,String(s.service.pro.reports(user.id)[0]!.id)).items.every(c=>!('kind' in c)||c.kind!=='briefing'));}finally{s.accounts.close();}});

test('forged references/XSS/price mismatch flagged, current withdrawal blocks publication',async()=>{const s=setup();try{const pack=await manual(s);const changed=structuredClone(pack);changed.contents[0]!.evidence[0]!.id='fake';changed.contents[0]!.body='<img src=x onerror=alert(1)>';changed.contents[0]!.rows=[{amount:'3',evidenceId:'fake'}];assert.ok(checkPackage(changed,s.store.issue(s.id),s.store.inputs(s.id)).blocking.length>=3);s.write('revisions',{package:pack});const r=approve(s);const e=pack.contents[0]!.evidence[0]!.id;const original=s.holder.current!.itemsById.get(e)!;s.holder.current!.itemsById.set(e,{...original,status:'withdrawn'});assert.throws(()=>s.write('publish',{revision:r.revision,outputHash:r.outputHash}));assert.equal(s.service.pro.contents().length,0);}finally{s.accounts.close();}});

test('persistent staged mock worker, dedup, lease fencing and cancellation reject late result',async()=>{const s=setup();try{const worker=new EditorialWorker(s.service);const a=s.write('runs',{stage:'curate'});assert.equal(s.write('runs',{stage:'curate'}).runId,a.runId);await worker.once();assert.equal(s.store.run(String(a.runId)).state,'succeeded');s.write('runs',{stage:'analyze'});await worker.once();assert.equal(s.store.issue(s.id).currentRevision,1);const verify=s.write('runs',{stage:'verify'});const claimed=worker.claim()!;assert.equal(new EditorialWorker(s.service).claim(),null);const fence=Number(claimed.fencingVersion);s.setNow(s.store.now+300001);assert.equal(worker.recover(),1);assert.equal(worker.finish(String(verify.runId),fence,'succeeded',{},null),false);assert.equal(s.store.run(String(verify.runId)).state,'needs_review');const c:AdminCommand={...s.command('cancel'),targetId:String(verify.runId),expectedVersion:Number(s.store.run(String(verify.runId)).version),currentVersion:()=>Number(s.store.run(String(verify.runId)).version)};s.service.cancel(c);assert.equal(worker.heartbeat(String(verify.runId),fence),false);}finally{s.accounts.close();}});

test('uncertain calls require review, retries bounded, insufficient budget calls no adapter',async()=>{const s=setup();try{s.write('runs',{stage:'curate'});let calls=0;const adapter:EditorialModel={async call(){calls++;throw new ModelFailure('rate_limit',true);}};const w=new EditorialWorker(s.service,adapter);for(let n=0;n<3;n++){await w.once();s.setNow(s.store.now+30000);}assert.equal(calls,3);assert.equal(s.store.db.prepare('SELECT state FROM editorial_runs').get()!.state,'failed');s.store.db.prepare('UPDATE editorial_issues SET config=? WHERE id=?').run(JSON.stringify({...JSON.parse(s.store.issue(s.id).config),adapter:'openai',price:{currency:'USD',inputPerMillion:10,outputPerMillion:10,updatedAt:'2026-10-04T00:00:00Z',source:'https://openai.com/api/pricing/'}}),s.id);assert.throws(()=>s.write('runs',{stage:'curate'}));assert.equal(calls,3);
 s.store.db.prepare('UPDATE editorial_issues SET budget=100 WHERE id=?').run(s.id);s.write('runs',{stage:'curate'});await new EditorialWorker(s.service,{async call(){throw new ModelFailure('unknown',false,true);}}).once();assert.equal(s.store.db.prepare('SELECT state FROM editorial_runs ORDER BY createdAt DESC LIMIT 1').get()!.state,'needs_review');}finally{s.accounts.close();}});

test('authenticated HTTP body limits, no draft disclosure, Plus consumer serialization',async()=>{const s=setup();const adminUser=s.accounts.verify('admin@example.test',s.accounts.issueCode('admin@example.test'));s.admin.setMember(adminUser.user.id,true,'operator','test');let origin='';const config={origin:'',secure:false};const ah=createAdminHandler(s.admin,s.holder,config),ph=createProHandler(s.service.pro,s.holder,config,false);const server=http.createServer((req,res)=>void(req.url?.startsWith('/api/admin/')?ah:ph)(req,res));await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${(server.address() as {port:number}).port}`;config.origin=origin;const cookie={Cookie:`maas_session=${adminUser.session}`};const post=(route:string,input:unknown)=>fetch(origin+'/api/admin/'+route,{method:'POST',headers:{...cookie,Origin:origin,'Content-Type':'application/json','Idempotency-Key':randomUUID()},body:JSON.stringify(input)});try{assert.equal((await fetch(origin+'/api/admin/weekly/'+s.id)).status,401);const pack=await manual(s);pack.contents[0]!.body='PRIVATE_FULL_TEXT\n'+'x'.repeat(18000);let response=await post('weekly/'+s.id+'/revisions',{reason:'test',expectedVersion:s.store.issue(s.id).version,package:pack});assert.equal(response.status,200,await response.text());assert.equal((await post('weekly/'+s.id+'/revisions',{reason:'test',expectedVersion:s.store.issue(s.id).version,package:'x'.repeat(1048576)})).status,413);assert.equal((await post('weekly/'+s.id+'/prepare',{reason:'test',expectedVersion:s.store.issue(s.id).version,coverageNote:'x'.repeat(18000),coverage:'partial'})).status,413);const r=approve(s);s.write('publish',{revision:r.revision,outputHash:r.outputHash});assert.ok(!(await(await fetch(origin+'/api/pro/catalog')).text()).includes('PRIVATE_FULL_TEXT'));const cid=pack.contents[0]!.id;assert.equal((await fetch(origin+'/api/pro/content/'+cid)).status,401);assert.equal((await fetch(origin+'/api/pro/content/'+cid,{headers:cookie})).status,403);s.service.pro.activateBeta(adminUser.user.id);assert.ok((await(await fetch(origin+'/api/pro/content/'+cid,{headers:cookie})).text()).includes('PRIVATE_FULL_TEXT'));}finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));s.accounts.close();}});

test('zero evidence preserves coverage-only issue; no artificial pro content',()=>{const s=setup();try{const command={...s.command('create',{periodEnd:'2020-01-06',selection:'无历史证据',budget:0}),targetId:'empty'};s.service.write(command,'create');const write=(op:string,input:Record<string,unknown>)=>s.service.write({...s.command(op,input),targetId:'empty',expectedVersion:s.store.issue('empty').version,currentVersion:()=>s.store.issue('empty').version},op);assert.throws(()=>write('prepare',{coverage:'normal',coverageNote:'全量'}));write('prepare',{coverage:'failed',coverageNote:'零证据，无法支持任何正文分析'});assert.equal(s.store.inputs('empty').length,0);assert.equal(s.service.pro.contents().length,0);assert.throws(()=>write('runs',{stage:'analyze'}));}finally{s.accounts.close();}});

test('editing during model call rejects overwrite but keeps incurred fees; cancellation and recovery reconciliation',async()=>{const s=setup();try{const pack=await manual(s);const worker=new EditorialWorker(s.service);s.write('runs',{stage:'curate'});await worker.once();const run=s.write('runs',{stage:'analyze'});let done!:(v:any)=>void;const waiting:EditorialModel={call(){return new Promise(resolve=>{done=resolve;});}};const turn=new EditorialWorker(s.service,waiting).once();await new Promise(resolve=>setImmediate(resolve));s.write('revisions',{package:pack});done({output:pack,inputTokens:100,outputTokens:100,actualCost:0.012,requestId:'isolated-test'});await turn;assert.equal(s.store.issue(s.id).currentRevision,1);assert.equal(s.store.run(String(run.runId)).actualCost,0.012);assert.equal(s.store.run(String(run.runId)).state,'cancelled');
 const verify=s.write('runs',{stage:'verify'});await new EditorialWorker(s.service,{async call(){throw new ModelFailure('provider_outcome_unknown',false,true);}}).once();assert.throws(()=>s.write('runs',{stage:'verify'}));const rid=String(verify.runId);const c:AdminCommand={...s.command('reconcile',{outcome:'not_executed',note:'隔离供应商夹具证实未执行',actualCost:0}),targetId:rid,expectedVersion:Number(s.store.run(rid).version),currentVersion:()=>Number(s.store.run(rid).version)};s.service.reconcile(c);assert.equal(s.store.run(rid).errorCode,'operator_reconciled');assert.ok(s.write('runs',{stage:'verify'}).runId);}finally{s.accounts.close();}});

test('two connections claim one durable task; restart retains frozen draft and fencing',async()=>{const {mkdtempSync,rmSync}=await import('node:fs');const {tmpdir}=await import('node:os');const path=await import('node:path');const root=mkdtempSync(path.join(tmpdir(),'editorial-persistence-')),filename=path.join(root,'accounts.sqlite');const secret='editorial-persistence-test-secret-32-chars';let a=new AccountStore(filename,Date.now,secret),b=new AccountStore(filename,Date.now,secret);try{const holder={current:Dataset.load(fileURLToPath(new URL('../../../../data/public/v1',import.meta.url)))} as DatasetHolder;const svc=new EditorialService(new EditorialStore(new AdminStore(a)),holder),other=new EditorialService(new EditorialStore(new AdminStore(b)),holder);const id='persist';const command=(op:string,input:Record<string,unknown>):AdminCommand=>({actor:{type:'cli',id:'operator'},action:'weekly.'+op,targetType:'editorial_issue',targetId:id,reason:'persistence test',requestId:randomUUID(),idempotencyKey:randomUUID(),input,...(op==='create'?{}:{expectedVersion:svc.store.issue(id).version,currentVersion:()=>svc.store.issue(id).version})});svc.write(command('create',{periodEnd:end,selection:'persistent history',budget:0}),'create');svc.write(command('prepare',{coverage:'partial',coverageNote:'persistent limited coverage'}),'prepare');svc.write(command('runs',{stage:'curate'}),'runs');const worker=new EditorialWorker(svc),claimed=worker.claim()!;assert.ok(claimed);assert.equal(new EditorialWorker(other).claim(),null);assert.equal(other.store.inputs(id)[0]!.hash,svc.store.inputs(id)[0]!.hash);a.close();b.close();a=new AccountStore(filename,()=>Date.now()+600000,secret);b=new AccountStore(filename,Date.now,secret);const restarted=new EditorialWorker(new EditorialService(new EditorialStore(new AdminStore(a)),holder));assert.equal(restarted.recover(),1);assert.equal(restarted.store.run(String(claimed.id)).state,'needs_review');}finally{a.close();b.close();rmSync(root,{recursive:true,force:true});}});

test('active real-provider cancellation remains blocked until provider reconciliation',async()=>{const s=setup();try{const config={...JSON.parse(s.store.issue(s.id).config),adapter:'openai'};s.store.db.prepare('UPDATE editorial_issues SET config=? WHERE id=?').run(JSON.stringify(config),s.id);const run=s.write('runs',{stage:'curate'});const worker=new EditorialWorker(s.service);worker.claim();const rid=String(run.runId);s.service.cancel({...s.command('cancel'),targetId:rid,expectedVersion:Number(s.store.run(rid).version),currentVersion:()=>Number(s.store.run(rid).version)});assert.equal(s.store.run(rid).errorCode,'cancelled_outcome_unknown');assert.throws(()=>s.write('runs',{stage:'curate'}));s.service.reconcile({...s.command('reconcile',{outcome:'not_executed',note:'供应商核对夹具，不代表真实供应商验收',actualCost:null}),targetId:rid,expectedVersion:Number(s.store.run(rid).version),currentVersion:()=>Number(s.store.run(rid).version)});assert.ok(s.write('runs',{stage:'curate'}).runId);}finally{s.accounts.close();}});

test('migration failure rolls back all new tables and preserves old account data',()=>{const a=new AccountStore(':memory:',Date.now,'migration-three-test-secret-at-least32');try{const u=a.verify('legacy@example.test',a.issueCode('legacy@example.test'));a.saveState(u.user.id,'theme','light');const admin=new AdminStore(a);a.db.exec("CREATE TRIGGER reject_migration_three BEFORE INSERT ON admin_schema_migrations WHEN NEW.version=3 BEGIN SELECT RAISE(ABORT,'migration fault'); END");assert.throws(()=>new EditorialStore(admin));assert.equal(a.db.prepare("SELECT count(*) n FROM sqlite_master WHERE name LIKE 'editorial_%'").get()!.n,0);assert.equal(a.state(u.user.id).theme,'light');a.db.exec('DROP TRIGGER reject_migration_three');new EditorialStore(admin);new EditorialStore(admin);assert.equal(a.state(u.user.id).theme,'light');assert.equal(a.db.prepare('SELECT count(*) n FROM admin_schema_migrations WHERE version=3').get()!.n,1);}finally{a.close();}});

test('publication stays available on composition failure; corrections change current reader version without rewriting reports',async()=>{const s=setup();try{const pack=await manual(s);s.write('revisions',{package:pack});let r=approve(s);const pub=s.write('publish',{revision:r.revision,outputHash:r.outputHash});const audits=Number(s.store.db.prepare("SELECT count(*) n FROM admin_audit WHERE action='weekly.publish'").get()!.n);s.write('publish',{revision:r.revision,outputHash:r.outputHash});assert.equal(s.store.db.prepare("SELECT count(*) n FROM admin_audit WHERE action='weekly.publish'").get()!.n,audits);const u=s.accounts.verify('correction@example.test',s.accounts.issueCode('correction@example.test')).user;s.service.pro.activateBeta(u.id);s.service.pro.configure(u.id,{providers:pack.contents[0]!.providers,models:[],families:[],topics:['capability']},false);s.store.db.exec("CREATE TRIGGER composition_failure BEFORE INSERT ON pro_reports BEGIN SELECT RAISE(ABORT,'compose fault'); END");assert.throws(()=>s.write('compose',{queueMail:false}));assert.equal(s.store.db.prepare('SELECT compositionState FROM editorial_publications WHERE id=?').get(String(pub.publicationId))!.compositionState,'pending');assert.equal(s.service.pro.contents().length,2);s.store.db.exec('DROP TRIGGER composition_failure');s.write('compose',{queueMail:false});const reportId=String(s.service.pro.reports(u.id)[0]!.id);for(const c of pack.contents){c.correction='隔离更正：补充局限';c.body+='\n修订内容';c.critical=true;}s.write('revisions',{package:pack});r=approve(s);s.write('publish',{revision:r.revision,outputHash:r.outputHash});assert.equal(s.service.pro.get(pack.contents[0]!.id,u.id).version,2);const report=s.service.pro.report(u.id,reportId);assert.ok(report.items.every(c=>'selectedVersion' in c&&c.selectedVersion===1&&c.version===2));assert.equal(s.write('compose',{queueMail:true}).created,0);assert.equal(s.store.db.prepare('SELECT count(*) n FROM pro_mail').get()!.n,0);}finally{s.accounts.close();}});
