import http from 'node:http';
import {createProHandler} from '../pro-http.js';
import {createPaymentWebhook} from '../payment-http.js';
import type {DatasetHolder} from '../dataset.js';
import {PaymentSimulator} from '../payment-simulator.js';
import {reconcilePayments} from '../payment-reconciliation.js';
import {AdminPayments} from '../admin-payments.js';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import {AccountStore} from '../account-store.js';
import {AdminStore} from '../admin-store.js';
import {ProStore} from '../pro-store.js';
import {PaymentStore,paymentMonthEnd,checkedMinorTotal,verifyPaymentSignature,type PaymentFact} from '../payment-store.js';
function fixture(){let now=1800000000000;const a=new AccountStore(':memory:',()=>now,'isolated-payment-secret-more-than-32-characters');const login=a.verify('pay@example.test',a.issueCode('pay@example.test')),u=login.user;const admin=new AdminStore(a),p=new PaymentStore(admin),pro=new ProStore(a);const o=p.createOrder(u.id,'first');const fact=(kind:PaymentFact['kind']='paid',extra:Partial<PaymentFact>={})=>({id:randomUUID(),kind,orderId:String(o.id),subscriptionId:String(o.subscriptionId),objectId:randomUUID(),currency:'USD',amount:990,starts:now-1,ends:now+100000,occurredAt:now,...extra});const accept=(f:PaymentFact,key:string=randomUUID())=>{const e=p.receive('simulator',key,Buffer.from(JSON.stringify(f)));p.process(e,f);return e;};return {a,u,session:login.session,admin,p,pro,o,fact,accept,setNow:(n:number)=>now=n,now:()=>now};}
test('T08 paid independent source, successful payment required, expiration and beta fallback',()=>{const f=fixture();try{assert.notEqual(f.pro.entitlement(f.u.id).status,'active');f.pro.activateBeta(f.u.id);assert.equal(f.pro.entitlement(f.u.id).source,'beta');f.accept(f.fact());assert.equal(f.pro.entitlement(f.u.id).source,'paid');f.setNow(f.now()+100001);assert.equal(f.pro.entitlement(f.u.id).source,'beta');}finally{f.a.close();}});
test('T08 duplicate events/facts, conflict, amount verification and failed event recovery persist',()=>{const f=fixture();try{const fact=f.fact(),e=f.accept(fact,'provider-event');f.p.process(e,fact);assert.equal(f.a.db.prepare('SELECT count(*) n FROM paid_facts').get()!.n,1);assert.throws(()=>f.p.receive('simulator','provider-event',Buffer.from('{}')));const bad=f.fact('paid',{id:fact.id,objectId:fact.objectId,amount:1}),id=f.p.receive('simulator','bad',Buffer.from(JSON.stringify(bad)));assert.throws(()=>f.p.process(id,bad));assert.equal(f.a.db.prepare("SELECT state FROM paid_event_results WHERE eventId=? ORDER BY rowid DESC").get(id)!.state,'failed');f.p.process(id,fact);assert.equal(f.a.db.prepare("SELECT state FROM paid_event_results WHERE eventId=? ORDER BY rowid DESC").get(id)!.state,'processed');}finally{f.a.close();}});
test('T08 refund submission reserves balance, completed partial retains and cumulative full removes paid',()=>{const f=fixture();try{f.accept(f.fact());const r=f.p.refund(String(f.o.id),500,'r1');assert.equal(f.p.refund(String(f.o.id),500,'r1').id,r.id);assert.throws(()=>f.p.refund(String(f.o.id),491,'r2'));assert.equal(f.pro.entitlement(f.u.id).source,'paid');f.accept(f.fact('refund',{amount:500}));assert.equal(f.pro.entitlement(f.u.id).source,'paid');f.accept(f.fact('refund',{amount:490}));assert.notEqual(f.pro.entitlement(f.u.id).source,'paid');assert.throws(()=>f.accept(f.fact('refund',{amount:1})));}finally{f.a.close();}});
test('T08 renewal failure/cancellation are distinct from termination and dispute',()=>{const f=fixture();try{f.accept(f.fact());f.accept(f.fact('failed'));f.accept(f.fact('cancel'));assert.equal(f.pro.entitlement(f.u.id).source,'paid');f.accept(f.fact('dispute'));assert.notEqual(f.pro.entitlement(f.u.id).source,'paid');f.setNow(f.now()+1);f.accept(f.fact('dispute_won'));assert.equal(f.pro.entitlement(f.u.id).source,'paid');f.accept(f.fact('terminate'));assert.notEqual(f.pro.entitlement(f.u.id).source,'paid');}finally{f.a.close();}});
test('T08 signed raw bytes verify freshness and reject mutation',()=>{const raw=Buffer.from('{"isolated":true}'),secret='mock-secret',now=1800000000000,t=String(now/1000),sig=createHmac('sha256',secret).update(t+'.').update(raw).digest('hex');verifyPaymentSignature(raw,`t=${t},v1=${sig}`,secret,now);assert.throws(()=>verifyPaymentSignature(Buffer.from('{}'),`t=${t},v1=${sig}`,secret,now));assert.throws(()=>verifyPaymentSignature(raw,`t=${t},v1=${sig}`,secret,now+301000));});
test('T08 additive migration rollback preserves accounts and is repeatable',()=>{const f=fixture();try{new PaymentStore(f.admin);assert.equal(f.a.db.prepare('SELECT count(*) n FROM admin_schema_migrations WHERE version=8').get()!.n,1);assert.ok(f.a.db.prepare('SELECT 1 FROM users WHERE id=?').get(f.u.id));f.a.db.exec('DELETE FROM admin_schema_migrations WHERE version=8');assert.throws(()=>new PaymentStore(f.admin));assert.equal(f.a.db.prepare('SELECT 1 FROM admin_schema_migrations WHERE version=8').get(),undefined);assert.ok(f.a.db.prepare('SELECT 1 FROM paid_orders').get());}finally{f.a.close();}});
test('T08 simulator authoritative lookup supports missing callback recovery and out of order renewal',()=>{const f=fixture();try{const sim=new PaymentSimulator(f.p),first=sim.publish(f.fact());sim.deliver(first.id);const o2=f.p.createOrder(f.u.id,'renewal','USD',990,String(f.o.subscriptionId));const renewal=sim.publish(f.fact('paid',{orderId:String(o2.id),starts:f.now()+100000,ends:f.now()+200000}));f.p.receive('simulator','lost_callback',Buffer.from(JSON.stringify({objectId:renewal.id})));assert.deepEqual(sim.recover(),{processed:1,failed:0});sim.deliver(first.id,'late_original');assert.equal(f.a.db.prepare("SELECT count(*) n FROM paid_facts WHERE kind='paid'").get()!.n,2);f.setNow(f.now()+100001);assert.equal(f.pro.entitlement(f.u.id).ends,Number(renewal.ends));}finally{f.a.close();}});
test('T08 final simulator refund separate from requested state; immutable histories',()=>{const f=fixture();try{const sim=new PaymentSimulator(f.p);f.accept(f.fact());const r=f.p.refund(String(f.o.id),990,'refund_full');assert.equal(f.pro.entitlement(f.u.id).source,'paid');sim.completeRefund(String(r.id),'succeeded');sim.completeRefund(String(r.id),'succeeded');assert.throws(()=>sim.completeRefund(String(r.id),'failed'));assert.notEqual(f.pro.entitlement(f.u.id).source,'paid');assert.throws(()=>f.a.db.exec('DELETE FROM paid_facts'));assert.throws(()=>f.a.db.exec("UPDATE paid_events SET payload='{}'"));}finally{f.a.close();}});
test('T08 reconciliation isolates currencies and unknown settlement, records discrepancies and append-only handling',()=>{const f=fixture();try{const paid=f.fact();f.accept(paid);const result=reconcilePayments(f.p,{currency:'USD',from:f.now()-100,to:f.now()+100,source:'isolated_simulator_snapshot',records:[{kind:'paid',objectId:paid.objectId,amount:980,currency:'USD',occurredAt:f.now()}]});assert.equal(result.differences,1);assert.equal(result.settlement,null);assert.equal(result.fees,null);assert.throws(()=>reconcilePayments(f.p,{currency:'USD',from:f.now()-100,to:f.now()+100,source:'fixture',records:[{kind:'paid',objectId:'foreign',amount:990,currency:'EUR',occurredAt:f.now()}]}));const a=new AdminPayments(f.admin),diff=String(a.list('differences',new URLSearchParams()).items[0]!.id);a.annotate({actor:{type:'cli',id:'operator'},action:'payments.annotate',targetType:'payment_difference',targetId:diff,reason:'verify fixture',requestId:'test',idempotencyKey:'note1',input:{note:'Supplier fixture differs by 10 minor units'}});assert.equal(f.a.db.prepare('SELECT count(*) n FROM paid_difference_actions').get()!.n,1);assert.equal(a.totals(new URLSearchParams({from:new Date(f.now()-1).toISOString(),to:new Date(f.now()+1).toISOString()})).revenue,990);}finally{f.a.close();}});
test('T08 administrative refund business and audit rollback atomically',()=>{const f=fixture();try{f.accept(f.fact());const a=new AdminPayments(f.admin),c={actor:{type:'cli' as const,id:'operator'},action:'payments.refund',targetType:'payment_order',targetId:String(f.o.id),reason:'fixture',requestId:'test',idempotencyKey:'atomic',input:{amount:990}};f.a.db.exec("CREATE TRIGGER fail_payment_audit BEFORE INSERT ON admin_audit BEGIN SELECT RAISE(ABORT,'fixture failure'); END;");assert.throws(()=>a.refund(c));assert.equal(f.a.db.prepare('SELECT count(*) n FROM paid_refunds').get()!.n,0);f.a.db.exec('DROP TRIGGER fail_payment_audit');const r=a.refund(c);assert.equal(a.refund(c).id,r.id);assert.equal(f.a.db.prepare('SELECT count(*) n FROM paid_refunds').get()!.n,1);}finally{f.a.close();}});
test('T08 local simulator HTTP authenticates ownership, ignores browser return, verifies callback and cancellation',async()=>{const f=fixture(),old=process.env.MAAS_PAYMENT_MODE,oldSecret=process.env.MAAS_PAYMENT_WEBHOOK_SECRET;let server:http.Server|undefined;try{process.env.MAAS_PAYMENT_MODE='simulator';process.env.MAAS_PAYMENT_WEBHOOK_SECRET='isolated-webhook';const session=f.session;let origin='';server=http.createServer((req,res)=>{const cfg={origin,secure:false,trustProxy:false};if(req.url==='/api/payment/webhook')void createPaymentWebhook(f.p,origin)(req,res);else void createProHandler(f.pro,{} as DatasetHolder,cfg,false)(req,res);});await new Promise<void>(resolve=>server!.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+(server.address() as {port:number}).port;const cookie='maas_session='+session;const request=(route:string,input?:unknown,authenticated=true)=>fetch(origin+'/api/pro/'+route,{headers:{...(authenticated?{Cookie:cookie}:{}),...(input?{'Content-Type':'application/json',Origin:origin}:{})},...(input?{method:'POST',body:JSON.stringify(input)}:{})});assert.equal((await request('billing',undefined,false)).status,401);const checkout=await (await request('billing/checkout',{key:'http'})).json() as {orderId:string};assert.ok(checkout.orderId);assert.notEqual(f.pro.entitlement(f.u.id).source,'paid');await request('billing?success=true');assert.notEqual(f.pro.entitlement(f.u.id).source,'paid');const unknown=f.fact('paid',{id:'authoritative-http',orderId:checkout.orderId,subscriptionId:String(f.p.order(checkout.orderId).subscriptionId)}),sim=new PaymentSimulator(f.p);sim.publish(unknown);const raw=JSON.stringify({id:'signed-http-event',objectId:unknown.id}),t=String(f.now()/1000),signature=createHmac('sha256','isolated-webhook').update(t+'.'+raw).digest('hex');const send=()=>fetch(origin+'/api/payment/webhook',{method:'POST',headers:{'payment-signature':`t=${t},v1=${signature}`},body:raw});assert.equal((await send()).status,202);assert.equal((await send()).status,202);assert.equal(f.pro.entitlement(f.u.id).source,'paid');assert.equal((await request('billing/cancel',{orderId:checkout.orderId})).status,200);assert.equal(f.pro.entitlement(f.u.id).source,'paid');const billing=await (await request('billing')).json() as {subscriptions:{cancelAtPeriodEnd:boolean}[]};assert.ok(billing.subscriptions.some(s=>s.cancelAtPeriodEnd===true));assert.equal((await fetch(origin+'/api/payment/webhook',{method:'POST',body:raw})).status,400);}finally{if(server)await new Promise<void>(resolve=>server!.close(()=>resolve()));if(old===undefined)delete process.env.MAAS_PAYMENT_MODE;else process.env.MAAS_PAYMENT_MODE=old;if(oldSecret===undefined)delete process.env.MAAS_PAYMENT_WEBHOOK_SECRET;else process.env.MAAS_PAYMENT_WEBHOOK_SECRET=oldSecret;f.a.close();}});

test('T08 month-end anchors, cancellation prevents future renewal orders, aggregate integers checked',()=>{assert.equal(new Date(paymentMonthEnd(Date.parse('2026-01-31T10:00:00Z'))).toISOString(),'2026-02-28T10:00:00.000Z');assert.throws(()=>checkedMinorTotal(Number.MAX_SAFE_INTEGER+1));const f=fixture();try{f.accept(f.fact('cancel'));assert.throws(()=>f.p.createOrder(f.u.id,'blocked','USD',990,String(f.o.subscriptionId)));}finally{f.a.close();}});
