#!/usr/bin/env python3
"""AR-03 generator v1: deterministic JSON Schema DTO subset + self-contained TS bridges.

Unsupported structural keywords fail closed. Validation constraints do not become TS runtime checks.
"""
import argparse
import json
import re
from pathlib import Path
BASE = Path(__file__).resolve().parents[1]
SCHEMAS = BASE / 'schemas/public-v1'
NAMES = {'change': 'ChangeDTO', 'record': 'ItemDTO', 'price': 'PriceDTO', 'evidence': 'EvidenceDTO', 'weekly': 'WeeklyDTO', 'status': 'StatusDTO', 'manifest': 'ManifestDTO', 'model-identities': 'ModelIdentityCatalogDTO'}


def compile_type(node, source):
    for key in ('oneOf', 'anyOf', 'not', 'if', 'then', 'else', 'dependentSchemas', 'patternProperties', 'prefixItems'):
        if key in node: raise ValueError('unsupported schema construct: ' + key)
    if '$ref' in node:
        filename, _, fragment = node['$ref'].partition('#')
        target = json.loads((SCHEMAS / (filename or source)).read_text())
        for part in fragment.strip('/').split('/') if fragment else []: target = target[part]
        return compile_type(target, filename or source)
    if 'allOf' in node: return '(' + ' & '.join(compile_type(x, source) for x in node['allOf']) + ')'
    if 'const' in node: return json.dumps(node['const'], ensure_ascii=False)
    if 'enum' in node: return ' | '.join(json.dumps(x, ensure_ascii=False) for x in node['enum'])
    kinds = node.get('type', 'object' if 'properties' in node else None)
    if isinstance(kinds, list): return '(' + ' | '.join(compile_type({**node, 'type': k}, source) for k in kinds) + ')'
    if kinds == 'array': return 'Array<' + compile_type(node.get('items', {}), source) + '>'
    if kinds == 'object':
        fields = [json.dumps(key) + ('' if key in node.get('required', []) else '?') + ': ' + compile_type(value, source) + ';' for key, value in node.get('properties', {}).items()]
        extra = node.get('additionalProperties', True)
        if extra is True: fields.append('[key: string]: unknown;')
        elif isinstance(extra, dict): fields.append('[key: string]: ' + compile_type(extra, source) + ';')
        return '{ ' + ' '.join(fields) + ' }'
    if kinds in ('string', 'boolean', 'null'): return kinds
    if kinds in ('number', 'integer'): return 'number'
    if kinds is None: return 'unknown'
    raise ValueError('unsupported type: ' + str(kinds))


def main():
    parser = argparse.ArgumentParser(description=__doc__); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    generated = '// Generated by scripts/generate-public-contract.py v1; do not edit.\n'
    for name, dto in NAMES.items(): generated += 'export type ' + dto + ' = ' + compile_type(json.loads((SCHEMAS / (name + '.schema.json')).read_text()), name + '.schema.json') + ';\n'
    targets = {'schema-dto.ts': generated}
    for filename in ('entities.ts', 'validation.ts', 'node-reader.ts'):
        p = BASE / 'packages/public-contract' / filename
        if p.exists(): targets[filename] = '// Generated bridge; canonical source: packages/public-contract/' + filename + '\n' + p.read_text()
    failures = []
    for name, content in targets.items():
        paths = [BASE / 'services/agent-api/src/public-contract' / name, BASE / 'site/src/lib/public-contract' / name]
        if name == 'schema-dto.ts': paths.insert(0, BASE / 'packages/public-contract' / name)
        for p in paths:
            emitted = re.sub(r'(from [\'\"]\./[^\'\"]+)\.js([\'\"])', r'\1.ts\2', content) if 'site/src/lib/public-contract' in str(p) else content
            if args.check:
                if not p.exists() or p.read_text() != emitted: failures.append(str(p.relative_to(BASE)))
            else: p.parent.mkdir(parents=True, exist_ok=True); p.write_text(emitted)
    if failures: raise SystemExit('generated contract drift: ' + ', '.join(failures))
    print('public contract generation ' + ('checked' if args.check else 'complete'))

if __name__ == '__main__': main()
